import { useEffect, useState } from 'react';
import { Button, Dialog, DialogActions, DialogContent, DialogTitle, Grid, MenuItem, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import { api } from '../../../../api/client';
import type { Environment, Group, User } from '../../../../types';
import { EffectivePermissionsTab } from './EffectivePermissionsTab';
import { UserEnvironmentsTab } from './UserEnvironmentsTab';
import { UserGroupsTab } from './UserGroupsTab';
import { UserPermissionsTab } from './UserPermissionsTab';

export function UserEditor({ user, users, groups, environments, onClose, onSaved }: { user?: User; users: User[]; groups: Group[]; environments: Environment[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const [tab, setTab] = useState(0); const [values, setValues] = useState<Partial<User>>({});
  useEffect(() => { if (user) { setTab(0); setValues(user); } }, [user]);
  async function saveDetails() { if (!user) return; const fields = ['first_name','last_name','display_name','email','user_principal_name','department','job_title','phone','mobile_phone','employee_id','computer_identifier','status','is_system_admin']; await api(`/users/${user.id}`, { method: 'PATCH', body: JSON.stringify(Object.fromEntries(fields.map((key) => [key, values[key as keyof User] ?? null]))) }); await onSaved(); }
  const field = (key: keyof User, label: string) => <TextField fullWidth label={label} value={String(values[key] ?? '')} onChange={(event) => setValues({ ...values, [key]: event.target.value })}/>;
  return <Dialog open={!!user} onClose={onClose} fullWidth maxWidth="lg"><DialogTitle><Typography variant="h5" fontWeight={800}>{user?.display_name}</Typography><Typography variant="body2" color="text.secondary">כרטיס משתמש והרשאות</Typography></DialogTitle>{user && <><Tabs value={tab} onChange={(_, value) => setTab(value)} variant="scrollable"><Tab label="פרטים"/><Tab label="קבוצות"/><Tab label="סביבות"/><Tab label="הרשאות"/><Tab label="הרשאות אפקטיביות"/></Tabs><DialogContent dividers>{tab === 0 && <Stack spacing={2}><Grid container spacing={2}><Grid size={{xs:12,sm:6}}>{field('first_name','שם פרטי')}</Grid><Grid size={{xs:12,sm:6}}>{field('last_name','שם משפחה')}</Grid><Grid size={{xs:12,sm:6}}>{field('display_name','שם תצוגה')}</Grid><Grid size={{xs:12,sm:6}}>{field('email','דוא״ל')}</Grid><Grid size={{xs:12,sm:6}}>{field('user_principal_name','שם משתמש / UPN')}</Grid><Grid size={{xs:12,sm:6}}>{field('department','מחלקה')}</Grid><Grid size={{xs:12,sm:6}}>{field('job_title','תפקיד ארגוני')}</Grid><Grid size={{xs:12,sm:6}}>{field('employee_id','מספר עובד')}</Grid><Grid size={{xs:12,sm:6}}>{field('phone','טלפון')}</Grid><Grid size={{xs:12,sm:6}}>{field('mobile_phone','טלפון נייד')}</Grid><Grid size={{xs:12,sm:6}}>{field('computer_identifier','מזהה מחשב')}</Grid><Grid size={{xs:12,sm:6}}><TextField select fullWidth label="מצב" value={values.status || 'active'} onChange={(event) => setValues({...values,status:event.target.value as User['status']})}><MenuItem value="active">פעיל</MenuItem><MenuItem value="inactive">לא פעיל</MenuItem><MenuItem value="archived">בארכיון</MenuItem></TextField></Grid></Grid><Button variant="contained" onClick={saveDetails}>שמירת פרטים</Button></Stack>}{tab === 1 && <UserGroupsTab user={user} users={users} groups={groups} onSaved={onSaved}/>} {tab === 2 && <UserEnvironmentsTab user={user} users={users} environments={environments} onSaved={onSaved}/>} {tab === 3 && <UserPermissionsTab user={user} environments={environments}/>} {tab === 4 && <EffectivePermissionsTab user={user} environments={environments}/>}</DialogContent></>}<DialogActions><Button onClick={onClose}>סגירה</Button></DialogActions></Dialog>;
}
