import { useEffect, useState } from 'react';
import { Alert, Button, Chip, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { api } from '../../../../api/client';
import type { Environment, Role, User } from '../../../../types';

type Selection = { environment_id: string; role_id: string };
type Preview = { source_count: number; targets: { changed: boolean }[] };
export function UserEnvironmentsTab({ user, users, environments, roles, onSaved }: { user: User; users: User[]; environments: Environment[]; roles: Role[]; onSaved: () => Promise<void> }) {
  const [rows, setRows] = useState<Selection[]>([]); const [targets, setTargets] = useState<string[]>([]); const [mode, setMode] = useState<'add_missing' | 'replace_all'>('add_missing'); const [preview, setPreview] = useState<Preview>(); const [message, setMessage] = useState('');
  useEffect(() => { setRows(user.memberships?.map((item) => ({ environment_id: item.environment_id, role_id: item.role_id })) || []); setTargets([]); setPreview(undefined); }, [user]);
  const ids = rows.map((row) => row.environment_id); const available = environments.filter((environment) => environment.is_active || ids.includes(environment.id));
  async function save() { await api(`/users/${user.id}/environment-memberships`, { method: 'PUT', body: JSON.stringify(rows) }); setMessage('סביבות העבודה נשמרו'); await onSaved(); }
  const payload = { source_user_id: user.id, target_user_ids: targets, mode };
  async function previewCopy() { setPreview(await api<Preview>('/users/environment-memberships/copy/preview', { method: 'POST', body: JSON.stringify(payload) })); }
  async function copy() { await api('/users/environment-memberships/copy', { method: 'POST', body: JSON.stringify(payload) }); setMessage('הסביבות והתפקידים הועתקו'); setPreview(undefined); await onSaved(); }
  return <Stack spacing={2}>{message && <Alert severity="success">{message}</Alert>}<TextField select SelectProps={{ multiple: true, renderValue: (value) => <Stack direction="row" gap={.5}>{(value as string[]).map((id) => <Chip key={id} label={environments.find((environment) => environment.id === id)?.name_he}/>)}</Stack> }} label="סביבות משויכות" value={ids} onChange={(event) => { const selected = typeof event.target.value === 'string' ? event.target.value.split(',') : event.target.value; setRows(selected.map((id) => rows.find((row) => row.environment_id === id) || { environment_id: id, role_id: roles.find((role) => role.scope === 'environment' && role.is_active)?.id || '' })); }}>{available.map((environment) => <MenuItem key={environment.id} value={environment.id}>{environment.name_he}{!environment.is_active ? ' · לא פעילה' : ''}</MenuItem>)}</TextField>{rows.map((row) => <Stack key={row.environment_id} direction={{ xs: 'column', sm: 'row' }} gap={1}><TextField fullWidth label="סביבה" value={environments.find((environment) => environment.id === row.environment_id)?.name_he || ''} slotProps={{ input: { readOnly: true } }}/><TextField fullWidth select label="תפקיד" value={row.role_id} onChange={(event) => setRows(rows.map((item) => item.environment_id === row.environment_id ? { ...item, role_id: event.target.value } : item))}>{roles.filter((role) => role.scope === 'environment' && role.is_active).map((role) => <MenuItem key={role.id} value={role.id}>{role.name_he || role.name}</MenuItem>)}</TextField></Stack>)}<Button variant="contained" disabled={rows.some((row) => !row.role_id)} onClick={save}>שמירת סביבות</Button>
    <Paper variant="outlined" sx={{ p: 2 }}><Stack spacing={2}><Typography variant="h6">העתקת סביבות ותפקידים</Typography><TextField select SelectProps={{ multiple: true }} label="משתמשי יעד" value={targets} onChange={(event) => { setTargets(typeof event.target.value === 'string' ? event.target.value.split(',') : event.target.value); setPreview(undefined); }}>{users.filter((item) => item.id !== user.id).map((item) => <MenuItem key={item.id} value={item.id}>{item.display_name}</MenuItem>)}</TextField><TextField select label="אופן ההעתקה" value={mode} onChange={(event) => { setMode(event.target.value as typeof mode); setPreview(undefined); }}><MenuItem value="add_missing">הוספת החסרות</MenuItem><MenuItem value="replace_all">החלפה מלאה</MenuItem></TextField><Button disabled={!targets.length} onClick={previewCopy}>תצוגה מקדימה</Button>{preview && <Alert severity="info">למקור {preview.source_count} סביבות; {preview.targets.filter((target) => target.changed).length} משתמשים ישתנו.</Alert>}<Button variant="outlined" disabled={!preview} onClick={copy}>אישור והעתקה</Button></Stack></Paper></Stack>;
}
