import { useEffect, useState } from 'react';
import { Button, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, Stack, Switch, Tab, Tabs, TextField, Typography } from '@mui/material';
import { api } from '../../../../api/client';
import type { Environment, Group, Role, User } from '../../../../types';
import { EffectivePermissionsTab } from './EffectivePermissionsTab';
import { UserEnvironmentsTab } from './UserEnvironmentsTab';
import { UserGroupsTab } from './UserGroupsTab';
import { UserPermissionsTab } from './UserPermissionsTab';

export function UserEditor({ user, users, groups, environments, roles, onClose, onSaved }: { user?: User; users: User[]; groups: Group[]; environments: Environment[]; roles: Role[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const [tab, setTab] = useState(0); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [active, setActive] = useState(true); const [admin, setAdmin] = useState(false);
  useEffect(() => { if (user) { setTab(0); setName(user.display_name); setEmail(user.email); setActive(user.is_active !== false); setAdmin(user.is_system_admin); } }, [user]);
  async function saveDetails() { if (!user) return; await api(`/users/${user.id}`, { method: 'PATCH', body: JSON.stringify({ display_name: name, email, is_active: active, is_system_admin: admin }) }); await onSaved(); }
  return <Dialog open={!!user} onClose={onClose} fullWidth maxWidth="lg" fullScreen={window.innerWidth < 600}><DialogTitle><Typography variant="h5" fontWeight={800}>{user?.display_name}</Typography><Typography variant="body2" color="text.secondary">כרטיס משתמש והרשאות</Typography></DialogTitle>{user && <><Tabs value={tab} onChange={(_, value) => setTab(value)} variant="scrollable"><Tab label="פרטים"/><Tab label="קבוצות"/><Tab label="סביבות"/><Tab label="הרשאות"/><Tab label="הרשאות אפקטיביות"/></Tabs><DialogContent dividers>{tab === 0 && <Stack spacing={2}><TextField label="שם" value={name} onChange={(event) => setName(event.target.value)}/><TextField label="מייל" value={email} onChange={(event) => setEmail(event.target.value)}/><FormControlLabel control={<Switch checked={active} onChange={(event) => setActive(event.target.checked)}/>} label="משתמש פעיל"/><FormControlLabel control={<Switch checked={admin} onChange={(event) => setAdmin(event.target.checked)}/>} label="מנהל מערכת"/><Typography>תאריך יצירה: {user.created_at ? new Date(user.created_at).toLocaleString('he-IL') : 'לא זמין'}</Typography><Typography>התחברות אחרונה: {user.last_login_at ? new Date(user.last_login_at).toLocaleString('he-IL') : 'טרם התחבר'}</Typography><Button variant="contained" onClick={saveDetails}>שמירת פרטים</Button></Stack>}{tab === 1 && <UserGroupsTab user={user} users={users} groups={groups} onSaved={onSaved}/>} {tab === 2 && <UserEnvironmentsTab user={user} users={users} environments={environments} roles={roles} onSaved={onSaved}/>} {tab === 3 && <UserPermissionsTab user={user} environments={environments}/>} {tab === 4 && <EffectivePermissionsTab user={user} environments={environments}/>}</DialogContent></>}<DialogActions><Button onClick={onClose}>סגירה</Button></DialogActions></Dialog>;
}
