import { useEffect, useState } from 'react';
import { Button, FormControlLabel, MenuItem, Paper, Stack, Switch, TextField, Typography } from '@mui/material';
import type { AutomationRule, Environment } from '../../../../types';
import { FieldSelector } from './FieldSelector';
import { FieldValueSelector } from './FieldValueSelector';
import type { FieldDiscovery } from './types';

export function AutomationRuleEditor({ environment, fields, rule, onSave, onCancel }: { environment: Environment; fields: FieldDiscovery; rule?: AutomationRule; onSave: (payload: object) => Promise<void>; onCancel: () => void }) {
  const [name, setName] = useState(''); const [active, setActive] = useState(true); const [triggerField, setTriggerField] = useState(''); const [operator,setOperator]=useState('equals'); const [triggerValue, setTriggerValue] = useState(''); const [targetField, setTargetField] = useState(''); const [targetValue, setTargetValue] = useState('');
  const unary=['is_empty','is_not_empty'].includes(operator);
  useEffect(() => { const condition = rule?.conditions_json.conditions?.[0]; const action = rule?.actions_json?.[0] as { field_id?: string; field_code?: string; value_id?: string; value?: string } | undefined; setName(rule?.name || ''); setActive(rule?.is_active !== false); setTriggerField(condition?.field || ''); setOperator(condition?.operator||'equals'); setTriggerValue(String(condition?.value || '')); setTargetField(action?.field_id||action?.field_code || ''); setTargetValue(String(action?.value_id || action?.value || '')); }, [rule]);
  const save = () => onSave({ environment_id: environment.id, name, description: null, is_active: active, trigger_type:'case_created', conditions_json: { logic: 'AND', conditions: [{ field: triggerField, operator, ...(unary?{}:{value:triggerValue}) }] }, actions_json: [{ type: 'set_field', field_id: targetField, value_id: targetValue }], priority: rule?.priority || 0 });
  return <Paper variant="outlined" sx={{ p: 2 }}><Stack spacing={2}><Typography variant="h6" fontWeight={650}>{rule ? 'עריכת אוטומציה' : 'אוטומציה חדשה'}</Typography><TextField label="שם הכלל" value={name} onChange={(event) => setName(event.target.value)}/><FormControlLabel control={<Switch checked={active} onChange={(event) => setActive(event.target.checked)}/>} label="פעיל"/><FieldSelector label="שדה טריגר" fields={fields.trigger_fields} value={triggerField} onChange={(value) => { setTriggerField(value); setTriggerValue(''); }}/><TextField select label="תנאי" value={operator} onChange={event=>setOperator(event.target.value)}><MenuItem value="equals">שווה ל</MenuItem><MenuItem value="not_equals">שונה מ</MenuItem><MenuItem value="is_empty">ריק</MenuItem><MenuItem value="is_not_empty">אינו ריק</MenuItem></TextField>{!unary&&<FieldValueSelector environmentId={environment.id} fieldCode={triggerField} label="ערך טריגר" value={triggerValue} onChange={setTriggerValue}/>}<FieldSelector label="שדה לשינוי" fields={fields.target_fields} value={targetField} onChange={(value) => { setTargetField(value); setTargetValue(''); }}/><FieldValueSelector environmentId={environment.id} fieldCode={targetField} label="ערך לשינוי" value={targetValue} onChange={setTargetValue}/><Stack direction="row" gap={1}><Button variant="contained" disabled={!name || !triggerField || (!unary&&!triggerValue) || !targetField || !targetValue} onClick={save}>שמירה</Button>{rule && <Button onClick={onCancel}>ביטול עריכה</Button>}</Stack></Stack></Paper>;
}
