import { useEffect, useState } from 'react';
import { Button, FormControlLabel, Paper, Stack, Switch, TextField, Typography } from '@mui/material';
import type { AutomationRule, Environment } from '../../../../types';
import { FieldSelector } from './FieldSelector';
import { FieldValueSelector } from './FieldValueSelector';
import type { FieldDiscovery } from './types';

const triggerType = (code: string) => ({ request_type: 'request_type_selected', status: 'status_changed', priority: 'priority_changed' }[code] || 'field_value_changed');
export function AutomationRuleEditor({ environment, fields, rule, onSave, onCancel }: { environment: Environment; fields: FieldDiscovery; rule?: AutomationRule; onSave: (payload: object) => Promise<void>; onCancel: () => void }) {
  const [name, setName] = useState(''); const [active, setActive] = useState(true); const [triggerField, setTriggerField] = useState(''); const [triggerValue, setTriggerValue] = useState(''); const [targetField, setTargetField] = useState(''); const [targetValue, setTargetValue] = useState('');
  useEffect(() => { const condition = rule?.conditions_json.conditions?.[0]; const action = rule?.actions_json?.[0] as { field_code?: string; value_id?: string; value?: string } | undefined; setName(rule?.name || ''); setActive(rule?.is_active !== false); setTriggerField(condition?.field || ''); setTriggerValue(String(condition?.value || '')); setTargetField(action?.field_code || ''); setTargetValue(String(action?.value_id || action?.value || '')); }, [rule]);
  const save = () => onSave({ environment_id: environment.id, name, description: null, is_active: active, trigger_type: triggerType(triggerField), conditions_json: { logic: 'AND', conditions: [{ field: triggerField, operator: 'equals', value: triggerValue }] }, actions_json: [{ type: 'set_field', field_code: targetField, value_id: targetValue }], priority: rule?.priority || 0 });
  return <Paper variant="outlined" sx={{ p: 2 }}><Stack spacing={2}><Typography variant="h6" fontWeight={800}>{rule ? 'עריכת אוטומציה' : 'אוטומציה חדשה'}</Typography><TextField label="שם הכלל" value={name} onChange={(event) => setName(event.target.value)}/><FormControlLabel control={<Switch checked={active} onChange={(event) => setActive(event.target.checked)}/>} label="פעיל"/><FieldSelector label="שדה טריגר" fields={fields.trigger_fields} value={triggerField} onChange={(value) => { setTriggerField(value); setTriggerValue(''); }}/><FieldValueSelector environmentId={environment.id} fieldCode={triggerField} label="ערך טריגר" value={triggerValue} onChange={setTriggerValue}/><FieldSelector label="שדה לשינוי" fields={fields.target_fields} value={targetField} onChange={(value) => { setTargetField(value); setTargetValue(''); }}/><FieldValueSelector environmentId={environment.id} fieldCode={targetField} label="ערך לשינוי" value={targetValue} onChange={setTargetValue}/><Stack direction="row" gap={1}><Button variant="contained" disabled={!name || !triggerField || !triggerValue || !targetField || !targetValue} onClick={save}>שמירה</Button>{rule && <Button onClick={onCancel}>ביטול עריכה</Button>}</Stack></Stack></Paper>;
}
