import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Box, Button, Card, CardActionArea, CardContent, Container, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { api } from '../../api/client';
import { CompactFilterPanel } from '../../components/filters/CompactFilterPanel';
import { approvalStatusHe as statusHe, reportFields as fields, type ReportKind as Kind } from './reportConfig';
import { displayCaseNumber } from '../cases/details/caseDisplay';
import { openCase as navigateToCase } from '../../navigation/caseNavigation';
import { readReportState, writeReportState } from './reportUrlState';

type Filters=Record<string,string>;type Option={id:string;label:string};
type FilterOptions={environments:Option[];request_types:(Option&{environment_id:string})[];users:Option[];groups:Option[];departments:string[];job_titles:string[];approval_statuses:Option[];approval_steps:string[]};
const titles={approvals:'דוח אישורים',users:'דוח משתמשים והרשאות',audit:'דוח Audit'};
const labels:Record<string,string>={case_number:'מספר קריאה',subject:'נושא',environment:'סביבה',request_type:'סוג קריאה',approver:'מאשר',step:'שלב',status:'סטטוס',requested_at:'מועד בקשה',decided_at:'מועד החלטה',user:'משתמש',email:'דוא״ל',username:'שם משתמש',source:'מקור',department:'מחלקה',job_title:'תפקיד ארגוני',groups:'קבוצות',environments:'סביבות',permissions:'הרשאות',action:'פעולה',entity:'סוג ישות',entity_id:'מזהה ישות',created_at:'מועד'};

export function OperationalReportPage({kind}:{kind:Kind}){
  const client=useQueryClient();const navigate=useNavigate();const location=useLocation();const[search,setSearch]=useSearchParams();const restored=readReportState(search);const[draft,setDraft]=useState<Filters>(restored.filters);const[applied,setApplied]=useState<Filters|undefined>(restored.run?restored.filters:undefined);const[page,setPageState]=useState(restored.page);const[sort,setSortState]=useState(restored.sort);const[direction,setDirectionState]=useState(restored.direction);const pageSize=restored.pageSize;
  const persist=(values:Filters,nextPage=page,nextSort=sort,nextDirection=direction)=>setSearch(writeReportState(values,nextPage,pageSize,nextSort,nextDirection));
  const setPage=(value:number)=>{setPageState(value);if(applied)persist(applied,value)};const updateSort=(column:string)=>{const next=sort===column&&direction==='asc'?'desc':'asc';setSortState(column);setDirectionState(next);if(applied)persist(applied,page,column,next)};
  const optionsQuery=useQuery({queryKey:['report-filter-options'],queryFn:()=>api<FilterOptions>('/reports/filter-options')});const options=optionsQuery.data;const params=new URLSearchParams({...applied,page:String(page),page_size:String(pageSize),...(sort&&{sort,direction})});const report=useQuery({queryKey:['operational-report',kind,applied,page,pageSize,sort,direction],queryFn:()=>api<{items:Record<string,unknown>[];total:number}>(`/reports/${kind}?${params}`),enabled:!!applied});const columns=report.data?.items[0]?Object.keys(report.data.items[0]).filter(key=>!['task_id','case_id','can_decide'].includes(key)):[];
  const select=(field:{key:string;label:string},rows:Option[])=>{const value=draft[field.key]||'';return <TextField select size="small" key={field.key} label={field.label} value={value} onChange={e=>setDraft({...draft,[field.key]:e.target.value})}><MenuItem value="">הכול</MenuItem>{rows.map(row=><MenuItem key={row.id} value={row.id}>{row.label}</MenuItem>)}</TextField>};
  function input(field:{key:string;label:string;type?:string}){if(field.type==='environment')return select(field,options?.environments||[]);if(field.type==='request_type')return select(field,(options?.request_types||[]).filter(row=>!draft.environment_id||row.environment_id===draft.environment_id));if(field.type==='user')return select(field,options?.users||[]);if(field.type==='group')return select(field,options?.groups||[]);if(field.type==='approval_step')return select(field,(options?.approval_steps||[]).map(value=>({id:value,label:value})));if(field.type==='department'||field.type==='job_title')return select(field,((field.type==='department'?options?.departments:options?.job_titles)||[]).map(value=>({id:value,label:value})));if(field.type==='approval_status')return select(field,options?.approval_statuses||[]);return <TextField size="small" key={field.key} type={field.type||'text'} label={field.label} value={draft[field.key]||''} onChange={e=>setDraft({...draft,[field.key]:e.target.value})} slotProps={field.type?{inputLabel:{shrink:true}}:undefined}/>}
  async function decide(row:Record<string,unknown>,decision:'approved'|'rejected'){const comment=decision==='rejected'?window.prompt('יש להזין סיבת דחייה')?.trim():undefined;if(decision==='rejected'&&!comment)return;await api(`/approval-tasks/${row.task_id}/decision`,{method:'POST',body:JSON.stringify({decision,comment})});await client.invalidateQueries({queryKey:['operational-report','approvals']})}
  const action=(row:Record<string,unknown>)=>kind==='approvals'&&Boolean(row.can_decide)?<Stack direction="row"><Button onClick={()=>decide(row,'approved')}>אישור</Button><Button color="error" onClick={()=>decide(row,'rejected')}>דחייה</Button></Stack>:null;
  const openCase=(row:Record<string,unknown>)=>{if(row.case_id)navigateToCase(navigate,location,String(row.case_id),'חזרה לדוח')};
  const primary=fields[kind].slice(0,5).map(input),advanced=fields[kind].slice(5).map(input);
  return <Container maxWidth="xl"><Stack spacing={2}><Typography variant="h4" fontWeight={900}>{titles[kind]}</Typography>{optionsQuery.isError&&<Alert severity="error">לא ניתן לטעון ערכים למסנני הדוח</Alert>}<CompactFilterPanel primary={primary} advanced={advanced.length?advanced:undefined} activeCount={Object.values(draft).filter(Boolean).length} onReset={()=>{setDraft({});setApplied(undefined);setPageState(1);setSearch({})}} actions={<Button size="small" variant="contained" onClick={()=>{const next={...draft};setApplied(next);setPageState(1);persist(next,1)}}>הרצת דוח</Button>}/>{applied&&<Typography>{report.data?.total||0} תוצאות</Typography>}
    {report.data&&<Paper variant="outlined" sx={{display:{xs:'none',md:'block'}}}><Table><TableHead><TableRow>{columns.map(column=><TableCell key={column}><Button onClick={()=>updateSort(column)}>{labels[column]||column}</Button></TableCell>)}{kind==='approvals'&&<TableCell>פעולות</TableCell>}</TableRow></TableHead><TableBody>{report.data.items.map((row,index)=><TableRow hover key={String(row.task_id||index)} onClick={()=>openCase(row)} sx={{cursor:row.case_id?'pointer':'default'}}>{columns.map(column=><TableCell key={column}>{column==='case_number'?displayCaseNumber(String(row[column]||'')):column==='status'?statusHe[String(row[column])]||String(row[column]||''):String(row[column]||'')}</TableCell>)}{kind==='approvals'&&<TableCell onClick={event=>event.stopPropagation()}>{action(row)}</TableCell>}</TableRow>)}</TableBody></Table></Paper>}
    <Stack spacing={1.25} sx={{display:{md:'none'}}}>{report.data?.items.map((row,index)=><Card variant="outlined" key={String(row.task_id||index)}><CardActionArea disabled={!row.case_id} onClick={()=>openCase(row)}><CardContent><Typography color="primary" fontWeight={850}>{kind==='approvals'?displayCaseNumber(String(row.case_number||'')):String(row.user||row.created_at||'')}</Typography><Typography variant="h6">{String(row.subject||row.email||row.action||'')}</Typography>{kind==='approvals'&&<Typography>{String(row.status||'')} · {String(row.approver||'')} · {String(row.requested_at||'')}</Typography>}{kind==='users'&&<Typography>{String(row.department||'')} · {String(row.job_title||'')} · {String(row.status||row.source||'')}</Typography>}{kind==='audit'&&<Typography>{String(row.user||'')} · {String(row.entity||'')} · {String(row.entity_id||'')}</Typography>}</CardContent></CardActionArea>{action(row)&&<Box px={2} pb={2}>{action(row)}</Box>}</Card>)}</Stack>
    {report.data&&<Stack direction="row" justifyContent="space-between"><Button disabled={page===1} onClick={()=>setPage(page-1)}>הקודם</Button><Typography>עמוד {page}</Typography><Button disabled={page*25>=report.data.total} onClick={()=>setPage(page+1)}>הבא</Button></Stack>}
  </Stack></Container>;
}
