import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Button, Container, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { api } from '../../api/client';
import type { Environment, Group, User } from '../../types';

type Kind='approvals'|'users'|'audit';type Filters=Record<string,string>;
const titles={approvals:'דוח אישורים',users:'דוח משתמשים והרשאות',audit:'דוח Audit'};
const statusHe:Record<string,string>={pending:'ממתין לאישור',approved:'אושר',rejected:'נדחה',cancelled:'בוטל'};
const labels:Record<string,string>={case_number:'מספר קריאה',subject:'נושא',environment:'סביבה',request_type:'סוג קריאה',approver:'מאשר',step:'שלב',status:'סטטוס',requested_at:'מועד בקשה',decided_at:'מועד החלטה',user:'משתמש',email:'דוא״ל',username:'שם משתמש',source:'מקור',department:'מחלקה',job_title:'תפקיד ארגוני',groups:'קבוצות',environments:'סביבות',permissions:'הרשאות',action:'פעולה',entity:'סוג ישות',entity_id:'מזהה ישות',created_at:'מועד'};
const fields:Record<Kind,{key:string;label:string;type?:string}[]>={
  approvals:[{key:'case_number',label:'מספר קריאה'},{key:'subject',label:'נושא'},{key:'environment_id',label:'סביבה',type:'environment'},{key:'request_type_id',label:'סוג קריאה'},{key:'approver_id',label:'מאשר',type:'user'},{key:'status',label:'סטטוס',type:'approval_status'},{key:'step',label:'שלב'},{key:'requested_from',label:'תאריך בקשה מ',type:'datetime-local'},{key:'requested_to',label:'תאריך בקשה עד',type:'datetime-local'},{key:'decided_from',label:'תאריך החלטה מ',type:'datetime-local'},{key:'decided_to',label:'תאריך החלטה עד',type:'datetime-local'}],
  users:[{key:'name',label:'שם'},{key:'email',label:'Email'},{key:'username',label:'Username'},{key:'status',label:'סטטוס',type:'user_status'},{key:'source',label:'מקור',type:'user_source'},{key:'department',label:'מחלקה',type:'department'},{key:'job_title',label:'תפקיד ארגוני',type:'job_title'},{key:'group_ids',label:'קבוצה',type:'group'},{key:'environment_id',label:'סביבה',type:'environment'}],
  audit:[{key:'user_id',label:'משתמש',type:'user'},{key:'effective_user_id',label:'משתמש מתחזה',type:'user'},{key:'action',label:'פעולה'},{key:'entity_type',label:'סוג ישות'},{key:'entity_id',label:'Entity ID'},{key:'environment_id',label:'סביבה',type:'environment'},{key:'date_from',label:'מתאריך',type:'datetime-local'},{key:'date_to',label:'עד תאריך',type:'datetime-local'},{key:'search',label:'חיפוש טקסט'}],
};

export function OperationalReportPage({kind}:{kind:Kind}){const client=useQueryClient();const[draft,setDraft]=useState<Filters>({});const[applied,setApplied]=useState<Filters>();const[page,setPage]=useState(1);const[sort,setSort]=useState('');const[direction,setDirection]=useState('asc');
  const{data:environments=[]}=useQuery({queryKey:['environments'],queryFn:()=>api<Environment[]>('/environments')});const{data:users=[]}=useQuery({queryKey:['users'],queryFn:()=>api<User[]>('/users?active_only=false')});const{data:groups=[]}=useQuery({queryKey:['groups'],queryFn:()=>api<Group[]>('/groups')});const{data:assignmentOptions}=useQuery({queryKey:['environment-assignment-options'],queryFn:()=>api<{departments:string[];job_titles:string[]}>('/environment-assignment-options')});
  const params=new URLSearchParams({...applied,page:String(page),page_size:'25',...(sort&&{sort,direction})});const report=useQuery({queryKey:['operational-report',kind,applied,page,sort,direction],queryFn:()=>api<{items:Record<string,unknown>[];total:number;page_size:number}>(`/reports/${kind}?${params}`),enabled:!!applied});const columns=report.data?.items[0]?Object.keys(report.data.items[0]).filter(key=>!['task_id','can_decide'].includes(key)):[];
  function input(field:{key:string;label:string;type?:string}){const value=draft[field.key]||'';const change=(next:string)=>setDraft({...draft,[field.key]:next});if(field.type==='environment')return <TextField select key={field.key} label={field.label} value={value} onChange={e=>change(e.target.value)}><MenuItem value="">הכול</MenuItem>{environments.map(row=><MenuItem key={row.id} value={row.id}>{row.name_he}</MenuItem>)}</TextField>;if(field.type==='user')return <TextField select key={field.key} label={field.label} value={value} onChange={e=>change(e.target.value)}><MenuItem value="">הכול</MenuItem>{users.map(row=><MenuItem key={row.id} value={row.id}>{row.display_name} · {row.email}</MenuItem>)}</TextField>;if(field.type==='group')return <TextField select key={field.key} label={field.label} value={value} onChange={e=>change(e.target.value)}><MenuItem value="">הכול</MenuItem>{groups.map(row=><MenuItem key={row.id} value={row.id}>{row.name}</MenuItem>)}</TextField>;if(field.type==='department'||field.type==='job_title'){const options=field.type==='department'?assignmentOptions?.departments:assignmentOptions?.job_titles;return <TextField select key={field.key} label={field.label} value={value} onChange={e=>change(e.target.value)}><MenuItem value="">הכול</MenuItem>{(options??[]).map(option=><MenuItem key={option} value={option}>{option}</MenuItem>)}</TextField>}if(field.type==='user_status')return <TextField select key={field.key} label={field.label} value={value} onChange={e=>change(e.target.value)}><MenuItem value="">הכול</MenuItem><MenuItem value="active">פעיל</MenuItem><MenuItem value="inactive">לא פעיל</MenuItem><MenuItem value="archived">בארכיון</MenuItem></TextField>;if(field.type==='user_source')return <TextField select key={field.key} label={field.label} value={value} onChange={e=>change(e.target.value)}><MenuItem value="">הכול</MenuItem><MenuItem value="manual">ידני</MenuItem><MenuItem value="entra">Microsoft Entra</MenuItem><MenuItem value="excel">Excel</MenuItem><MenuItem value="fake">ספק בדיקה</MenuItem></TextField>;if(field.type==='approval_status')return <TextField select key={field.key} label={field.label} value={value} onChange={e=>change(e.target.value)}><MenuItem value="">הכול</MenuItem>{Object.entries(statusHe).map(([key,label])=><MenuItem key={key} value={key}>{label}</MenuItem>)}</TextField>;return <TextField key={field.key} type={field.type||'text'} label={field.label} value={value} onChange={e=>change(e.target.value)} slotProps={field.type?{inputLabel:{shrink:true}}:undefined}/>}
  async function decide(row:Record<string,unknown>,decision:'approved'|'rejected'){const comment=decision==='rejected'?window.prompt('יש להזין סיבת דחייה')?.trim():undefined;if(decision==='rejected'&&!comment)return;await api(`/approval-tasks/${row.task_id}/decision`,{method:'POST',body:JSON.stringify({decision,comment})});await client.invalidateQueries({queryKey:['operational-report','approvals']})}
  return <Container maxWidth="xl"><Stack spacing={2}><Typography variant="h4" fontWeight={900}>{titles[kind]}</Typography><Paper variant="outlined" sx={{p:2}}><Stack direction={{xs:'column',md:'row'}} flexWrap="wrap" gap={1.5}>{fields[kind].map(input)}</Stack><Stack direction="row" gap={1} mt={2}><Button variant="contained" onClick={()=>{setApplied({...draft});setPage(1)}}>הרצת דוח</Button><Button onClick={()=>{setDraft({});setApplied({});setPage(1)}}>איפוס</Button></Stack></Paper>{report.isError&&<Alert severity="error">{(report.error as Error).message}</Alert>}{applied&&<Typography>{report.data?.total??0} תוצאות</Typography>}{report.data&&<Paper variant="outlined" sx={{overflowX:'auto'}}><Table><TableHead><TableRow>{columns.map(column=><TableCell key={column}><Button onClick={()=>{setSort(column);setDirection(sort===column&&direction==='asc'?'desc':'asc')}}>{labels[column]||column}</Button></TableCell>)}{kind==='approvals'&&<TableCell>פעולות</TableCell>}</TableRow></TableHead><TableBody>{report.data.items.map((row,index)=><TableRow key={index}>{columns.map(column=><TableCell key={column}>{column==='status'?statusHe[String(row[column])]||String(row[column]??''):String(row[column]??'')}</TableCell>)}{kind==='approvals'&&<TableCell>{Boolean(row.can_decide)&&<Stack direction="row"><Button onClick={()=>decide(row,'approved')}>אישור</Button><Button color="error" onClick={()=>decide(row,'rejected')}>דחייה</Button></Stack>}</TableCell>}</TableRow>)}</TableBody></Table><Stack direction="row" justifyContent="space-between" p={2}><Button disabled={page===1} onClick={()=>setPage(page-1)}>הקודם</Button><Typography>עמוד {page}</Typography><Button disabled={page*25>=(report.data.total||0)} onClick={()=>setPage(page+1)}>הבא</Button></Stack></Paper>}</Stack></Container>}
