import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Box, Button, Container, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { api } from '../../api/client';
import { approvalStatusHe as statusHe, reportFields as fields, type ReportKind as Kind } from './reportConfig';

type Filters=Record<string,string>;
type Option={id:string;label:string};
type FilterOptions={environments:Option[];request_types:(Option&{environment_id:string})[];users:Option[];groups:Option[];departments:string[];job_titles:string[];approval_statuses:Option[];approval_steps:string[]};
const titles={approvals:'דוח אישורים',users:'דוח משתמשים והרשאות',audit:'דוח Audit'};
const labels:Record<string,string>={case_number:'מספר קריאה',subject:'נושא',environment:'סביבה',request_type:'סוג קריאה',approver:'מאשר',step:'שלב',status:'סטטוס',requested_at:'מועד בקשה',decided_at:'מועד החלטה',user:'משתמש',email:'דוא״ל',username:'שם משתמש',source:'מקור',department:'מחלקה',job_title:'תפקיד ארגוני',groups:'קבוצות',environments:'סביבות',permissions:'הרשאות',action:'פעולה',entity:'סוג ישות',entity_id:'מזהה ישות',created_at:'מועד'};

export function OperationalReportPage({kind}:{kind:Kind}){const client=useQueryClient();const[draft,setDraft]=useState<Filters>({});const[applied,setApplied]=useState<Filters>();const[page,setPage]=useState(1);const[sort,setSort]=useState('');const[direction,setDirection]=useState('asc');
  const optionsQuery=useQuery({queryKey:['report-filter-options'],queryFn:()=>api<FilterOptions>('/reports/filter-options')});const options=optionsQuery.data;
  const params=new URLSearchParams({...applied,page:String(page),page_size:'25',...(sort&&{sort,direction})});const report=useQuery({queryKey:['operational-report',kind,applied,page,sort,direction],queryFn:()=>api<{items:Record<string,unknown>[];total:number;page_size:number}>(`/reports/${kind}?${params}`),enabled:!!applied});const columns=report.data?.items[0]?Object.keys(report.data.items[0]).filter(key=>!['task_id','can_decide'].includes(key)):[];
  function input(field:{key:string;label:string;type?:string}){const value=draft[field.key]||'';const change=(next:string)=>setDraft({...draft,[field.key]:next});const select=(rows:Option[])=><TextField select fullWidth key={field.key} label={field.label} value={value} onChange={e=>change(e.target.value)}><MenuItem value="">הכול</MenuItem>{rows.map(row=><MenuItem key={row.id} value={row.id}>{row.label}</MenuItem>)}</TextField>;if(field.type==='environment')return select(options?.environments??[]);if(field.type==='request_type')return select((options?.request_types??[]).filter(row=>!draft.environment_id||row.environment_id===draft.environment_id));if(field.type==='user')return select(options?.users??[]);if(field.type==='group')return select(options?.groups??[]);if(field.type==='approval_step')return select((options?.approval_steps??[]).map(value=>({id:value,label:value})));if(field.type==='department'||field.type==='job_title'){const rows=field.type==='department'?options?.departments:options?.job_titles;return select((rows??[]).map(option=>({id:option,label:option})))}if(field.type==='user_status')return select([{id:'active',label:'פעיל'},{id:'inactive',label:'לא פעיל'},{id:'archived',label:'בארכיון'}]);if(field.type==='user_source')return select([{id:'manual',label:'ידני'},{id:'entra',label:'Microsoft Entra'},{id:'excel',label:'Excel'},{id:'fake',label:'ספק בדיקה'}]);if(field.type==='approval_status')return select(options?.approval_statuses??[]);return <TextField fullWidth key={field.key} type={field.type||'text'} label={field.label} value={value} onChange={e=>change(e.target.value)} slotProps={field.type?{inputLabel:{shrink:true}}:undefined}/>}
  async function decide(row:Record<string,unknown>,decision:'approved'|'rejected'){const comment=decision==='rejected'?window.prompt('יש להזין סיבת דחייה')?.trim():undefined;if(decision==='rejected'&&!comment)return;await api(`/approval-tasks/${row.task_id}/decision`,{method:'POST',body:JSON.stringify({decision,comment})});await Promise.all([client.invalidateQueries({queryKey:['operational-report','approvals']}),client.invalidateQueries({queryKey:['pending-approvals']}),client.invalidateQueries({queryKey:['case-approvals']})])}
  return <Container maxWidth="xl"><Stack spacing={2}><Typography variant="h4" fontWeight={900}>{titles[kind]}</Typography>{optionsQuery.isError&&<Alert severity="error">לא ניתן לטעון ערכים למסנני הדוח</Alert>}<Paper variant="outlined" sx={{p:2}}><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(3,minmax(220px,1fr))'},gap:2}}>{fields[kind].map(input)}</Box><Stack direction="row" gap={1} mt={2}><Button variant="contained" onClick={()=>{setApplied({...draft});setPage(1)}}>הרצת דוח</Button><Button onClick={()=>{setDraft({});setApplied({});setPage(1)}}>איפוס</Button></Stack></Paper>{report.isError&&<Alert severity="error">{(report.error as Error).message}</Alert>}{applied&&<Typography>{report.data?.total??0} תוצאות</Typography>}{report.data&&<Paper variant="outlined" sx={{overflowX:'auto'}}><Table><TableHead><TableRow>{columns.map(column=><TableCell key={column}><Button onClick={()=>{setSort(column);setDirection(sort===column&&direction==='asc'?'desc':'asc')}}>{labels[column]||column}</Button></TableCell>)}{kind==='approvals'&&<TableCell>פעולות</TableCell>}</TableRow></TableHead><TableBody>{report.data.items.map((row,index)=><TableRow key={String(row.task_id??index)}>{columns.map(column=><TableCell key={column}>{column==='status'?statusHe[String(row[column])]||String(row[column]??''):String(row[column]??'')}</TableCell>)}{kind==='approvals'&&<TableCell>{Boolean(row.can_decide)&&<Stack direction="row"><Button onClick={()=>decide(row,'approved')}>אישור</Button><Button color="error" onClick={()=>decide(row,'rejected')}>דחייה</Button></Stack>}</TableCell>}</TableRow>)}</TableBody></Table><Stack direction="row" justifyContent="space-between" p={2}><Button disabled={page===1} onClick={()=>setPage(page-1)}>הקודם</Button><Typography>עמוד {page}</Typography><Button disabled={page*25>=(report.data.total||0)} onClick={()=>setPage(page+1)}>הבא</Button></Stack></Paper>}</Stack></Container>}
