import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { DndContext, KeyboardSensor, PointerSensor, TouchSensor, closestCenter, useSensor, useSensors, type DragEndEvent } from '@dnd-kit/core';
import { SortableContext, arrayMove, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { Alert, Button, Container, FormControlLabel, MenuItem, Paper, Stack, Switch, Tab, Tabs, TextField, Typography } from '@mui/material';
import { api } from '../../api/client';

type Kind='statuses'|'priorities'|'sub-priorities';
type Value={id:string;label_he:string;label_en?:string;is_active:boolean;is_initial?:boolean;is_final?:boolean;semantic_category?:string;color?:string;sort_order:number};
const kinds:Kind[]=['statuses','priorities','sub-priorities'];
const titles:Record<Kind,string>={statuses:'סטטוסים',priorities:'עדיפויות','sub-priorities':'תתי־עדיפויות'};
const blank={label_he:'',label_en:'',is_active:true,is_initial:false,is_final:false,semantic_category:'open',color:'#64748b'};

function SortableValue({row,children}:{row:Value;children:React.ReactNode}){const{attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:row.id});return <Paper ref={setNodeRef} variant="outlined" sx={{p:2,borderRight:`6px solid ${row.color||'#64748b'}`,transform:CSS.Transform.toString(transform),transition,opacity:isDragging?.65:1}}><Stack direction={{xs:'column',md:'row'}} gap={1.5} alignItems={{md:'center'}}><Button {...attributes} {...listeners} aria-label={`גרירת ${row.label_he}`} sx={{minWidth:38,cursor:'grab'}}>☰</Button>{children}</Stack></Paper>}

export function CaseValuesPage(){
  const client=useQueryClient();const[tab,setTab]=useState(0);const[form,setForm]=useState(blank);const[error,setError]=useState('');
  const sensors=useSensors(useSensor(PointerSensor),useSensor(TouchSensor),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));
  const kind=kinds[tab];const query=useQuery({queryKey:['global-case-values',kind],queryFn:()=>api<Value[]>(`/global-case-values/${kind}?include_inactive=true`)});
  async function create(){setError('');try{await api(`/global-case-values/${kind}`,{method:'POST',body:JSON.stringify(form)});setForm(blank);await client.invalidateQueries({queryKey:['global-case-values']})}catch(e){setError((e as Error).message)}}
  async function update(row:Value,patch:Partial<Value>){setError('');try{await api(`/global-case-values/${kind}/${row.id}`,{method:'PATCH',body:JSON.stringify({...row,...patch})});await client.invalidateQueries({queryKey:['global-case-values']})}catch(e){setError((e as Error).message)}}
  async function initial(row:Value){await api(`/global-case-values/statuses/${row.id}/set-initial`,{method:'POST'});await client.invalidateQueries({queryKey:['global-case-values']})}
  async function reorder(event:DragEndEvent){if(!event.over||event.active.id===event.over.id)return;const rows=query.data??[];const next=arrayMove(rows,rows.findIndex(row=>row.id===event.active.id),rows.findIndex(row=>row.id===event.over?.id));try{await api(`/global-case-values/${kind}/order`,{method:'PUT',body:JSON.stringify(next.map(row=>row.id))});await client.invalidateQueries({queryKey:['global-case-values']})}catch(e){setError((e as Error).message)}}
  return <Container maxWidth="lg"><Stack spacing={3}><header><Typography variant="h4" fontWeight={900}>הגדרות שדות קריאה</Typography><Typography color="text.secondary">מקור אמת גלובלי לכל הסביבות, הקריאות והדוחות</Typography></header><Tabs value={tab} onChange={(_,value)=>{setTab(value);setForm(blank)}}>{kinds.map(value=><Tab key={value} label={titles[value]}/>)}</Tabs>{error&&<Alert severity="error">{error}</Alert>}{query.isLoading&&<Alert severity="info">טוען ערכים…</Alert>}<DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={reorder}><SortableContext items={(query.data??[]).map(row=>row.id)} strategy={verticalListSortingStrategy}><Stack spacing={1.5}>{(query.data??[]).map(row=><SortableValue key={row.id} row={row}><TextField size="small" label="שם בעברית" value={row.label_he} onChange={event=>update(row,{label_he:event.target.value})}/><TextField size="small" label="שם באנגלית" value={row.label_en||''} onChange={event=>update(row,{label_en:event.target.value})}/>{kind==='statuses'&&<TextField size="small" select label="קטגוריה סמנטית" value={row.semantic_category||'open'} onChange={event=>update(row,{semantic_category:event.target.value})}>{['open','in_progress','waiting','resolved','closed'].map(value=><MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField>}<FormControlLabel control={<Switch checked={row.is_active} onChange={event=>update(row,{is_active:event.target.checked})}/>} label="פעיל"/>{kind==='statuses'&&!row.is_initial&&<Button onClick={()=>initial(row)}>הגדרה כהתחלתי</Button>}{row.is_initial&&<Typography color="primary" fontWeight={800}>● התחלתי</Typography>}</SortableValue>)}</Stack></SortableContext></DndContext><Paper variant="outlined" sx={{p:2}}><Typography variant="h6" mb={2}>הוספת ערך</Typography><Stack direction={{xs:'column',md:'row'}} gap={1.5}><TextField label="שם בעברית" value={form.label_he} onChange={event=>setForm({...form,label_he:event.target.value})}/><TextField label="שם באנגלית (רשות)" value={form.label_en} onChange={event=>setForm({...form,label_en:event.target.value})}/>{kind==='statuses'&&<TextField select label="קטגוריה סמנטית" value={form.semantic_category} onChange={event=>setForm({...form,semantic_category:event.target.value})}>{['open','in_progress','waiting','resolved','closed'].map(value=><MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField>}<Button variant="contained" disabled={!form.label_he.trim()} onClick={create}>הוספה</Button></Stack></Paper></Stack></Container>
}
