import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { SortableFieldRow } from './global-fields/SortableFieldRow';
import { DndContext, closestCenter, type DragEndEvent } from '@dnd-kit/core';
import { SortableContext, arrayMove, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { Add, DeleteOutline, EditOutlined } from '@mui/icons-material';
import { Alert, Box, Button, Container, Menu, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../api/client';
import { ScreenHeader } from '../../components/ScreenHeader';
import { GlobalFieldDialog } from './global-fields/GlobalFieldDialog';
import { GlobalOptionsDialog } from './global-fields/GlobalOptionsDialog';
import { fieldTypes, type GlobalField, type GlobalOption } from './global-fields/types';

export function GlobalFieldsPage(){
  const { t } = useTranslation();
  const qc=useQueryClient(); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [search,setSearch]=useState(''); const [type,setType]=useState('all'); const [status,setStatus]=useState('all');
  const [editing,setEditing]=useState<GlobalField>(); const [createOpen,setCreateOpen]=useState(false); const [optionsField,setOptionsField]=useState<GlobalField>(); const [menu,setMenu]=useState<{anchor:HTMLElement;row:GlobalField}>();
  const query=useQuery({queryKey:['global-case-fields'],queryFn:()=>api<GlobalField[]>('/global-case-fields?include_inactive=true')});
  const visible=useMemo(()=>(query.data||[]).filter(row=>(!search||`${row.label_he} ${row.key} ${row.semantic_binding||''}`.toLowerCase().includes(search.toLowerCase()))&&(type==='all'||row.field_type===type)&&(status==='all'||row.is_active===(status==='active'))),[query.data,search,type,status]);
  const refresh=()=>qc.invalidateQueries({queryKey:['global-case-fields']});
  async function guarded(action:()=>Promise<void>){setError('');try{await action();await refresh()}catch(caught){setError((caught as Error).message)}}
  const payload=(field:GlobalField,patch:Partial<GlobalField>)=>({label_he:field.label_he,label_en:field.label_en,field_type:field.field_type,is_required:field.is_required,is_active:field.is_active,track_history:field.track_history,semantic_binding:field.semantic_binding||null,...patch});
  async function save(value:{label_he:string;label_en:string;field_type:string;is_required:boolean;is_active:boolean;track_history:boolean;semantic_binding:string|null}){await guarded(async()=>{await api(editing?`/global-case-fields/${editing.id}`:'/global-case-fields',{method:editing?'PATCH':'POST',body:JSON.stringify(value)});setEditing(undefined);setCreateOpen(false)})}
  async function remove(row:GlobalField){if(!confirm(row.semantic_binding?'השדה מחובר למשמעות עסקית. מחיקה בטוחה עשויה להשבית אותו. להמשיך?':'למחוק את השדה?'))return;await guarded(async()=>{const result=await api<{action:string}>(`/global-case-fields/${row.id}`,{method:'DELETE'});setNotice(result.action==='deactivated'?'השדה נמצא בשימוש ולכן הושבת והמידע נשמר':'השדה נמחק')})}
  async function reorder(event:DragEndEvent){if(!event.over||event.active.id===event.over.id)return;const rows=query.data||[];const next=arrayMove(rows,rows.findIndex(x=>x.id===event.active.id),rows.findIndex(x=>x.id===event.over?.id));await guarded(()=>api('/global-case-fields/order',{method:'PUT',body:JSON.stringify(next.map(x=>x.id))}).then(()=>undefined))}
  const optionAction=(action:()=>Promise<unknown>)=>guarded(async()=>{await action();const fresh=await query.refetch();setOptionsField(fresh.data?.find(row=>row.id===optionsField?.id))});
  return <Box className="admin-page"><Container maxWidth="xl"><Stack spacing={2.5}><ScreenHeader title="שדות גלובליים" subtitle="השדות נשמרים כקונפיגורציה ומוצגים בכל הסביבות כברירת מחדל" action={<Button variant="contained" size="large" startIcon={<Add/>} onClick={()=>setCreateOpen(true)}>הוסף שדה גלובלי</Button>}/>{error&&<Alert severity="error">{error}</Alert>}{notice&&<Alert severity="success" onClose={()=>setNotice('')}>{notice}</Alert>}
    <Paper className="filter-panel" variant="outlined"><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'2fr 1fr 1fr'},gap:1.5}}><TextField label="חיפוש חופשי" value={search} onChange={e=>setSearch(e.target.value)}/><TextField select label="סוג שדה" value={type} onChange={e=>setType(e.target.value)}><MenuItem value="all">כל הסוגים</MenuItem>{fieldTypes.map(([key,label])=><MenuItem key={key} value={key}>{label}</MenuItem>)}</TextField><TextField select label="סטטוס" value={status} onChange={e=>setStatus(e.target.value)}><MenuItem value="all">הכול</MenuItem><MenuItem value="active">פעיל</MenuItem><MenuItem value="inactive">לא פעיל</MenuItem></TextField></Box></Paper>
    <Paper className="data-table responsive-record-table" variant="outlined"><DndContext collisionDetection={closestCenter} onDragEnd={reorder}><SortableContext items={(query.data||[]).map(x=>x.id)} strategy={verticalListSortingStrategy}><Table><TableHead><TableRow><TableCell/><TableCell>{t('globalFieldsList.name')}</TableCell><TableCell>{t('globalFieldsList.purpose')}</TableCell><TableCell>{t('globalFieldsList.type')}</TableCell><TableCell>{t('globalFieldsList.values')}</TableCell><TableCell>{t('globalFieldsList.status')}</TableCell><TableCell>{t('globalFieldsList.required')}</TableCell><TableCell>{t('globalFieldsList.create')}</TableCell><TableCell>{t('globalFieldsList.edit')}</TableCell><TableCell>{t('globalFieldsList.order')}</TableCell><TableCell>{t('globalFieldsList.actions')}</TableCell></TableRow></TableHead><TableBody>{visible.map(row=><SortableFieldRow key={row.id} row={row} onManageOptions={setOptionsField} onMenu={(anchor,item)=>setMenu({anchor,row:item})}/>)}</TableBody></Table></SortableContext></DndContext>{!visible.length&&<Typography textAlign="center" color="text.secondary" py={6}>לא נמצאו שדות</Typography>}</Paper>
    <Menu anchorEl={menu?.anchor} open={!!menu} onClose={()=>setMenu(undefined)}><MenuItem onClick={()=>{setEditing(menu?.row);setMenu(undefined)}}><EditOutlined fontSize="small" sx={{ml:1}}/>עריכה</MenuItem><MenuItem onClick={()=>menu&&guarded(()=>api(`/global-case-fields/${menu.row.id}`,{method:'PATCH',body:JSON.stringify(payload(menu.row,{is_active:!menu.row.is_active}))}).then(()=>{setMenu(undefined)}))}>{menu?.row.is_active?'השבתה':'הפעלה'}</MenuItem><MenuItem sx={{color:'error.main'}} onClick={()=>{if(menu)void remove(menu.row);setMenu(undefined)}}><DeleteOutline fontSize="small" sx={{ml:1}}/>מחיקה</MenuItem></Menu>
    <GlobalFieldDialog open={createOpen||!!editing} field={editing} onClose={()=>{setCreateOpen(false);setEditing(undefined)}} onSave={save}/><GlobalOptionsDialog field={optionsField} onClose={()=>setOptionsField(undefined)} onAdd={(labelHe,labelEn)=>optionAction(()=>api(`/global-case-fields/${optionsField!.id}/options`,{method:'POST',body:JSON.stringify({label_he:labelHe,label_en:labelEn,is_active:true})}))} onUpdate={(option,labelHe,labelEn,active)=>void optionAction(()=>api(`/global-case-fields/${optionsField!.id}/options/${option.id}`,{method:'PATCH',body:JSON.stringify({label_he:labelHe,label_en:labelEn,is_active:active})}))} onRemove={(option:GlobalOption)=>void optionAction(()=>api(`/global-case-fields/${optionsField!.id}/options/${option.id}`,{method:'DELETE'}))} onReorder={ids=>void optionAction(()=>api(`/global-case-fields/${optionsField!.id}/options/order`,{method:'PUT',body:JSON.stringify(ids)}))}/>
  </Stack></Container></Box>;
}
