import { Search } from '@mui/icons-material';
import { Checkbox, FormControlLabel, InputAdornment, MenuItem, TextField, Tooltip } from '@mui/material';
import { CompactFilterPanel } from '../../../components/filters/CompactFilterPanel';
import type { Environment, RequestType, User } from '../../../types';
import type { ReportFilters } from './reportFilters';
import { useTranslation } from 'react-i18next';
import { localized } from '../../../i18n';
import { emptyFilters } from './reportFilters';

export function CaseReportFilters({ value, onChange, environments, types, users, statuses }: { value: ReportFilters; onChange: (value: ReportFilters) => void; environments: Environment[]; types: RequestType[]; users: User[]; statuses: {id:string;label_he:string;environment:string}[] }) {
  const {t,i18n}=useTranslation();
  const set = (key: keyof ReportFilters, next: string) => onChange({ ...value, [key]: next });
  const primary=<><TextField label={t('reports.search')} value={value.search} onChange={(e) => set('search', e.target.value)} slotProps={{input:{startAdornment:<InputAdornment position="start"><Search/></InputAdornment>}}}/><TextField select label={t('cases.environment')} value={value.environment_id} onChange={(e) => onChange({...value,environment_id:e.target.value,request_type_id:'',workflow_status_id:''})}><MenuItem value="">{t('reports.allEnvironments')}</MenuItem>{environments.map((x) => <MenuItem key={x.id} value={x.id}>{x.localized_name || localized(x.name_he,x.name_en,i18n.language)}</MenuItem>)}</TextField><TextField select label={t('cases.requestType')} value={value.request_type_id} onChange={(e) => set('request_type_id', e.target.value)}><MenuItem value="">{t('reports.allTypes')}</MenuItem>{types.map((x) => <MenuItem key={x.id} value={x.id}>{x.localized_name || localized(x.name_he,x.name_en,i18n.language)}</MenuItem>)}</TextField><TextField select label={t('dashboard.status')} value={value.workflow_status_id} onChange={(e) => set('workflow_status_id', e.target.value)}><MenuItem value="">{t('reports.allStatuses')}</MenuItem>{statuses.map((x) => <MenuItem key={x.id} value={x.id}>{x.label_he}{value.environment_id?'':` · ${x.environment}`}</MenuItem>)}</TextField></>;
  const advanced=<><TextField select label={t('reports.creator')} value={value.created_by_id} onChange={(e) => set('created_by_id', e.target.value)}><MenuItem value="">{t('reports.allUsers')}</MenuItem>{users.map((x) => <MenuItem key={x.id} value={x.id}>{x.display_name}</MenuItem>)}</TextField><TextField select label={t('reports.assignee')} value={value.assignee_id} onChange={(e) => set('assignee_id', e.target.value)}><MenuItem value="">{t('reports.allAssignees')}</MenuItem>{users.map((x) => <MenuItem key={x.id} value={x.id}>{x.display_name}</MenuItem>)}</TextField>{(['created_from','created_to','updated_from','updated_to'] as const).map((key)=><TextField key={key} type="datetime-local" label={key==='created_from'?'תאריך פתיחה מ-':key==='created_to'?'תאריך פתיחה עד-':key==='updated_from'?t('reports.updatedFrom'):t('reports.updatedTo')} slotProps={{inputLabel:{shrink:true}}} value={value[key]} onChange={(e)=>set(key,e.target.value)}/>)}</>;
  return <CompactFilterPanel primary={primary} advanced={advanced} activeCount={Object.entries(value).filter(([key,next])=>next&&next!==emptyFilters[key]).length} onReset={()=>onChange({...emptyFilters})} actions={<Tooltip title={t('reports.includeParticipantsHelp')}><FormControlLabel control={<Checkbox checked={value.include_participating === 'true'} onChange={(e) => set('include_participating', String(e.target.checked))}/>} label={t('reports.includeParticipants')}/></Tooltip>}/>;
}
