import { Checkbox, FormControlLabel, MenuItem, Paper, Stack, TextField, Tooltip } from '@mui/material';
import type { Environment, RequestType, User } from '../../../types';
import type { ReportFilters } from './reportFilters';
import { useTranslation } from 'react-i18next';
import { localized } from '../../../i18n';

export function CaseReportFilters({ value, onChange, environments, types, users, statuses }: { value: ReportFilters; onChange: (value: ReportFilters) => void; environments: Environment[]; types: RequestType[]; users: User[]; statuses: {id:string;label_he:string;environment:string}[] }) {
  const {t,i18n}=useTranslation();
  const set = (key: keyof ReportFilters, next: string) => onChange({ ...value, [key]: next });
  return <Paper variant="outlined" sx={{ p: { xs: 2, md: 2.5 } }}><Stack spacing={2}>
    <Stack direction={{ xs: 'column', md: 'row' }} spacing={1}><TextField fullWidth label={t('reports.search')} value={value.search} onChange={(e) => set('search', e.target.value)}/><TextField select fullWidth label={t('cases.environment')} value={value.environment_id} onChange={(e) => onChange({...value,environment_id:e.target.value,request_type_id:'',workflow_status_id:''})}><MenuItem value="">{t('reports.allEnvironments')}</MenuItem>{environments.map((x) => <MenuItem key={x.id} value={x.id}>{x.localized_name || localized(x.name_he,x.name_en,i18n.language)}</MenuItem>)}</TextField><TextField select fullWidth label={t('cases.requestType')} value={value.request_type_id} onChange={(e) => set('request_type_id', e.target.value)}><MenuItem value="">{t('reports.allTypes')}</MenuItem>{types.map((x) => <MenuItem key={x.id} value={x.id}>{x.localized_name || localized(x.name_he,x.name_en,i18n.language)}</MenuItem>)}</TextField><TextField select fullWidth label={t('dashboard.status')} value={value.workflow_status_id} onChange={(e) => set('workflow_status_id', e.target.value)}><MenuItem value="">{t('reports.allStatuses')}</MenuItem>{statuses.map((x) => <MenuItem key={x.id} value={x.id}>{x.label_he}{value.environment_id?'':` · ${x.environment}`}</MenuItem>)}</TextField></Stack>
    <Stack direction={{ xs: 'column', md: 'row' }} spacing={1}><TextField select fullWidth label={t('reports.creator')} value={value.created_by_id} onChange={(e) => set('created_by_id', e.target.value)}><MenuItem value="">{t('reports.allUsers')}</MenuItem>{users.map((x) => <MenuItem key={x.id} value={x.id}>{x.display_name}</MenuItem>)}</TextField><TextField select fullWidth label={t('reports.assignee')} value={value.assignee_id} onChange={(e) => set('assignee_id', e.target.value)}><MenuItem value="">{t('reports.allAssignees')}</MenuItem>{users.map((x) => <MenuItem key={x.id} value={x.id}>{x.display_name}</MenuItem>)}</TextField><TextField fullWidth type="datetime-local" label={t('reports.updatedFrom')} slotProps={{ inputLabel: { shrink: true } }} value={value.updated_from} onChange={(e) => set('updated_from', e.target.value)}/><TextField fullWidth type="datetime-local" label={t('reports.updatedTo')} slotProps={{ inputLabel: { shrink: true } }} value={value.updated_to} onChange={(e) => set('updated_to', e.target.value)}/></Stack>
    <Tooltip title={t('reports.includeParticipantsHelp')}><FormControlLabel control={<Checkbox checked={value.include_participating === 'true'} onChange={(e) => set('include_participating', String(e.target.checked))}/>} label={t('reports.includeParticipants')}/></Tooltip>
  </Stack></Paper>;
}
