import { Close } from '@mui/icons-material';
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useMemo, useState } from 'react';
import { api } from '../../api/client';
import type { Case, User } from '../../types';
import type { GlobalField } from '../admin/global-fields/types';

type Action='assign'|'status'|'priority'|'add_participant';type Preview={preview_id:string;eligible:number;skipped:number;items:{case_id:string;case_number:string;eligible:boolean;reason?:string}[]};type Result={succeeded:number;skipped:number;failed:number};
export function BulkActionBar({selectedIds,onClear}:{selectedIds:string[];onClear:()=>void}){
  const client=useQueryClient();const[action,setAction]=useState<Action>('assign');const[target,setTarget]=useState('');const[preview,setPreview]=useState<Preview>();const[result,setResult]=useState<Result>();
  const first=useQuery({queryKey:['bulk-first-case',selectedIds[0]],queryFn:()=>api<Case>(`/cases/${selectedIds[0]}`),enabled:Boolean(selectedIds[0])});
  const users=useQuery({queryKey:['bulk-eligible-users',first.data?.environment_id],queryFn:()=>api<User[]>(`/environments/${first.data?.environment_id}/eligible-assignees`),enabled:Boolean(first.data?.environment_id&&(action==='assign'||action==='add_participant'))});
  const statuses=useQuery({queryKey:['bulk-statuses',selectedIds[0]],queryFn:()=>api<{id:string;label:string}[]>(`/cases/${selectedIds[0]}/allowed-transitions`),enabled:Boolean(selectedIds[0]&&action==='status')});
  const fields=useQuery({queryKey:['bulk-global-fields'],queryFn:()=>api<GlobalField[]>('/global-case-fields?include_inactive=false'),enabled:action==='priority'});
  const options=useMemo(()=>action==='status'?(statuses.data||[]):action==='priority'?((fields.data||[]).find(field=>field.semantic_binding==='case.priority')?.options||[]).filter(row=>row.is_active).map(row=>({id:row.id,label:row.label_he})):(users.data||[]).map(row=>({id:row.id,label:row.display_name})),[action,statuses.data,fields.data,users.data]);
  const previewMutation=useMutation({mutationFn:()=>api<Preview>('/workspace/bulk/preview',{method:'POST',body:JSON.stringify({case_ids:selectedIds,action,target_id:target})}),onSuccess:setPreview});
  const apply=useMutation({mutationFn:()=>api<Result>('/workspace/bulk/apply',{method:'POST',body:JSON.stringify({preview_id:preview?.preview_id})}),onSuccess:async value=>{setResult(value);await client.invalidateQueries({queryKey:['workspace-cases']})}});
  if(!selectedIds.length)return null;return <><Paper className="bulk-toolbar" elevation={6}><Typography fontWeight={650}>{selectedIds.length} קריאות נבחרו</Typography><Stack direction={{xs:'column',sm:'row'}} gap={1}><TextField select size="small" label="פעולה" value={action} onChange={event=>{setAction(event.target.value as Action);setTarget('');setPreview(undefined)}} sx={{minWidth:160}}><MenuItem value="assign">שיוך מטפל</MenuItem><MenuItem value="status">שינוי סטטוס</MenuItem><MenuItem value="priority">שינוי עדיפות</MenuItem><MenuItem value="add_participant">הוספת משתתף</MenuItem></TextField><TextField select size="small" label="ערך יעד" value={target} onChange={event=>setTarget(event.target.value)} sx={{minWidth:180}}>{options.map(option=><MenuItem key={option.id} value={option.id}>{option.label}</MenuItem>)}</TextField><Button variant="contained" disabled={!target||previewMutation.isPending} onClick={()=>previewMutation.mutate()}>תצוגה מקדימה</Button><Button startIcon={<Close/>} onClick={onClear}>ביטול</Button></Stack></Paper><Dialog open={Boolean(preview)} onClose={()=>setPreview(undefined)} fullWidth maxWidth="sm"><DialogTitle>אישור פעולה גורפת</DialogTitle><DialogContent><Alert severity={preview?.skipped?'warning':'info'}>{preview?.eligible} קריאות יבצעו את הפעולה; {preview?.skipped} ידולגו.</Alert><Stack mt={2}>{preview?.items.map(row=><Typography key={row.case_id}>{row.case_number}: {row.eligible?'מוכן לביצוע':row.reason}</Typography>)}</Stack>{result&&<Alert severity={result.failed?'warning':'success'} sx={{mt:2}}>הצליחו: {result.succeeded}, דולגו: {result.skipped}, נכשלו: {result.failed}</Alert>}</DialogContent><DialogActions><Button onClick={()=>setPreview(undefined)}>סגירה</Button><Button variant="contained" disabled={Boolean(result)||apply.isPending} onClick={()=>apply.mutate()}>אישור וביצוע</Button></DialogActions></Dialog></>;
}
