import { MoreHoriz, OpenInNew } from '@mui/icons-material';
import { Card, CardActionArea, CardContent, IconButton, Menu, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TableSortLabel, Typography } from '@mui/material';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { BusinessPill } from '../../components/BusinessPill';
import { displayCaseNumber } from '../cases/details/caseDisplay';
import type { WorkspaceCase } from './types';
import { useTranslation } from 'react-i18next';

const sortable = new Set(['case_number', 'title', 'created_at', 'updated_at']);
export function DashboardCaseList({ items, sort, onSort }: { items: WorkspaceCase[]; sort: string; onSort: (key: string) => void }) {
  const { t, i18n } = useTranslation(); const locale = i18n.language === 'en' ? 'en-US' : 'he-IL'; const navigate = useNavigate();
  const [menu, setMenu] = useState<{ anchor: HTMLElement; id: string }>();
  if (!items.length) return <Paper className="empty-state" variant="outlined"><Typography variant="h6">{t('dashboard.empty')}</Typography><Typography color="text.secondary">{t('dashboard.emptyHelp')}</Typography></Paper>;
  const columns = [['case_number', t('dashboard.caseNumber')], ['title', t('cases.subject')], ['environment', t('cases.environment')], ['request_type', t('cases.requestType')], ['status', t('dashboard.status')], ['priority', t('dashboard.priority')], ['created_at', t('dashboard.created')], ['updated_at', t('dashboard.updated')]];
  return <><Paper className="data-table" variant="outlined" sx={{ display: { xs: 'none', md: 'block' } }}><Table><TableHead><TableRow>{columns.map(([key, label]) => <TableCell key={key}>{sortable.has(key) ? <TableSortLabel active={sort.startsWith(key)} direction={sort.endsWith(':asc') ? 'asc' : 'desc'} onClick={() => onSort(key)}>{label}</TableSortLabel> : label}</TableCell>)}<TableCell width={64}>פעולות</TableCell></TableRow></TableHead><TableBody>{items.map((item) => <TableRow hover key={item.id} onDoubleClick={() => navigate(`/cases/${item.id}`)}><TableCell><Typography color="primary" fontWeight={850}>{displayCaseNumber(item.case_number)}</Typography></TableCell><TableCell><Typography fontWeight={700}>{item.title}</Typography></TableCell><TableCell>{item.environment}</TableCell><TableCell>{item.request_type}</TableCell><TableCell><BusinessPill label={item.status}/></TableCell><TableCell><BusinessPill label={item.priority} kind="priority"/></TableCell><TableCell>{new Date(item.created_at).toLocaleDateString(locale)}</TableCell><TableCell>{new Date(item.updated_at).toLocaleString(locale)}</TableCell><TableCell><IconButton aria-label="פעולות" onClick={(event) => setMenu({ anchor: event.currentTarget, id: item.id })}><MoreHoriz/></IconButton></TableCell></TableRow>)}</TableBody></Table></Paper>
    <Menu anchorEl={menu?.anchor} open={Boolean(menu)} onClose={() => setMenu(undefined)}><MenuItem onClick={() => menu && navigate(`/cases/${menu.id}`)}><OpenInNew fontSize="small" sx={{ ml: 1 }}/>פתיחת הקריאה</MenuItem></Menu>
    <Stack spacing={1.5} sx={{ display: { md: 'none' } }}>{items.map((item) => <Card variant="outlined" key={item.id}><CardActionArea onClick={() => navigate(`/cases/${item.id}`)}><CardContent><Typography color="primary" fontWeight={850}>{displayCaseNumber(item.case_number)}</Typography><Typography variant="h6">{item.title}</Typography><Stack direction="row" gap={1} mt={1} flexWrap="wrap"><BusinessPill label={item.status}/><BusinessPill label={item.priority} kind="priority"/></Stack><Typography variant="body2" mt={1}>{item.environment} · {item.request_type}</Typography><Typography variant="caption" color="text.secondary">{t('dashboard.updated')}: {new Date(item.updated_at).toLocaleString(locale)}</Typography></CardContent></CardActionArea></Card>)}</Stack></>;
}
