import { MoreHoriz, OpenInNew, Visibility } from '@mui/icons-material';
import { Card, CardContent, Checkbox, IconButton, Menu, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TableSortLabel, Typography } from '@mui/material';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { BusinessPill } from '../../components/BusinessPill';
import { displayCaseNumber } from '../cases/details/caseDisplay';
import type { WorkspaceCase } from './types';

const sortable=new Set(['case_number','title','created_at','updated_at']);
export function DashboardCaseList({items,sort,onSort,visibleColumns,selectedIds=[],onToggle,onPreview}:{items:WorkspaceCase[];sort:string;onSort:(key:string)=>void;visibleColumns?:string[];selectedIds?:string[];onToggle?:(id:string)=>void;onPreview?:(id:string)=>void}){
  const {t,i18n}=useTranslation();const locale=i18n.language==='en'?'en-US':'he-IL';const navigate=useNavigate();const[menu,setMenu]=useState<{anchor:HTMLElement;id:string}>();
  if(!items.length)return <Paper className="empty-state" variant="outlined"><Typography variant="h6">{t('dashboard.empty')}</Typography><Typography color="text.secondary">{t('dashboard.emptyHelp')}</Typography></Paper>;
  const all=[['case_number',t('dashboard.caseNumber')],['title',t('cases.subject')],['environment',t('cases.environment')],['request_type',t('cases.requestType')],['status',t('dashboard.status')],['priority',t('dashboard.priority')],['sla_state','SLA'],['sla_due_at','יעד SLA'],['created_at',t('dashboard.created')],['updated_at',t('dashboard.updated')]];
  const columns=all.filter(([key])=>!visibleColumns||visibleColumns.includes(key));
  const cell=(item:WorkspaceCase,key:string)=>{const value=item[key as keyof WorkspaceCase];if(key==='case_number')return <Typography color="primary" fontWeight={850}>{displayCaseNumber(String(value))}</Typography>;if(key==='title')return <Typography fontWeight={700}>{String(value)}</Typography>;if(key==='status')return <BusinessPill label={String(value)}/>;if(key==='priority')return <BusinessPill label={String(value)} kind="priority"/>;if(key==='sla_state')return <BusinessPill label={({running:'תקין',warning:'בסיכון',breached:'בחריגה',paused:'מושהה',not_started:'ללא SLA'} as Record<string,string>)[String(value)]||String(value)}/>;if(key==='sla_due_at')return value?new Date(String(value)).toLocaleString(locale):'';if(key==='created_at')return new Date(String(value)).toLocaleDateString(locale);if(key==='updated_at')return new Date(String(value)).toLocaleString(locale);return String(value||'');};
  return <><Paper className="data-table" variant="outlined" sx={{display:{xs:'none',md:'block'}}}><Table><TableHead><TableRow>{onToggle&&<TableCell padding="checkbox"/>}{columns.map(([key,label])=><TableCell key={key}>{sortable.has(key)?<TableSortLabel active={sort.startsWith(key)} direction={sort.endsWith(':asc')?'asc':'desc'} onClick={()=>onSort(key)}>{label}</TableSortLabel>:label}</TableCell>)}<TableCell width={64}>פעולות</TableCell></TableRow></TableHead><TableBody>{items.map(item=><TableRow hover key={item.id} onClick={()=>onPreview?.(item.id)} onDoubleClick={()=>navigate(`/cases/${item.id}`)}>{onToggle&&<TableCell padding="checkbox"><Checkbox checked={selectedIds.includes(item.id)} onClick={event=>event.stopPropagation()} onChange={()=>onToggle(item.id)}/></TableCell>}{columns.map(([key])=><TableCell key={key}>{cell(item,key)}</TableCell>)}<TableCell><IconButton aria-label="פעולות" onClick={event=>{event.stopPropagation();setMenu({anchor:event.currentTarget,id:item.id})}}><MoreHoriz/></IconButton></TableCell></TableRow>)}</TableBody></Table></Paper><Menu anchorEl={menu?.anchor} open={Boolean(menu)} onClose={()=>setMenu(undefined)}><MenuItem onClick={()=>{if(menu)onPreview?.(menu.id);setMenu(undefined)}}><Visibility fontSize="small" sx={{ml:1}}/>תצוגה מהירה</MenuItem><MenuItem onClick={()=>menu&&navigate(`/cases/${menu.id}`)}><OpenInNew fontSize="small" sx={{ml:1}}/>פתיחת הקריאה</MenuItem></Menu><Stack spacing={1.5} sx={{display:{md:'none'}}}>{items.map(item=><Card variant="outlined" key={item.id}><CardContent><Stack direction="row" justifyContent="space-between"><Checkbox checked={selectedIds.includes(item.id)} onChange={()=>onToggle?.(item.id)}/><IconButton onClick={()=>onPreview?.(item.id)}><Visibility/></IconButton></Stack><Typography color="primary" fontWeight={850}>{displayCaseNumber(item.case_number)}</Typography><Typography variant="h6">{item.title}</Typography><Stack direction="row" gap={1} mt={1} flexWrap="wrap"><BusinessPill label={item.status}/><BusinessPill label={item.priority} kind="priority"/></Stack><Typography variant="body2" mt={1}>{item.environment} · {item.request_type}</Typography><Typography variant="caption" color="text.secondary">{t('dashboard.updated')}: {new Date(item.updated_at).toLocaleString(locale)}</Typography></CardContent></Card>)}</Stack></>;
}
