import { Add, ContentCopy, DeleteOutline, Edit, MoreVert, Star, ViewColumn } from '@mui/icons-material';
import { Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, IconButton, Menu, MenuItem, Stack, TextField, Tooltip } from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useState } from 'react';
import { api } from '../../api/client';
import type { WorkspaceFilters } from './types';

export const workspaceColumns = ['case_number','title','environment','request_type','status','priority','sla_state','sla_due_at','created_at','updated_at'] as const;
const labels:Record<string,string>={case_number:'מספר קריאה',title:'נושא',environment:'סביבה',request_type:'סוג קריאה',status:'סטטוס',priority:'עדיפות',sla_state:'מצב SLA',sla_due_at:'יעד SLA',created_at:'תאריך פתיחה',updated_at:'עדכון אחרון'};
export type SavedView={id:string;name:string;filters:WorkspaceFilters;sort:string;visible_columns:string[];page_size:number;is_default:boolean};

export function SavedViewsBar({filters,sort,pageSize,visibleColumns,onApply,onColumnsChange}:{filters:WorkspaceFilters;sort:string;pageSize:number;visibleColumns:string[];onApply:(view:SavedView)=>void;onColumnsChange:(columns:string[])=>void}){
  const client=useQueryClient();const [dialog,setDialog]=useState<'create'|'rename'>();const [name,setName]=useState('');const [selected,setSelected]=useState<SavedView>();const [menu,setMenu]=useState<HTMLElement>();const [columnsMenu,setColumnsMenu]=useState<HTMLElement>();
  const query=useQuery({queryKey:['workspace-saved-views'],queryFn:()=>api<SavedView[]>('/workspace/views')});
  useEffect(()=>{const initial=query.data?.find(row=>row.is_default);if(initial&&!selected){setSelected(initial);onApply(initial)}},[query.data,selected,onApply]);
  const refresh=()=>client.invalidateQueries({queryKey:['workspace-saved-views']});
  const save=useMutation({mutationFn:()=>api<SavedView>(dialog==='rename'&&selected?`/workspace/views/${selected.id}`:'/workspace/views',{method:dialog==='rename'?'PUT':'POST',body:JSON.stringify({name:name.trim(),filters,sort,visible_columns:visibleColumns,page_size:pageSize,is_default:selected?.is_default||false})}),onSuccess:(row)=>{void refresh();setSelected(row);setDialog(undefined);setName('')}});
  const action=async(kind:'duplicate'|'default'|'delete')=>{if(!selected)return;if(kind==='delete')await api(`/workspace/views/${selected.id}`,{method:'DELETE'});else await api(`/workspace/views/${selected.id}/${kind}`,{method:'POST'});setMenu(undefined);if(kind==='delete')setSelected(undefined);await refresh()};
  return <Stack direction={{xs:'column',md:'row'}} gap={1} alignItems={{md:'center'}}><TextField select size="small" label="תצוגה שמורה" value={selected?.id||''} onChange={event=>{const row=query.data?.find(item=>item.id===event.target.value);if(row){setSelected(row);onApply(row)}}} sx={{minWidth:220}}><MenuItem value="">תצוגה נוכחית</MenuItem>{query.data?.map(row=><MenuItem key={row.id} value={row.id}>{row.is_default?'★ ':''}{row.name}</MenuItem>)}</TextField><Button startIcon={<Add/>} onClick={()=>{setName('');setDialog('create')}}>שמירת תצוגה</Button><Tooltip title="עמודות"><IconButton onClick={event=>setColumnsMenu(event.currentTarget)}><ViewColumn/></IconButton></Tooltip>{selected&&<IconButton aria-label="פעולות תצוגה" onClick={event=>setMenu(event.currentTarget)}><MoreVert/></IconButton>}<Menu anchorEl={menu} open={Boolean(menu)} onClose={()=>setMenu(undefined)}><MenuItem onClick={()=>{setName(selected?.name||'');setDialog('rename');setMenu(undefined)}}><Edit fontSize="small"/> שינוי שם</MenuItem><MenuItem onClick={()=>void action('duplicate')}><ContentCopy fontSize="small"/> שכפול</MenuItem><MenuItem onClick={()=>void action('default')}><Star fontSize="small"/> הגדרת ברירת מחדל</MenuItem><MenuItem onClick={()=>void action('delete')}><DeleteOutline fontSize="small"/> מחיקה</MenuItem></Menu><Menu anchorEl={columnsMenu} open={Boolean(columnsMenu)} onClose={()=>setColumnsMenu(undefined)}>{workspaceColumns.map(column=><MenuItem key={column}><FormControlLabel label={labels[column]} control={<Checkbox checked={visibleColumns.includes(column)} onChange={(_,checked)=>{const next=checked?[...visibleColumns,column]:visibleColumns.filter(item=>item!==column);if(next.length)onColumnsChange(next)}}/>}/></MenuItem>)}</Menu><Dialog open={Boolean(dialog)} onClose={()=>setDialog(undefined)} fullWidth maxWidth="xs"><DialogTitle>{dialog==='rename'?'שינוי שם תצוגה':'שמירת תצוגה חדשה'}</DialogTitle><DialogContent><TextField autoFocus fullWidth margin="dense" label="שם התצוגה" value={name} onChange={event=>setName(event.target.value)}/></DialogContent><DialogActions><Button onClick={()=>setDialog(undefined)}>ביטול</Button><Button variant="contained" disabled={!name.trim()||save.isPending} onClick={()=>save.mutate()}>שמירה</Button></DialogActions></Dialog></Stack>;
}
