import { useState } from 'react';
import { Alert, Button, Chip, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { api } from '../../../api/client';

type Preview={created:number;updated:number;disabled:number;unchanged:number;errors:number;users:unknown[];delta_link?:string};
type Diagnostic={code:string;label:string;ok:boolean;message:string};
export function DirectorySyncTab({onChanged}:{onChanged:()=>Promise<void>}) {
  const[provider,setProvider]=useState('fake');const[preview,setPreview]=useState<Preview>();const[message,setMessage]=useState('');const[error,setError]=useState('');const[diagnostics,setDiagnostics]=useState<Diagnostic[]>([]);
  async function connection(){setError('');setMessage('');try{const result=await api<{ok:boolean;message?:string;steps:Diagnostic[]}>(`/directory/${provider}/test`,{method:'POST'});setDiagnostics(result.steps||[]);if(result.ok)setMessage(result.message||'החיבור תקין');else setError(result.message||'בדיקת החיבור נכשלה');}catch(caught){setError((caught as Error).message)}}
  async function loadPreview(){setError('');try{setPreview(await api<Preview>(`/directory/${provider}/preview`,{method:'POST'}))}catch(caught){setError((caught as Error).message)}}
  async function apply(){if(!preview)return;await api('/directory/apply',{method:'POST',body:JSON.stringify({provider,users:preview.users,delta_link:preview.delta_link})});setMessage('הסנכרון הושלם');setPreview(undefined);await onChanged()}
  return <Stack spacing={2}>{error&&<Alert severity="error">{error}</Alert>}{message&&<Alert severity="success">{message}</Alert>}<Paper variant="outlined" sx={{p:3}}><Stack spacing={2}><Typography variant="h6">Directory</Typography><TextField select label="ספק חיבור" value={provider} onChange={event=>{setProvider(event.target.value);setPreview(undefined);setDiagnostics([])}}><MenuItem value="fake">Fake — בדיקות</MenuItem><MenuItem value="entra">Microsoft Entra</MenuItem><MenuItem value="active_directory">Active Directory מקומי</MenuItem></TextField><Stack direction={{xs:'column',sm:'row'}} gap={1}><Button onClick={connection}>בדיקת חיבור</Button><Button variant="outlined" onClick={loadPreview}>תצוגה מקדימה</Button><Button variant="contained" disabled={!preview} onClick={apply}>סנכרון עכשיו</Button></Stack>{diagnostics.length>0&&<Stack spacing={1}>{diagnostics.map(step=><Stack key={step.code} direction="row" gap={1} alignItems="center"><Chip size="small" color={step.ok?'success':'error'} label={step.ok?'✓':'✗'}/><Typography fontWeight={700}>{step.label}</Typography><Typography color="text.secondary">{step.message}</Typography></Stack>)}</Stack>}{preview&&<Alert severity="info">חדשים: {preview.created} · לעדכון: {preview.updated} · להשבתה: {preview.disabled} · ללא שינוי: {preview.unchanged} · שגיאות: {preview.errors}</Alert>}</Stack></Paper></Stack>;
}
