import { useState } from 'react';
import { Alert, Button, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { api } from '../../../api/client';

type Preview = { created: number; updated: number; disabled: number; unchanged: number; errors: number; users: unknown[]; delta_link?: string };
export function DirectorySyncTab({ onChanged }: { onChanged: () => Promise<void> }) {
  const [provider, setProvider] = useState('fake'); const [preview, setPreview] = useState<Preview>(); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  async function connection() { try { const result = await api<{message?:string}>(`/directory/${provider}/test`, {method:'POST'}); setMessage(result.message || 'החיבור תקין'); } catch (caught) { setError((caught as Error).message); } }
  async function loadPreview() { setError(''); try { setPreview(await api<Preview>(`/directory/${provider}/preview`, {method:'POST'})); } catch (caught) { setError((caught as Error).message); } }
  async function apply() { if (!preview) return; await api('/directory/apply', {method:'POST', body:JSON.stringify({provider, users:preview.users, delta_link:preview.delta_link})}); setMessage('הסנכרון הושלם'); setPreview(undefined); await onChanged(); }
  return <Stack spacing={2}>{error && <Alert severity="error">{error}</Alert>}{message && <Alert severity="success">{message}</Alert>}<Paper variant="outlined" sx={{p:3}}><Stack spacing={2}><Typography variant="h6">Directory</Typography><TextField select label="מצב חיבור" value={provider} onChange={(event)=>{setProvider(event.target.value);setPreview(undefined)}}><MenuItem value="fake">Fake — בדיקות</MenuItem><MenuItem value="entra">Microsoft Entra</MenuItem><MenuItem value="active_directory">Active Directory מקומי</MenuItem></TextField><Stack direction={{xs:'column',sm:'row'}} gap={1}><Button onClick={connection}>בדיקת חיבור</Button><Button variant="outlined" onClick={loadPreview}>תצוגה מקדימה</Button><Button variant="contained" disabled={!preview} onClick={apply}>סנכרון עכשיו</Button></Stack>{preview && <Alert severity="info">חדשים: {preview.created} · לעדכון: {preview.updated} · להשבתה: {preview.disabled} · ללא שינוי: {preview.unchanged} · שגיאות: {preview.errors}</Alert>}</Stack></Paper><Paper variant="outlined" sx={{p:3}}><Typography variant="h6">Excel</Typography><Stack direction={{xs:'column',sm:'row'}} gap={1} sx={{mt:2}}><Button href="/api/users/import/template">הורדת תבנית משתמשים</Button><Button href="/api/users-export">ייצוא משתמשים</Button></Stack></Paper></Stack>;
}
