import { useMemo, useState } from 'react';
import { Add, Search } from '@mui/icons-material';
import { Avatar, Box, Button, Chip, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import type { User, UserSource, UserStatus } from '../../../types';
import { UserTransferPanel } from './UserTransferPanel';
import { emptyUserFilters, filterUsers, type UserFilters } from './userFilters';

const statusLabel:Record<UserStatus,string>={active:'פעיל',inactive:'לא פעיל',archived:'בארכיון'};
const sourceLabel:Record<UserSource,string>={manual:'ידני',excel:'Excel',entra:'Entra',active_directory:'AD'};
export function UsersTab({users,onCreate,onEdit,onChanged}:{users:User[];onCreate:()=>void;onEdit:(user:User)=>void;onChanged:()=>Promise<void>}) {
  const[draft,setDraft]=useState<UserFilters>(emptyUserFilters);const[applied,setApplied]=useState<UserFilters>(emptyUserFilters);
  const departments=[...new Set(users.map(row=>row.department).filter(Boolean))] as string[];const titles=[...new Set(users.map(row=>row.job_title).filter(Boolean))] as string[];
  const visible=useMemo(()=>filterUsers(users,applied),[applied,users]);const set=(key:keyof UserFilters,value:string)=>setDraft(current=>({...current,[key]:value}));
  const reset=()=>{setDraft(emptyUserFilters);setApplied(emptyUserFilters)};
  return <Stack spacing={2}><UserTransferPanel filters={applied} onApplied={onChanged}/><Paper variant="outlined" sx={{p:2}}><Stack component="form" onSubmit={event=>{event.preventDefault();setApplied(draft)}} direction={{xs:'column',lg:'row'}} gap={1}><TextField label="חיפוש חופשי" value={draft.search} onChange={event=>set('search',event.target.value)}/><TextField select label="סטטוס" value={draft.status} onChange={event=>set('status',event.target.value)} sx={{minWidth:140}}><MenuItem value="">הכול</MenuItem><MenuItem value="active">פעיל</MenuItem><MenuItem value="inactive">לא פעיל</MenuItem><MenuItem value="archived">ארכיון</MenuItem></TextField><TextField select label="מקור" value={draft.source} onChange={event=>set('source',event.target.value)} sx={{minWidth:130}}><MenuItem value="">הכול</MenuItem>{Object.entries(sourceLabel).map(([key,label])=><MenuItem key={key} value={key}>{label}</MenuItem>)}</TextField><TextField select label="מחלקה" value={draft.department} onChange={event=>set('department',event.target.value)} sx={{minWidth:150}}><MenuItem value="">הכול</MenuItem>{departments.map(value=><MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField><TextField select label="תפקיד ארגוני" value={draft.jobTitle} onChange={event=>set('jobTitle',event.target.value)} sx={{minWidth:160}}><MenuItem value="">הכול</MenuItem>{titles.map(value=><MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField><Button type="submit" variant="contained" startIcon={<Search/>}>חיפוש</Button><Button onClick={reset}>איפוס</Button><Button variant="outlined" startIcon={<Add/>} onClick={onCreate}>יצירת משתמש</Button></Stack></Paper><Typography color="text.secondary">נמצאו {visible.length} משתמשים</Typography><Paper variant="outlined" sx={{overflowX:'auto'}}><Stack>{visible.length?visible.map(user=><Button key={user.id} color="inherit" onClick={()=>onEdit(user)} sx={{justifyContent:'flex-start',p:2,borderBottom:'1px solid #edf0f5',borderRadius:0,textAlign:'right'}}><Stack direction="row" gap={2} alignItems="center" width="100%"><Avatar>{user.display_name[0]}</Avatar><Box flex={1}><Typography fontWeight={800}>{user.display_name}</Typography><Typography variant="body2" color="text.secondary">{user.email}{user.department?` · ${user.department}`:''}{user.job_title?` · ${user.job_title}`:''}</Typography></Box><Chip label={statusLabel[user.status]} color={user.status==='active'?'success':user.status==='inactive'?'default':'warning'}/><Chip label={sourceLabel[user.source]} variant="outlined"/></Stack></Button>):<Box p={5} textAlign="center">לא נמצאו משתמשים התואמים למסננים</Box>}</Stack></Paper></Stack>;
}
