import { useEffect, useState } from 'react';
import { Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { api } from '../../../api/client';
import type { Environment, Role, User } from '../../../types';
import { UserDirectPermissions } from './UserDirectPermissions';
import { EffectivePermissions } from './EffectivePermissions';

type Selection = { environment_id: string; role_id: string };

export function UserDetailsPage({ user, users, environments, roles, onClose, onSaved }: { user?: User; users: User[]; environments: Environment[]; roles: Role[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const [env, setEnv] = useState(environments[0]?.id || ''); const [memberships, setMemberships] = useState<Selection[]>([]);
  const [copyTargets, setCopyTargets] = useState<string[]>([]); const [copyMode, setCopyMode] = useState<'add_missing' | 'replace_all'>('add_missing'); const [message, setMessage] = useState('');
  useEffect(() => { setMemberships(user?.memberships?.map((item) => ({ environment_id: item.environment_id, role_id: item.role_id })) || []); setCopyTargets([]); setMessage(''); }, [user]);
  const selectedIds = memberships.map((item) => item.environment_id);
  async function save() { if (!user) return; await api(`/users/${user.id}/environment-memberships`, { method: 'PUT', body: JSON.stringify(memberships) }); setMessage('סביבות העבודה נשמרו'); await onSaved(); }
  async function copy() { if (!user || !copyTargets.length) return; const result = await api<{ copied: number }>('/users/environment-memberships/copy', { method: 'POST', body: JSON.stringify({ source_user_id: user.id, target_user_ids: copyTargets, mode: copyMode }) }); setMessage(`הועתקו ${result.copied} שיוכים`); await onSaved(); }
  return <Dialog open={!!user} onClose={onClose} fullWidth maxWidth="md" fullScreen={window.innerWidth < 600}><DialogTitle>כרטיס משתמש</DialogTitle><DialogContent>{user && <Stack spacing={2} sx={{ pt: 1 }}><Typography variant="h5">{user.display_name}</Typography><Typography>{user.email}</Typography>{message && <Typography color="success.main">{message}</Typography>}<Divider/><Typography variant="h6">סביבות עבודה</Typography><TextField select SelectProps={{ multiple: true, renderValue: (selected) => <Stack direction="row" gap={.5} flexWrap="wrap">{(selected as string[]).map((id) => <Chip key={id} label={environments.find((item) => item.id === id)?.name_he || id}/>)}</Stack> }} label="סביבות משויכות" value={selectedIds} onChange={(event) => { const ids = typeof event.target.value === 'string' ? event.target.value.split(',') : event.target.value; setMemberships(ids.map((id) => memberships.find((item) => item.environment_id === id) || { environment_id: id, role_id: roles.find((role) => role.scope === 'environment' && role.is_active)?.id || '' })); }}>{environments.map((item) => <MenuItem key={item.id} value={item.id}>{item.name_he}</MenuItem>)}</TextField>
    {memberships.map((membership) => <Stack key={membership.environment_id} direction={{ xs: 'column', sm: 'row' }} gap={1}><TextField fullWidth label="סביבה" value={environments.find((item) => item.id === membership.environment_id)?.name_he || ''} slotProps={{ input: { readOnly: true } }}/><TextField fullWidth select label="תפקיד" value={membership.role_id} onChange={(event) => setMemberships(memberships.map((item) => item.environment_id === membership.environment_id ? { ...item, role_id: event.target.value } : item))}>{roles.filter((role) => role.scope === 'environment' && role.is_active).map((role) => <MenuItem key={role.id} value={role.id}>{role.name_he || role.name}</MenuItem>)}</TextField></Stack>)}
    <Button variant="contained" disabled={memberships.some((item) => !item.role_id)} onClick={save}>שמירת סביבות עבודה</Button><Divider/><Typography variant="h6">העתקת סביבות</Typography><TextField select SelectProps={{ multiple: true }} label="משתמשי יעד" value={copyTargets} onChange={(event) => setCopyTargets(typeof event.target.value === 'string' ? event.target.value.split(',') : event.target.value)}>{users.filter((item) => item.id !== user.id && item.is_active).map((item) => <MenuItem key={item.id} value={item.id}>{item.display_name}</MenuItem>)}</TextField><TextField select label="אופן ההעתקה" value={copyMode} onChange={(event) => setCopyMode(event.target.value as typeof copyMode)}><MenuItem value="add_missing">הוספת החסרות בלבד</MenuItem><MenuItem value="replace_all">החלפת כל הסביבות</MenuItem></TextField><Button variant="outlined" disabled={!copyTargets.length || !memberships.length} onClick={copy}>העתקת סביבות</Button><Divider/><UserDirectPermissions user={user} environments={environments}/><TextField select label="סביבה להצגת הרשאות אפקטיביות" value={env} onChange={(event) => setEnv(event.target.value)}>{environments.map((item) => <MenuItem key={item.id} value={item.id}>{item.name_he}</MenuItem>)}</TextField><EffectivePermissions user={user} environmentId={env}/></Stack>}</DialogContent><DialogActions><Button onClick={onClose}>סגירה</Button></DialogActions></Dialog>;
}
