import { useRef, useState } from 'react';
import { Alert, Button, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Paper, Stack, Typography } from '@mui/material';
import { useTranslation } from 'react-i18next';
import { api, apiDownload, apiUpload } from '../../../api/client';

type ImportRow={email:string;display_name:string;action:string;errors:string[]};
type ImportPreview={import_session_id:string;created:number;updated:number;disabled:number;unchanged:number;errors:number;rows:ImportRow[]};
type ImportResult={created_count:number;updated_count:number;disabled_count:number;unchanged_count:number;error_count:number;users:{email:string;display_name:string;is_active:boolean}[]};
type Filters={status:string;source:string;department:string;jobTitle:string;search:string};
function saveBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url)}

export function UserTransferPanel({filters,onApplied}:{filters:Filters;onApplied:()=>Promise<void>}){
  const {t}=useTranslation();const input=useRef<HTMLInputElement>(null);const[preview,setPreview]=useState<ImportPreview>();const[result,setResult]=useState<ImportResult>();const[open,setOpen]=useState(false);const[error,setError]=useState('');const[busy,setBusy]=useState(false);
  async function download(path:string,name:string){setError('');try{saveBlob(await apiDownload(path),name)}catch(caught){setError((caught as Error).message)}}
  async function choose(file?:File){if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.append('file',file);setPreview(await apiUpload<ImportPreview>('/users/import/preview',form));setOpen(true)}catch(caught){setError((caught as Error).message)}finally{setBusy(false);if(input.current)input.current.value=''}}
  async function apply(){if(!preview)return;setBusy(true);setError('');try{const saved=await api<ImportResult>('/users/import/apply',{method:'POST',body:JSON.stringify({import_session_id:preview.import_session_id})});setResult(saved);await onApplied();setPreview(undefined)}catch(caught){setError((caught as Error).message)}finally{setBusy(false)}}
  const params=new URLSearchParams();if(filters.status)params.set('status_filter',filters.status);if(filters.source)params.set('source',filters.source);if(filters.department)params.set('department',filters.department);if(filters.jobTitle)params.set('job_title',filters.jobTitle);if(filters.search)params.set('search',filters.search);
  return <Paper variant="outlined" sx={{p:2}}><Stack direction={{xs:'column',sm:'row'}} gap={1} alignItems={{sm:'center'}}><Typography fontWeight={800} sx={{flex:1}}>{t('userImport.title')}</Typography><Button onClick={()=>download('/users/import/template','user-import-template.xlsx')}>{t('userImport.template')}</Button><Button onClick={()=>input.current?.click()} disabled={busy}>{t('userImport.import')}</Button><Button variant="outlined" onClick={()=>download(`/users-export?${params}`,'users.xlsx')}>{t('userImport.export')}</Button><input ref={input} hidden type="file" accept=".xlsx" onChange={event=>choose(event.target.files?.[0])}/></Stack>{error&&<Alert severity="error" sx={{mt:1}}>{error}</Alert>}
    <Dialog open={open} onClose={()=>!busy&&setOpen(false)} fullWidth maxWidth="md"><DialogTitle>{t(result?'userImport.completed':'userImport.preview')}</DialogTitle><DialogContent>{result?<Stack spacing={1}><Alert severity="success">{t('userImport.result',{created:result.created_count,updated:result.updated_count,disabled:result.disabled_count,unchanged:result.unchanged_count,errors:result.error_count})}</Alert>{result.users.map(row=><Typography key={row.email}>{row.display_name} · {row.email} · {t(row.is_active?'permissions.active':'permissions.inactive')}</Typography>)}</Stack>:<><Alert severity={preview?.errors?'error':'info'}>{t('userImport.previewResult',{created:preview?.created||0,updated:preview?.updated||0,disabled:preview?.disabled||0,unchanged:preview?.unchanged||0,errors:preview?.errors||0})}</Alert><Stack spacing={1} sx={{mt:2,maxHeight:420,overflow:'auto'}}>{preview?.rows.map((row,index)=><Paper key={`${row.email}-${index}`} variant="outlined" sx={{p:1.5}}><Typography fontWeight={700}>{row.display_name} · {row.email}</Typography><Typography variant="body2">{row.action}{row.errors.length?` · ${row.errors.join(', ')}`:''}</Typography></Paper>)}</Stack></>}</DialogContent><DialogActions>{result?<Button variant="contained" onClick={()=>{setOpen(false);setResult(undefined)}}>{t('userImport.close')}</Button>:<><Button onClick={()=>setOpen(false)} disabled={busy}>{t('common.cancel')}</Button><Button variant="contained" onClick={apply} disabled={busy||!!preview?.errors}>{busy?<><CircularProgress size={18} color="inherit" sx={{ml:1}}/>{t('userImport.applying')}</>:t('userImport.apply')}</Button></>}</DialogActions></Dialog>
  </Paper>;
}
