import { useMemo, useState } from 'react';
import { Add } from '@mui/icons-material';
import { Avatar, Box, Button, Chip, FormControlLabel, MenuItem, Paper, Stack, Switch, TextField, Typography } from '@mui/material';
import type { User, UserSource, UserStatus } from '../../../types';
import { UserTransferPanel } from './UserTransferPanel';

const statusLabel: Record<UserStatus,string> = { active:'פעיל', inactive:'לא פעיל', archived:'בארכיון' };
const sourceLabel: Record<UserSource,string> = { manual:'ידני', excel:'Excel', entra:'Entra', active_directory:'AD' };

export function UsersTab({users,onCreate,onEdit,onChanged}:{users:User[];onCreate:()=>void;onEdit:(user:User)=>void;onChanged:()=>Promise<void>}) {
  const [activeOnly,setActiveOnly]=useState(true); const [status,setStatus]=useState(''); const [source,setSource]=useState(''); const [department,setDepartment]=useState(''); const [jobTitle,setJobTitle]=useState(''); const [search,setSearch]=useState('');
  const departments=[...new Set(users.map(row=>row.department).filter(Boolean))] as string[]; const titles=[...new Set(users.map(row=>row.job_title).filter(Boolean))] as string[];
  const visible=useMemo(()=>users.filter(user=>(!activeOnly||user.status==='active')&&(!status||user.status===status)&&(!source||user.source===source)&&(!department||user.department===department)&&(!jobTitle||user.job_title===jobTitle)&&`${user.display_name} ${user.email} ${user.user_principal_name||''}`.toLowerCase().includes(search.toLowerCase())),[activeOnly,department,jobTitle,search,source,status,users]);
  return <Stack spacing={2}><UserTransferPanel filters={{status:activeOnly?'active':status,source,department,jobTitle,search}} onApplied={onChanged}/><Stack direction={{xs:'column',lg:'row'}} gap={1}><TextField label="חיפוש חופשי" value={search} onChange={event=>setSearch(event.target.value)}/><TextField select label="סטטוס" value={status} onChange={event=>setStatus(event.target.value)} sx={{minWidth:140}}><MenuItem value="">הכול</MenuItem><MenuItem value="active">פעיל</MenuItem><MenuItem value="inactive">לא פעיל</MenuItem><MenuItem value="archived">ארכיון</MenuItem></TextField><TextField select label="מקור" value={source} onChange={event=>setSource(event.target.value)} sx={{minWidth:130}}><MenuItem value="">הכול</MenuItem>{Object.entries(sourceLabel).map(([key,label])=><MenuItem key={key} value={key}>{label}</MenuItem>)}</TextField><TextField select label="מחלקה" value={department} onChange={event=>setDepartment(event.target.value)} sx={{minWidth:150}}><MenuItem value="">הכול</MenuItem>{departments.map(value=><MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField><TextField select label="תפקיד ארגוני" value={jobTitle} onChange={event=>setJobTitle(event.target.value)} sx={{minWidth:160}}><MenuItem value="">הכול</MenuItem>{titles.map(value=><MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField><Button variant="contained" startIcon={<Add/>} onClick={onCreate}>יצירת משתמש</Button></Stack><FormControlLabel control={<Switch checked={activeOnly} onChange={event=>setActiveOnly(event.target.checked)}/>} label="משתמשים פעילים בלבד"/>
    <Paper variant="outlined" sx={{overflowX:'auto'}}><Stack>{visible.length?visible.map(user=><Button key={user.id} color="inherit" onClick={()=>onEdit(user)} sx={{justifyContent:'flex-start',p:2,borderBottom:'1px solid #edf0f5',borderRadius:0,textAlign:'right'}}><Stack direction="row" gap={2} alignItems="center" width="100%"><Avatar>{user.display_name[0]}</Avatar><Box flex={1}><Typography fontWeight={800}>{user.display_name}</Typography><Typography variant="body2" color="text.secondary">{user.email}{user.department?` · ${user.department}`:''}{user.job_title?` · ${user.job_title}`:''}</Typography></Box><Chip label={statusLabel[user.status]} color={user.status==='active'?'success':user.status==='inactive'?'default':'warning'}/><Chip label={sourceLabel[user.source]} variant="outlined"/></Stack></Button>):<Box p={5} textAlign="center">לא נמצאו משתמשים התואמים למסננים</Box>}</Stack></Paper>
  </Stack>;
}
