import { CheckCircleOutline, HourglassTop, SearchOutlined } from '@mui/icons-material';
import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { Alert, Box, Button, Card, CardActionArea, CardContent, Chip, CircularProgress, Container, Dialog, DialogActions, DialogContent, DialogTitle, InputAdornment, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { api } from '../../api/client';
import { BusinessPill } from '../../components/BusinessPill';
import { ScreenHeader } from '../../components/ScreenHeader';
import { ResponsiveTable } from '../../components/responsive/ResponsivePrimitives';
import { displayCaseNumber } from '../cases/details/caseDisplay';

type PendingApproval={task_id:string;case_id:string;case_number:string;title:string;description:string;environment:string;request_type:string;step_name:string;approver_name:string;priority:string;requested_at:string;status:string};
export function PendingApprovalsPage(){
  const qc=useQueryClient(); const[selected,setSelected]=useState<PendingApproval>(); const[details,setDetails]=useState<PendingApproval>(); const[comment,setComment]=useState(''); const[error,setError]=useState(''); const[search,setSearch]=useState(''); const[environment,setEnvironment]=useState('all');
  const query=useQuery({queryKey:['pending-approvals'],queryFn:()=>api<PendingApproval[]>('/approvals/pending-for-me')});
  const decision=useMutation({mutationFn:({task,value}:{task:PendingApproval;value:'approved'|'rejected'})=>api(`/approval-tasks/${task.task_id}/decision`,{method:'POST',body:JSON.stringify({decision:value,comment:comment.trim()||null})}),onSuccess:()=>{setSelected(undefined);setDetails(undefined);setComment('');void Promise.all([qc.invalidateQueries({queryKey:['pending-approvals']}),qc.invalidateQueries({queryKey:['case']}),qc.invalidateQueries({queryKey:['case-approvals']})])},onError:caught=>setError((caught as Error).message)});
  const environments=useMemo(()=>[...new Set((query.data||[]).map(row=>row.environment))],[query.data]);
  const rows=useMemo(()=>(query.data||[]).filter(row=>(environment==='all'||row.environment===environment)&&`${row.case_number} ${row.title} ${row.step_name}`.toLowerCase().includes(search.toLowerCase())),[query.data,environment,search]);
  if(query.isLoading)return <Stack alignItems="center" py={8}><CircularProgress/></Stack>;
  const actions=(row:PendingApproval)=><Stack direction="row" gap={1}><Button fullWidth variant="contained" disabled={decision.isPending} onClick={event=>{event.stopPropagation();decision.mutate({task:row,value:'approved'})}}>אישור</Button><Button fullWidth color="error" variant="outlined" onClick={event=>{event.stopPropagation();setSelected(row)}}>דחייה</Button></Stack>;
  const cards=rows.map(row=><Card variant="outlined" key={row.task_id}><CardActionArea onClick={()=>setDetails(row)}><CardContent><Typography color="primary" fontWeight={650}>{displayCaseNumber(row.case_number)}</Typography><Typography variant="h6">{row.title}</Typography><Typography color="text.secondary" sx={{display:'-webkit-box',WebkitLineClamp:2,WebkitBoxOrient:'vertical',overflow:'hidden'}}>{row.description}</Typography><Stack direction="row" gap={1} my={1} flexWrap="wrap"><Chip size="small" color="warning" label="ממתין לאישור"/><BusinessPill label={row.priority} kind="priority"/></Stack><Typography variant="body2">{row.environment} · {row.approver_name}</Typography><Typography variant="caption">{new Date(row.requested_at).toLocaleString('he-IL')}</Typography><Box mt={2}>{actions(row)}</Box></CardContent></CardActionArea></Card>);
  const table=<TableContainer component={Paper} variant="outlined"><Table><TableHead><TableRow><TableCell>מספר</TableCell><TableCell>נושא</TableCell><TableCell>סביבה</TableCell><TableCell>מאשר</TableCell><TableCell>עדיפות</TableCell><TableCell>תאריך</TableCell><TableCell>פעולות</TableCell></TableRow></TableHead><TableBody>{rows.map(row=><TableRow hover key={row.task_id} onClick={()=>setDetails(row)} sx={{cursor:'pointer'}}><TableCell><Typography color="primary" fontWeight={650}>{displayCaseNumber(row.case_number)}</Typography></TableCell><TableCell><Typography fontWeight={650}>{row.title}</Typography><Typography variant="caption">{row.step_name}</Typography></TableCell><TableCell>{row.environment}</TableCell><TableCell>{row.approver_name}</TableCell><TableCell><BusinessPill label={row.priority} kind="priority"/></TableCell><TableCell>{new Date(row.requested_at).toLocaleString('he-IL')}</TableCell><TableCell>{actions(row)}</TableCell></TableRow>)}</TableBody></Table></TableContainer>;
  return <Box className="admin-page"><Container maxWidth="xl"><Stack spacing={2.5}><ScreenHeader title="קריאות ממתינות לאישור" subtitle="כל החלטות האישור הפעילות שממתינות לטיפולך"/><Box className="approval-kpis"><Card><CardContent><HourglassTop color="warning"/><Typography variant="h4">{query.data?.length||0}</Typography><Typography color="text.secondary">ממתינות לאישור</Typography></CardContent></Card><Card><CardContent><CheckCircleOutline color="success"/><Typography variant="h4">{rows.length}</Typography><Typography color="text.secondary">בתוצאות</Typography></CardContent></Card></Box>{error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}<Paper className="filter-panel" variant="outlined"><Stack direction={{xs:'column',md:'row'}} gap={1.5}><TextField fullWidth label="חיפוש לפי מספר, נושא או שלב" value={search} onChange={event=>setSearch(event.target.value)} slotProps={{input:{startAdornment:<InputAdornment position="start"><SearchOutlined/></InputAdornment>}}}/><TextField select label="סביבה" value={environment} onChange={event=>setEnvironment(event.target.value)} sx={{minWidth:{md:220}}}><MenuItem value="all">כל הסביבות</MenuItem>{environments.map(value=><MenuItem value={value} key={value}>{value}</MenuItem>)}</TextField></Stack></Paper><ResponsiveTable table={table} cards={cards}/>{!rows.length&&<Paper className="empty-state" variant="outlined"><Typography>אין כרגע קריאות שממתינות לאישורך</Typography></Paper>}</Stack></Container>
    <Dialog open={!!details} onClose={()=>setDetails(undefined)} fullWidth maxWidth="sm"><DialogTitle>{details&&`${displayCaseNumber(details.case_number)} · ${details.title}`}</DialogTitle><DialogContent><Stack spacing={1.5}><Typography>{details?.description}</Typography><Typography color="text.secondary">{details?.environment} · {details?.request_type} · {details?.step_name}</Typography></Stack></DialogContent><DialogActions><Button component={Link} to={`/cases/${details?.case_id}`}>פתיחת קריאה</Button><Box flex={1}/>{details&&actions(details)}</DialogActions></Dialog>
    <Dialog open={!!selected} onClose={()=>setSelected(undefined)} fullWidth maxWidth="sm"><DialogTitle>דחיית {selected&&displayCaseNumber(selected.case_number)}</DialogTitle><DialogContent><TextField sx={{mt:1}} fullWidth multiline minRows={3} label="סיבת דחייה" value={comment} onChange={event=>setComment(event.target.value)}/></DialogContent><DialogActions><Button onClick={()=>setSelected(undefined)}>ביטול</Button><Button color="error" variant="contained" disabled={!comment.trim()||decision.isPending} onClick={()=>selected&&decision.mutate({task:selected,value:'rejected'})}>אישור דחייה</Button></DialogActions></Dialog>
  </Box>;
}
