import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, Step, StepLabel, Stepper, TextField, Typography } from '@mui/material';
import { api } from '../../../api/client';
import type { Environment, Priority, SubPriority, User } from '../../../types';

type Preview = { target_environment_name:string; request_types:{id:string;name_he:string;requires_approval:boolean}[]; removed_participant_ids:string[]; assignee_will_be_removed:boolean; current_fields:{field_id:string;label:string;value:unknown}[]; warning:string };
type Requirements = { initial_status_label:string; required_fields:{id:string;label:string;field_type:string}[]; removed_fields:{id:string;label:string}[]; field_mappings:{label:string}[] };

export function CaseTransferWizard({caseId,currentEnvironmentId,open,onClose,onTransferred}:{caseId:string;currentEnvironmentId:string;open:boolean;onClose:()=>void;onTransferred:()=>void}) {
  const [step,setStep]=useState(0); const [target,setTarget]=useState(''); const [requestType,setRequestType]=useState('');
  const [priority,setPriority]=useState(''); const [sub,setSub]=useState(''); const [assignee,setAssignee]=useState('');
  const [values,setValues]=useState<Record<string,string>>({}); const [reason,setReason]=useState(''); const [error,setError]=useState('');
  const [preview,setPreview]=useState<Preview>(); const [requirements,setRequirements]=useState<Requirements>();
  const {data:environments=[]}=useQuery({queryKey:['environments'],queryFn:()=>api<Environment[]>('/environments'),enabled:open});
  const {data:priorities=[]}=useQuery({queryKey:['priorities',target],queryFn:()=>api<Priority[]>(`/environments/${target}/priorities`),enabled:!!target});
  const {data:subs=[]}=useQuery({queryKey:['sub-priorities',target],queryFn:()=>api<SubPriority[]>(`/environments/${target}/sub-priorities`),enabled:!!target});
  const {data:assignees=[]}=useQuery({queryKey:['eligible-assignees',target],queryFn:()=>api<User[]>(`/environments/${target}/eligible-assignees`),enabled:!!target});
  useEffect(()=>{if(!open){setStep(0);setTarget('');setRequestType('');setPreview(undefined);setRequirements(undefined);setValues({});setError('')}},[open]);
  async function next(){try{setError('');if(step===0){const data=await api<Preview>(`/cases/${caseId}/transfer-preview?target_environment_id=${target}`);setPreview(data);setStep(1);return}if(step===1){if(!requestType)throw new Error('יש לבחור סוג קריאה');const data=await api<Requirements>(`/cases/${caseId}/transfer-requirements?request_type_id=${requestType}`);setRequirements(data);setStep(2);return}if(step===2){const missing=requirements?.required_fields.filter(f=>!values[f.id].trim())||[];if(!priority)throw new Error('יש לבחור עדיפות');if(missing.length)throw new Error(`חובה למלא: ${missing.map(f=>f.label).join(', ')}`);setStep(3)}}catch(e){setError((e as Error).message)}}
  async function execute(){try{await api(`/cases/${caseId}/transfer`,{method:'POST',body:JSON.stringify({target_environment_id:target,target_request_type_id:requestType,priority_id:priority,sub_priority_id:sub||null,assignee_id:assignee||null,new_field_values:Object.entries(values).map(([field_definition_id,value])=>({field_definition_id,value})),reason:reason||null})});onTransferred();onClose()}catch(e){setError((e as Error).message)}}
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="md"><DialogTitle>העברת קריאה לסביבה אחרת</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><Stepper activeStep={step}>{['סביבת יעד','השוואה','השלמת מידע','אישור'].map(label=><Step key={label}><StepLabel>{label}</StepLabel></Step>)}</Stepper>{error&&<Alert severity="error">{error}</Alert>}
    {step===0&&<TextField select label="סביבת יעד" value={target} onChange={e=>{setTarget(e.target.value);setRequestType('')}}>{environments.filter(e=>e.is_active&&e.id!==currentEnvironmentId).map(e=><MenuItem key={e.id} value={e.id}>{e.name_he}</MenuItem>)}</TextField>}
    {step===1&&preview&&<><Alert severity="warning">{preview.warning}</Alert><Typography>העברה אל: <strong>{preview.target_environment_name}</strong></Typography><Typography>משתתפים שיוסרו: {preview.removed_participant_ids.length}</Typography><Typography>מטפל נוכחי: {preview.assignee_will_be_removed?'יוסר':'יכול להישאר'}</Typography><TextField select label="סוג קריאה בסביבת היעד" value={requestType} onChange={e=>setRequestType(e.target.value)}>{preview.request_types.map(r=><MenuItem key={r.id} value={r.id}>{r.name_he}{r.requires_approval?' · דורש אישור':''}</MenuItem>)}</TextField></>}
    {step===2&&requirements&&<><Typography>סטטוס התחלתי: <strong>{requirements.initial_status_label}</strong></Typography>{requirements.removed_fields.length>0&&<Alert severity="warning">השדות הבאים לא יוצגו לאחר ההעברה: {requirements.removed_fields.map(f=>f.label).join(', ')}</Alert>}<TextField select label="עדיפות" value={priority} onChange={e=>{setPriority(e.target.value);setSub('')}}>{priorities.filter(p=>p.is_active).map(p=><MenuItem key={p.id} value={p.id}>{p.label_he}</MenuItem>)}</TextField><TextField select label="תת־עדיפות" value={sub} onChange={e=>setSub(e.target.value)}><MenuItem value="">ללא</MenuItem>{subs.filter(s=>s.is_active&&(!s.priority_id||s.priority_id===priority)).map(s=><MenuItem key={s.id} value={s.id}>{s.label_he}</MenuItem>)}</TextField><TextField select label="מטפל בסביבת היעד" value={assignee} onChange={e=>setAssignee(e.target.value)}><MenuItem value="">ללא שיוך</MenuItem>{assignees.map(u=><MenuItem key={u.id} value={u.id}>{u.display_name}</MenuItem>)}</TextField>{requirements.required_fields.map(f=><TextField key={f.id} required label={f.label} value={values[f.id]||''} onChange={e=>setValues({...values,[f.id]:e.target.value})}/>)}</>}
    {step===3&&preview&&requirements&&<><Alert severity="warning">העברת הקריאה תשנה את סביבת העבודה ואת התצורה הפעילה שלה. מידע היסטורי יישמר.</Alert><Typography>סביבה: {preview.target_environment_name}</Typography><Typography>סטטוס חדש: {requirements.initial_status_label}</Typography><Typography>משתתפים שיוסרו: {preview.removed_participant_ids.length}</Typography><Typography>שדות שמופו: {requirements.field_mappings.length}; שדות שיוסרו מהתצוגה: {requirements.removed_fields.length}</Typography><TextField label="סיבת ההעברה (רשות)" multiline value={reason} onChange={e=>setReason(e.target.value)}/></>}
  </Stack></DialogContent><DialogActions><Button onClick={onClose}>ביטול</Button>{step>0&&<Button onClick={()=>setStep(step-1)}>חזרה</Button>}{step<3?<Button variant="contained" disabled={step===0&&!target} onClick={next}>המשך</Button>:<Button variant="contained" color="warning" onClick={execute}>העברת הקריאה</Button>}</DialogActions></Dialog>
}
