import { alpha, createTheme } from '@mui/material/styles';

export const designTokens = {
  ink: '#203e5b', inkHover: '#152e46', inkTint: '#e9eff5',
  canvas: '#f5f7f9', paper: '#ffffff', navigation: '#eef2f6',
  text: '#202d3a', muted: '#59697a', border: '#dce3eb',
  radius: 12, controlRadius: 8,
  font: '"Noto Sans Hebrew", "Segoe UI", sans-serif',
  ease: 'cubic-bezier(0.23, 1, 0.32, 1)',
  overlayShadow: '0 12px 36px rgba(23, 42, 63, .16)',
} as const;

export const createAppTheme = (direction: 'rtl' | 'ltr') => createTheme({
  direction,
  palette: {
    primary: { main: designTokens.ink, dark: designTokens.inkHover, light: designTokens.inkTint },
    secondary: { main: '#48647e' },
    background: { default: designTokens.canvas, paper: designTokens.paper },
    text: { primary: designTokens.text, secondary: designTokens.muted },
    divider: designTokens.border,
    success: { main: '#24634b' }, warning: { main: '#8b530d' },
    error: { main: '#b3343e' }, info: { main: '#315e85' },
    action: { hover: '#f0f4f8', selected: designTokens.inkTint, focus: '#dbe7f2' },
  },
  typography: {
    fontFamily: designTokens.font, fontSize: 14,
    h1: { fontSize: '2rem', lineHeight: 1.35, fontWeight: 700 },
    h4: { fontSize: '1.875rem', lineHeight: 1.4, fontWeight: 700, letterSpacing: '-.025em' },
    h5: { fontSize: '1.375rem', lineHeight: 1.45, fontWeight: 650, letterSpacing: '-.015em' },
    h6: { fontSize: '1.0625rem', lineHeight: 1.5, fontWeight: 650 },
    body1: { fontSize: '.9375rem', lineHeight: 1.65 },
    body2: { fontSize: '.8125rem', lineHeight: 1.6 },
    caption: { fontSize: '.75rem', lineHeight: 1.5 },
    button: { fontWeight: 600, textTransform: 'none', letterSpacing: 0 },
  },
  shape: { borderRadius: designTokens.radius },
  transitions: {
    easing: { easeOut: designTokens.ease },
    duration: { shortest: 120, shorter: 150, short: 180, standard: 200, enteringScreen: 220, leavingScreen: 180 },
  },
  components: {
    MuiCssBaseline: { styleOverrides: {
      ':root': {
        '--app-ink': designTokens.ink, '--app-ink-hover': designTokens.inkHover,
        '--app-tint': designTokens.inkTint, '--app-canvas': designTokens.canvas,
        '--app-paper': designTokens.paper, '--app-navigation': designTokens.navigation,
        '--app-text': designTokens.text, '--app-muted': designTokens.muted,
        '--app-border': designTokens.border, '--app-ease': designTokens.ease,
      },
      body: { fontFamily: designTokens.font, color: designTokens.text },
      '::selection': { background: '#d6e4f1', color: designTokens.inkHover },
      'input, textarea': { caretColor: designTokens.ink },
      ':focus-visible': { outline: `2px solid ${designTokens.ink}`, outlineOffset: 3 },
      '@media (prefers-reduced-motion: reduce)': {
        '*, *::before, *::after': { animationDuration: '0.01ms !important', animationIterationCount: '1 !important', transitionDuration: '0.01ms !important', scrollBehavior: 'auto !important' },
      },
    } },
    MuiPaper: { styleOverrides: { root: { backgroundImage: 'none' }, rounded: { borderRadius: designTokens.radius } } },
    MuiCard: { defaultProps: { variant: 'outlined' }, styleOverrides: { root: { boxShadow: 'none', borderColor: designTokens.border } } },
    MuiCardContent: { styleOverrides: { root: { padding: 24, '&:last-child': { paddingBottom: 24 }, '@media (max-width:599px)': { padding: 16, '&:last-child': { paddingBottom: 16 } } } } },
    MuiButton: { defaultProps: { disableElevation: true }, styleOverrides: {
      root: { minHeight: 40, borderRadius: designTokens.controlRadius, paddingInline: 16, flexShrink: 0, gap: 6,
        transition: `background-color 150ms ${designTokens.ease}, box-shadow 150ms ${designTokens.ease}, transform 120ms ${designTokens.ease}`,
        '@media (hover:hover)': { '&:active': { transform: 'translateY(1px)' } },
        '@media (pointer:coarse)': { minHeight: 44 },
      },
      startIcon: { margin: 0 }, endIcon: { margin: 0 },
      outlined: { borderColor: designTokens.border, backgroundColor: designTokens.paper },
      sizeLarge: { minHeight: 44, fontSize: '.875rem', paddingInline: 20 },
    } },
    MuiIconButton: { styleOverrides: { root: { borderRadius: designTokens.controlRadius, color: designTokens.muted, '@media (pointer:coarse)': { minWidth: 44, minHeight: 44 } } } },
    MuiTextField: { defaultProps: { variant: 'outlined', size: 'small' } },
    MuiOutlinedInput: { styleOverrides: {
      root: { borderRadius: designTokens.controlRadius, minHeight: 44, backgroundColor: designTokens.paper,
        '&:hover .MuiOutlinedInput-notchedOutline': { borderColor: '#899aab' },
        '&.Mui-focused .MuiOutlinedInput-notchedOutline': { borderWidth: 1 },
        '&.Mui-focused': { boxShadow: `0 0 0 3px ${alpha(designTokens.ink, .09)}` },
      },
      notchedOutline: { borderColor: '#bcc8d4' },
      input: { '&::placeholder': { color: designTokens.muted, opacity: 1 } },
    } },
    MuiInputLabel: { styleOverrides: { root: { color: designTokens.muted, fontSize: '.875rem' } } },
    MuiFormHelperText: { styleOverrides: { root: { marginInline: 0 } } },
    MuiChip: { styleOverrides: {
      root: { borderRadius: 6, fontWeight: 550, fontSize: '.75rem', maxWidth: '100%' },
      label: { paddingInline: 10 }, outlined: { backgroundColor: designTokens.paper },
    } },
    MuiAvatar: { styleOverrides: { root: { width: 34, height: 34, fontSize: '.875rem', fontWeight: 650, backgroundColor: designTokens.inkTint, color: designTokens.ink } } },
    MuiTableCell: { styleOverrides: {
      root: { borderColor: designTokens.border, padding: '14px 16px', textAlign: direction === 'rtl' ? 'right' : 'left', fontVariantNumeric: 'tabular-nums', fontSize: '.8125rem' },
      head: { fontWeight: 650, color: designTokens.muted, backgroundColor: designTokens.canvas, paddingBlock: 12 },
    } },
    MuiTableRow: { styleOverrides: { root: { '&.MuiTableRow-hover:hover': { backgroundColor: '#f5f8fb' }, '&.Mui-selected': { backgroundColor: designTokens.inkTint } } } },
    MuiTabs: { styleOverrides: { root: { minHeight: 48 }, indicator: { height: 2 } } },
    MuiTab: { styleOverrides: { root: { minHeight: 48, textTransform: 'none', fontWeight: 600, paddingInline: 20 } } },
    MuiListItemButton: { styleOverrides: { root: { borderRadius: 8, '&.Mui-selected': { backgroundColor: designTokens.inkTint, color: designTokens.ink, '&:hover': { backgroundColor: '#dce6f0' } } } } },
    MuiListItemIcon: { styleOverrides: { root: { minWidth: 36, color: 'inherit' } } },
    MuiMenuItem: { styleOverrides: { root: { minHeight: 40, fontSize: '.875rem', '@media (pointer:coarse)': { minHeight: 44 } } } },
    MuiPopover: { styleOverrides: { paper: { boxShadow: designTokens.overlayShadow, borderRadius: designTokens.radius } } },
    MuiDialog: { styleOverrides: { paper: { boxShadow: designTokens.overlayShadow, borderRadius: 16 } } },
    MuiDialogTitle: { styleOverrides: { root: { fontSize: '1.25rem', fontWeight: 650, padding: '24px 24px 16px' } } },
    MuiDialogActions: { styleOverrides: { root: { padding: '16px 24px', borderTop: `1px solid ${designTokens.border}`, gap: 8 } } },
    MuiAlert: { styleOverrides: { root: { borderRadius: 8, alignItems: 'center' }, icon: { marginInlineEnd: 12, marginInlineStart: 0 } } },
    MuiAccordion: { defaultProps: { disableGutters: true, elevation: 0 }, styleOverrides: { root: { border: `1px solid ${designTokens.border}`, '&:before': { display: 'none' } } } },
    MuiSkeleton: { defaultProps: { animation: false }, styleOverrides: { root: { backgroundColor: designTokens.inkTint } } },
    MuiTooltip: { defaultProps: { enterDelay: 350, enterNextDelay: 0 }, styleOverrides: { tooltip: { backgroundColor: designTokens.inkHover, fontSize: '.75rem' } } },
  },
});
