import { useEffect, useState } from 'react';
import { Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, MenuItem, Stack, TextField } from '@mui/material';
import type { Permission, Role } from '../../../types';

export type RoleForm = { code?: string; name: string; name_he: string; description: string; description_he: string; scope: string; sort_order: number; permissions: string[]; is_active: boolean };
const empty: RoleForm = { name: '', name_he: '', description: '', description_he: '', scope: 'environment', sort_order: 0, permissions: [], is_active: true };

export function RoleDialog({ open, saving, catalog, initial, onClose, onSubmit }: { open: boolean; saving: boolean; catalog: Permission[]; initial?: Role; onClose: () => void; onSubmit: (value: RoleForm) => Promise<void> }) {
  const [value, setValue] = useState<RoleForm>(empty);
  useEffect(() => { if (open) setValue(initial ? { code: initial.code, name: initial.name_he || initial.name, name_he: initial.name_he || initial.name, description: initial.description || '', description_he: initial.description_he || initial.description || '', scope: initial.scope, sort_order: initial.sort_order || 0, permissions: initial.permissions, is_active: initial.is_active } : empty); }, [open, initial]);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!value.name_he.trim()) return; await onSubmit({ ...value, name: value.name_he, description: value.description_he }); }
  return <Dialog open={open} onClose={onClose} fullWidth><Stack component="form" onSubmit={submit}><DialogTitle>{initial ? 'עריכת תפקיד' : 'יצירת תפקיד'}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label="שם התפקיד" value={value.name_he} onChange={(event) => setValue({ ...value, name_he: event.target.value, name: event.target.value })}/><TextField label="תיאור" value={value.description_he} onChange={(event) => setValue({ ...value, description_he: event.target.value, description: event.target.value })}/><TextField type="number" label="סדר" value={value.sort_order} onChange={(event) => setValue({ ...value, sort_order: Number(event.target.value) })}/><TextField select label="תחולה" value={value.scope} onChange={(event) => setValue({ ...value, scope: event.target.value })}><MenuItem value="environment">סביבתית</MenuItem><MenuItem value="system">מערכתית</MenuItem></TextField><TextField select SelectProps={{ multiple: true }} label="הרשאות" value={value.permissions} onChange={(event) => setValue({ ...value, permissions: typeof event.target.value === 'string' ? event.target.value.split(',') : event.target.value })}>{catalog.filter((permission) => permission.is_active !== false).map((permission) => <MenuItem key={permission.code} value={permission.code}>{permission.name_he || permission.code}</MenuItem>)}</TextField><FormControlLabel control={<Checkbox checked={value.is_active} onChange={(event) => setValue({ ...value, is_active: event.target.checked })}/>} label="תפקיד פעיל"/></Stack></DialogContent><DialogActions><Button onClick={onClose}>ביטול</Button><Button type="submit" variant="contained" disabled={saving || !value.name_he.trim()}>{saving ? 'שומר...' : 'שמירה'}</Button></DialogActions></Stack></Dialog>;
}
