import { useState } from 'react';
import { Add } from '@mui/icons-material';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import { Alert,Button,Chip,Dialog,DialogActions,DialogContent,DialogTitle,FormControlLabel,MenuItem,Paper,Stack,Switch,TextField,Typography } from '@mui/material';
import { api } from '../../../../api/client';
import type { CaseField,CaseFieldType,Environment,RequestType } from '../../../../types';
import { CaseFieldOptionsManager } from './CaseFieldOptionsManager';
import { parseCaseFieldOptions as options } from './caseFieldOptions';

type GlobalField={id:string;label_he:string;is_active:boolean};
type GlobalConfig={global_field_id:string;is_visible:boolean;is_required:boolean;show_on_create:boolean;show_on_edit:boolean};
const TYPES:CaseFieldType[]=['short_text','long_text','number','date','datetime','boolean','single_select','multi_select','user','group','email','phone'];

export function CaseFieldsTab({environment}:{environment:Environment}){
  const qc=useQueryClient(); const[open,setOpen]=useState(false); const[error,setError]=useState('');
  const[form,setForm]=useState({label_he:'',field_type:'short_text' as CaseFieldType,request_type_id:'',options:''});
  const{data:fieldData={global_fields:[],environment_fields:[]}}=useQuery({queryKey:['case-fields',environment.id],queryFn:()=>api<{global_fields:CaseField[];environment_fields:CaseField[]}>(`/environments/${environment.id}/case-fields`)});
  const{data:allGlobal=[]}=useQuery({queryKey:['global-case-fields'],queryFn:()=>api<GlobalField[]>('/global-case-fields?include_inactive=true')});
  const{data:globalConfigs=[]}=useQuery({queryKey:['environment-global-field-config',environment.id],queryFn:()=>api<GlobalConfig[]>(`/environments/${environment.id}/global-case-fields/configuration`)});
  const{data:types=[]}=useQuery({queryKey:['request-types',environment.id],queryFn:()=>api<RequestType[]>(`/request-types?environment_id=${environment.id}`)});
  const items=fieldData.environment_fields;
  async function configure(fieldId:string,patch:Partial<GlobalConfig>){const current=globalConfigs.find(row=>row.global_field_id===fieldId)??{global_field_id:fieldId,is_visible:true,is_required:false,show_on_create:true,show_on_edit:true};try{await api(`/environments/${environment.id}/global-case-fields/${fieldId}/configuration`,{method:'PUT',body:JSON.stringify({...current,...patch,global_field_id:undefined})});await Promise.all([qc.invalidateQueries({queryKey:['case-fields',environment.id]}),qc.invalidateQueries({queryKey:['environment-global-field-config',environment.id]})]);}catch(caught){setError((caught as Error).message);}}
  async function save(){setError('');if(!form.label_he.trim()){setError('תווית בעברית היא שדה חובה');return}try{await api(`/environments/${environment.id}/case-fields`,{method:'POST',body:JSON.stringify({key:`field_${crypto.randomUUID().replaceAll('-','').slice(0,16)}`,label_he:form.label_he,label_en:form.label_he,field_type:form.field_type,request_type_id:form.request_type_id||null,options_json:options(form.options),is_required:false,is_active:true,validation_json:{},sort_order:items.length})});setOpen(false);setForm({label_he:'',field_type:'short_text',request_type_id:'',options:''});await qc.invalidateQueries({queryKey:['case-fields',environment.id]});}catch(caught){setError((caught as Error).message);}}
  return <Stack spacing={2}><Typography variant="h6">שדות גלובליים בקריאה</Typography>{error&&<Alert severity="error">{error}</Alert>}
    {allGlobal.map(item=>{const config=globalConfigs.find(row=>row.global_field_id===item.id)??{global_field_id:item.id,is_visible:true,is_required:false,show_on_create:true,show_on_edit:true};return <Paper key={item.id} variant="outlined" sx={{p:2,opacity:item.is_active?1:.6}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" alignItems={{md:'center'}} gap={1}><BoxLabel item={item}/><Stack direction="row" flexWrap="wrap"><FormControlLabel control={<Switch checked={config.is_visible} disabled={!item.is_active} onChange={event=>configure(item.id,{is_visible:event.target.checked})}/>} label={config.is_visible?'מוצג':'מוסתר'}/><FormControlLabel control={<Switch checked={config.is_required} disabled={!config.is_visible} onChange={event=>configure(item.id,{is_required:event.target.checked})}/>} label="חובה"/><FormControlLabel control={<Switch checked={config.show_on_create} disabled={!config.is_visible} onChange={event=>configure(item.id,{show_on_create:event.target.checked})}/>} label="בפתיחה"/><FormControlLabel control={<Switch checked={config.show_on_edit} disabled={!config.is_visible} onChange={event=>configure(item.id,{show_on_edit:event.target.checked})}/>} label="בעריכה"/></Stack></Stack></Paper>})}
    {!allGlobal.length&&<Typography color="text.secondary">לא הוגדרו שדות גלובליים.</Typography>}
    <Button startIcon={<Add/>} variant="contained" onClick={()=>setOpen(true)} sx={{alignSelf:'flex-start'}}>שדה סביבה חדש</Button>
    {items.map(item=><Paper key={item.id} variant="outlined" sx={{p:2}}><Typography fontWeight={700}>{item.label_he}</Typography><Typography variant="body2" color="text.secondary">{item.field_type} · {item.request_type_id?'סוג קריאה':'כל הסביבה'}</Typography>{item.options_json.length>0&&<CaseFieldOptionsManager environmentId={environment.id} fieldId={item.id} options={item.options_json}/>}</Paper>)}
    <Dialog open={open} onClose={()=>setOpen(false)} fullWidth><DialogTitle>יצירת שדה סביבה</DialogTitle><DialogContent><Stack spacing={2} sx={{mt:1}}><TextField label="תווית בעברית" required error={error.includes('תווית')} helperText={error.includes('תווית')?error:undefined} value={form.label_he} onChange={e=>setForm({...form,label_he:e.target.value})}/><TextField select label="סוג שדה" value={form.field_type} onChange={e=>setForm({...form,field_type:e.target.value as CaseFieldType})}>{TYPES.map(t=><MenuItem key={t} value={t}>{t}</MenuItem>)}</TextField><TextField select label="תחולה" value={form.request_type_id} onChange={e=>setForm({...form,request_type_id:e.target.value})}><MenuItem value="">כל הסביבה</MenuItem>{types.map(t=><MenuItem key={t.id} value={t.id}>{t.name_he}</MenuItem>)}</TextField>{['single_select','multi_select'].includes(form.field_type)&&<><TextField label="ערכים לבחירה (תוויות בלבד)" value={form.options} onChange={e=>setForm({...form,options:e.target.value})}/><Stack direction="row" gap={1} flexWrap="wrap">{options(form.options).map(o=><Chip key={o.value} label={o.label_he}/>)}</Stack></>}</Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>ביטול</Button><Button variant="contained" onClick={save}>שמירה</Button></DialogActions></Dialog>
  </Stack>;
}

function BoxLabel({item}:{item:GlobalField}){return <Stack><Typography fontWeight={700}>{item.label_he}</Typography><Typography variant="body2" color="text.secondary">{item.is_active?'מנוהל בהגדרות המערכת':'השדה אינו פעיל במערכת'}</Typography></Stack>;}
