import { useEffect, useState } from 'react';
import { DndContext, KeyboardSensor, PointerSensor, TouchSensor, closestCenter, useSensor, useSensors, type DragEndEvent } from '@dnd-kit/core';
import { SortableContext, arrayMove, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { Alert, Button, Paper, Stack } from '@mui/material';
import { useQueryClient } from '@tanstack/react-query';
import { api } from '../../../../api/client';
type Option={value:string;label_he:string};
function Row({option}:{option:Option}){const{attributes,listeners,setNodeRef,transform,transition}=useSortable({id:option.value});return <Paper ref={setNodeRef} {...attributes} variant="outlined" sx={{p:.5,transform:CSS.Transform.toString(transform),transition}}><Stack direction="row" alignItems="center"><Button {...listeners} aria-label={`גרירת ${option.label_he}`} sx={{minWidth:36,cursor:'grab'}}>☰</Button>{option.label_he}</Stack></Paper>}
export function CaseFieldOptionsManager({environmentId,fieldId,options}:{environmentId:string;fieldId:string;options:Option[]}){const client=useQueryClient();const[ordered,setOrdered]=useState(options);const[error,setError]=useState('');const sensors=useSensors(useSensor(PointerSensor),useSensor(TouchSensor),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));useEffect(()=>setOrdered(options),[options]);async function end(event:DragEndEvent){if(!event.over||event.active.id===event.over.id)return;const before=ordered;const next=arrayMove(before,before.findIndex(row=>row.value===event.active.id),before.findIndex(row=>row.value===event.over?.id));setOrdered(next);try{await api(`/environments/${environmentId}/case-fields/${fieldId}/options/reorder`,{method:'PUT',body:JSON.stringify({ids:next.map(row=>row.value)})});await client.invalidateQueries({queryKey:['case-fields',environmentId]})}catch(caught){setOrdered(before);setError((caught as Error).message)}}return <Stack spacing={.5}>{error&&<Alert severity="error">{error}</Alert>}<DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={end}><SortableContext items={ordered.map(row=>row.value)} strategy={verticalListSortingStrategy}>{ordered.map(option=><Row key={option.value} option={option}/>)}</SortableContext></DndContext></Stack>}
