import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Button, Chip, Divider, Paper, Stack, TextField, Typography } from '@mui/material';
import { api, apiDownload, apiUpload } from '../../../../api/client';
import type { Environment } from '../../../../types';

type Document={id:string;original_filename:string;size:number;status:string;version:number;is_active:boolean;error_message?:string};
type Answer={answer:string;sources:{filename:string;section?:string;chunk_index:number}[]};
export function KnowledgeTab({environment}:{environment:Environment}){const qc=useQueryClient();const[file,setFile]=useState<File>();const[question,setQuestion]=useState('');const[answer,setAnswer]=useState<Answer>();const[error,setError]=useState('');const{data:documents=[]}=useQuery({queryKey:['knowledge',environment.id],queryFn:()=>api<Document[]>(`/environments/${environment.id}/knowledge/documents`),retry:false});
async function upload(){if(!file)return;try{const form=new FormData();form.append('file',file);await apiUpload(`/environments/${environment.id}/knowledge/documents`,form);setFile(undefined);await qc.invalidateQueries({queryKey:['knowledge',environment.id]})}catch(e){setError((e as Error).message)}}
async function ask(){try{setAnswer(await api(`/environments/${environment.id}/knowledge/query`,{method:'POST',body:JSON.stringify({question})}))}catch(e){setError((e as Error).message)}}
async function download(row:Document){const blob=await apiDownload(`/environments/${environment.id}/knowledge/documents/${row.id}/download`);const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=row.original_filename;link.click();URL.revokeObjectURL(url)}
async function reindex(row:Document){await api(`/environments/${environment.id}/knowledge/documents/${row.id}/reindex`,{method:'POST'});await qc.invalidateQueries({queryKey:['knowledge',environment.id]})}
async function toggle(row:Document){await api(`/environments/${environment.id}/knowledge/documents/${row.id}/active?enabled=${!row.is_active}`,{method:'PATCH'});await qc.invalidateQueries({queryKey:['knowledge',environment.id]})}
return <Stack spacing={3}>{error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}<Paper variant="outlined" sx={{p:2}}><Typography variant="h6">מסמכי מאגר הידע</Typography><Typography color="text.secondary">PDF, DOCX, XLSX, TXT או MD. הקובץ נשמר ומאונדקס רק בסביבה זו.</Typography><Stack direction={{xs:'column',sm:'row'}} gap={1} mt={2}><Button component="label" variant="outlined">בחירת מסמך<input hidden type="file" accept=".pdf,.docx,.xlsx,.txt,.md" onChange={e=>setFile(e.target.files?.[0])}/></Button><Typography sx={{flex:1}}>{file?.name||'לא נבחר קובץ'}</Typography><Button variant="contained" disabled={!file} onClick={upload}>העלאה ואינדוקס</Button></Stack><Divider sx={{my:2}}/>{documents.length===0?<Typography color="text.secondary">עדיין לא הועלו מסמכים למאגר הידע.</Typography>:documents.map(row=><Stack key={row.id} direction={{xs:'column',sm:'row'}} gap={1} alignItems={{sm:'center'}} sx={{py:1}}><Typography sx={{flex:1}}>{row.original_filename} · גרסה {row.version}</Typography><Chip label={{ready:'מוכן',processing:'בעיבוד',failed:'נכשל',uploaded:'הועלה'}[row.status]||row.status} color={row.status==='ready'?'success':row.status==='failed'?'error':'default'}/><Chip size="small" label={row.is_active?'פעיל':'מושבת'}/><Button onClick={()=>download(row)}>הורדה</Button><Button onClick={()=>reindex(row)}>אינדוקס מחדש</Button><Button color={row.is_active?'warning':'success'} onClick={()=>toggle(row)}>{row.is_active?'השבתה':'הפעלה'}</Button>{row.error_message&&<Typography color="error">{row.error_message}</Typography>}</Stack>)}</Paper><Paper variant="outlined" sx={{p:2}}><Typography variant="h6">שאל את הידע של הסביבה</Typography><Stack gap={2} mt={2}><TextField multiline minRows={2} label="שאלה" value={question} onChange={e=>setQuestion(e.target.value)}/><Button variant="contained" disabled={question.trim().length<2} onClick={ask}>קבלת תשובה</Button>{answer&&<Alert severity={answer.sources.length?'info':'warning'}><Typography>{answer.answer}</Typography>{answer.sources.map((source,index)=><Typography key={`${source.filename}-${index}`} variant="caption" display="block">מקור: {source.filename}{source.section?`, ${source.section}`:''}</Typography>)}</Alert>}</Stack></Paper></Stack>}
