import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Button, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { api } from '../../../../api/client';
import type { ApprovalFlow, Environment, RequestType, User } from '../../../../types';
import { ApprovalPolicySelector } from './ApprovalPolicySelector';
import { ApprovalStageEditor, type StageValue } from './ApprovalStageEditor';

const emptyStages = (): StageValue[] => [{ active: true, approver_user_id: '' }, { active: false, approver_user_id: '' }, { active: false, approver_user_id: '' }];
export function ApprovalSettingsTab({ environment }: { environment: Environment }) {
  const client = useQueryClient(); const [editing, setEditing] = useState<ApprovalFlow>(); const [requestType, setRequestType] = useState(''); const [name, setName] = useState(''); const [policy, setPolicy] = useState<'all_active_steps' | 'highest_active_step'>('all_active_steps'); const [stages, setStages] = useState(emptyStages());
  const { data: flows = [] } = useQuery({ queryKey: ['approval-flows', environment.id], queryFn: () => api<ApprovalFlow[]>(`/environments/${environment.id}/approval-flows`) });
  const { data: types = [] } = useQuery({ queryKey: ['request-types', environment.id], queryFn: () => api<RequestType[]>(`/request-types?environment_id=${environment.id}`) });
  const { data: users = [] } = useQuery({ queryKey: ['users'], queryFn: () => api<User[]>('/users') });
  const updateStage = (index: number, value: StageValue) => { const next = stages.map((stage, position) => position === index ? value : stage); if (!value.active) for (let position = index + 1; position < next.length; position++) next[position] = { active: false, approver_user_id: '' }; setStages(next); };
  const edit = (flow: ApprovalFlow) => { const next = emptyStages(); flow.steps.slice(0, 3).forEach((step, index) => { next[index] = { active: true, approver_user_id: step.approver_user_id || '' }; }); setEditing(flow); setRequestType(flow.request_type_id || ''); setName(flow.name); setPolicy(flow.approval_policy || 'all_active_steps'); setStages(next); };
  async function save() { const active = stages.filter((stage) => stage.active); const body = { name, request_type_id: requestType, trigger_type: 'case_created', is_active: true, approval_policy: policy, steps: active.map((stage, index) => ({ name: `שלב ${index + 1}`, approver_type: 'user', approver_user_id: stage.approver_user_id, required_approvals: 1, approval_mode: 'any', is_active: true, allow_reject: true, allow_return: false })) }; await api(editing ? `/approval-flows/${editing.id}` : `/environments/${environment.id}/approval-flows`, { method: editing ? 'PUT' : 'POST', body: JSON.stringify(body) }); setEditing(undefined); setRequestType(''); setName(''); setPolicy('all_active_steps'); setStages(emptyStages()); await client.invalidateQueries({ queryKey: ['approval-flows', environment.id] }); }
  return <Stack spacing={2}>{flows.map((flow) => <Paper key={flow.id} variant="outlined" sx={{ p: 2 }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between"><span><Typography fontWeight={800}>{flow.name}</Typography><Typography color="text.secondary">{flow.steps.length} שלבים · {flow.approval_policy === 'highest_active_step' ? 'השלב הגבוה ביותר' : 'כולם מאשרים'}</Typography></span><Button onClick={() => edit(flow)}>עריכה</Button></Stack></Paper>)}<Paper variant="outlined" sx={{ p: 2 }}><Stack spacing={2}><Typography variant="h6" fontWeight={800}>{editing ? 'עריכת הגדרת אישור' : 'הגדרת אישור חדשה'}</Typography><TextField label="שם ההגדרה" value={name} onChange={(event) => setName(event.target.value)}/><TextField select label="סוג קריאה" value={requestType} onChange={(event) => setRequestType(event.target.value)}>{types.map((type) => <MenuItem key={type.id} value={type.id}>{type.name_he}</MenuItem>)}</TextField><ApprovalPolicySelector value={policy} onChange={setPolicy}/>{stages.map((stage, index) => <ApprovalStageEditor key={index} number={index + 1} value={stage} users={users} disabled={index > 0 && !stages[index - 1].active} onChange={(value) => updateStage(index, value)}/>) }<Button variant="contained" disabled={!name || !requestType || stages.filter((stage) => stage.active).some((stage) => !stage.approver_user_id)} onClick={save}>שמירה</Button></Stack></Paper></Stack>;
}
