import { zodResolver } from '@hookform/resolvers/zod';
import { useEffect } from 'react';
import { Controller, useForm, useWatch } from 'react-hook-form';
import { Alert, Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, MenuItem, Stack, TextField } from '@mui/material';
import { ApiError } from '../../../api/client';
import type { Environment, UserField, UserFieldCreatePayload, UserFieldType } from '../../../types';
import { FieldOptionsEditor } from './FieldOptionsEditor';
import { buildOptions, FIELD_TYPES, fieldSchema, suggestKey, type UserFieldFormValues } from './fieldValidation';

const emptyValues: UserFieldFormValues = { key: '', label_he: '', label_en: '', field_type: 'short_text', is_required: false, is_active: true, options_text: '', environment_ids: [], min_length: '', max_length: '', placeholder: '', rows: '3', minimum: '', maximum: '', decimals: '0', pattern: '', default_value: '', sort_order: 0 };
function initialValues(field?: UserField): UserFieldFormValues { if (!field) return emptyValues; const validation = field.validation_json || {}; return { ...emptyValues, key: field.key, label_he: field.label_he, label_en: field.label_en, field_type: field.field_type, is_required: field.is_required, is_active: field.is_active, options_text: field.options_json.map((option) => option.label_he).join(', '), environment_ids: field.environment_ids || [], min_length: String(validation.min_length ?? ''), max_length: String(validation.max_length ?? ''), placeholder: String(validation.placeholder ?? ''), rows: String(validation.rows ?? '3'), minimum: String(validation.minimum ?? ''), maximum: String(validation.maximum ?? ''), decimals: String(validation.decimals ?? '0'), pattern: String(validation.pattern ?? ''), default_value: field.default_value_json == null ? '' : String(field.default_value_json), sort_order: field.sort_order }; }
function optionalNumber(value: string) { return value === '' ? undefined : Number(value); }
function payload(values: UserFieldFormValues): UserFieldCreatePayload { const validation: Record<string, unknown> = {}; if (['short_text','long_text'].includes(values.field_type)) Object.assign(validation, { min_length: optionalNumber(values.min_length), max_length: optionalNumber(values.max_length), placeholder: values.placeholder || undefined }); if (values.field_type === 'long_text') validation.rows = optionalNumber(values.rows); if (values.field_type === 'number') Object.assign(validation, { minimum: optionalNumber(values.minimum), maximum: optionalNumber(values.maximum), decimals: optionalNumber(values.decimals) }); if (['email','phone'].includes(values.field_type)) validation.placeholder = values.placeholder || undefined; if (values.field_type === 'phone') validation.pattern = values.pattern || undefined; Object.keys(validation).forEach((key) => validation[key] === undefined && delete validation[key]); let defaultValue: unknown = values.default_value || null; if (values.field_type === 'boolean') defaultValue = values.default_value === '' ? null : values.default_value === 'true'; if (values.field_type === 'number' && values.default_value !== '') defaultValue = Number(values.default_value); return { key: values.key.trim(), label_he: values.label_he.trim(), label_en: values.label_en.trim() || values.label_he.trim(), field_type: values.field_type, is_required: values.is_required, is_active: values.is_active, options_json: ['single_select','multi_select'].includes(values.field_type) ? buildOptions(values.options_text) : [], default_value_json: defaultValue, validation_json: validation, sort_order: values.sort_order, environment_ids: values.environment_ids }; }

export function UserFieldDialog({ open, saving, field, onClose, onSubmit }: { open: boolean; saving: boolean; environments: Environment[]; field?: UserField; onClose: () => void; onSubmit: (payload: UserFieldCreatePayload) => Promise<void> }) {
  const { control, handleSubmit, reset, setError, setValue, formState: { errors } } = useForm<UserFieldFormValues>({ resolver: zodResolver(fieldSchema), defaultValues: emptyValues });
  const type = useWatch({ control, name: 'field_type' }); const label = useWatch({ control, name: 'label_he' }); const key = useWatch({ control, name: 'key' });
  useEffect(() => { if (open) reset(initialValues(field)); }, [field, open, reset]);
  useEffect(() => { if (!field && label && !key) setValue('key', suggestKey(label), { shouldValidate: true }); }, [field, key, label, setValue]);
  async function submit(values: UserFieldFormValues) { try { await onSubmit(payload(values)); reset(emptyValues); } catch (caught) { if (caught instanceof ApiError) Object.entries(caught.fieldErrors).forEach(([name, message]) => { const mapped = name === 'options_json' || name === 'form' ? 'options_text' : name; if (mapped in emptyValues) setError(mapped as keyof UserFieldFormValues, { message }); }); } }
  function changeType(next: UserFieldType) { setValue('field_type', next); setValue('options_text', ''); setValue('default_value', ''); setValue('min_length', ''); setValue('max_length', ''); setValue('minimum', ''); setValue('maximum', ''); setValue('pattern', ''); }
  return <Dialog open={open} onClose={saving ? undefined : onClose} fullWidth maxWidth="md"><Stack component="form" onSubmit={handleSubmit(submit)} noValidate><DialogTitle>{field ? 'עריכת שדה משתמש' : 'יצירת שדה משתמש'}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>{Object.keys(errors).length > 0 && <Alert severity="error">יש לתקן את השדות המסומנים לפני השמירה</Alert>}
    <Controller name="label_he" control={control} render={({ field: input }) => <TextField {...input} autoFocus label="תווית בעברית" required error={Boolean(errors.label_he)} helperText={errors.label_he?.message} />} />
    <Controller name="label_en" control={control} render={({ field: input }) => <TextField {...input} label="תווית באנגלית" helperText="אופציונלי; אם יישאר ריק יישמר הערך בעברית" />} />
    <Controller name="key" control={control} render={({ field: input }) => <TextField {...input} label="מפתח טכני" required error={Boolean(errors.key)} helperText={errors.key?.message || 'אות אנגלית קטנה בתחילה; לאחר מכן אותיות, מספרים וקו תחתון'} />} />
    <Controller name="field_type" control={control} render={({ field: input }) => <TextField select label="סוג שדה" value={input.value} onChange={(event) => changeType(event.target.value as UserFieldType)}>{FIELD_TYPES.map((item) => <MenuItem key={item} value={item}>{item}</MenuItem>)}</TextField>} />
    {(type === 'single_select' || type === 'multi_select') && <Controller name="options_text" control={control} render={({ field: input }) => <FieldOptionsEditor value={input.value} onChange={input.onChange} error={errors.options_text?.message} />} />}
    {(type === 'short_text' || type === 'long_text') && <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><Controller name="min_length" control={control} render={({ field: input }) => <TextField {...input} type="number" label="אורך מינימלי" />} /><Controller name="max_length" control={control} render={({ field: input }) => <TextField {...input} type="number" label="אורך מקסימלי" />} />{type === 'long_text' && <Controller name="rows" control={control} render={({ field: input }) => <TextField {...input} type="number" label="מספר שורות" />} />}</Stack>}
    {type === 'number' && <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><Controller name="minimum" control={control} render={({ field: input }) => <TextField {...input} type="number" label="מינימום" />} /><Controller name="maximum" control={control} render={({ field: input }) => <TextField {...input} type="number" label="מקסימום" />} /><Controller name="decimals" control={control} render={({ field: input }) => <TextField {...input} type="number" label="ספרות עשרוניות" />} /></Stack>}
    {type === 'date' && <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><Controller name="minimum" control={control} render={({ field: input }) => <TextField {...input} type="date" label="תאריך מינימום" slotProps={{ inputLabel: { shrink: true } }} />} /><Controller name="maximum" control={control} render={({ field: input }) => <TextField {...input} type="date" label="תאריך מקסימום" slotProps={{ inputLabel: { shrink: true } }} />} /></Stack>}
    {['short_text','long_text','email','phone'].includes(type) && <Controller name="placeholder" control={control} render={({ field: input }) => <TextField {...input} label="Placeholder" />} />}
    {type === 'phone' && <Controller name="pattern" control={control} render={({ field: input }) => <TextField {...input} label="Pattern" />} />}
    {type !== 'user' && type !== 'multi_select' && <Controller name="default_value" control={control} render={({ field: input }) => type === 'boolean' ? <TextField select {...input} label="ערך ברירת מחדל"><MenuItem value="">ללא ערך</MenuItem><MenuItem value="true">כן</MenuItem><MenuItem value="false">לא</MenuItem></TextField> : <TextField {...input} type={type === 'date' ? 'date' : type === 'number' ? 'number' : 'text'} label="ערך ברירת מחדל" slotProps={type === 'date' ? { inputLabel: { shrink: true } } : undefined} />} />}
    <Controller name="is_required" control={control} render={({ field: input }) => <FormControlLabel control={<Checkbox checked={input.value} onChange={input.onChange} />} label="שדה חובה" />} />
    {field && <Controller name="is_active" control={control} render={({ field: input }) => <FormControlLabel control={<Checkbox checked={input.value} onChange={input.onChange} />} label="שדה פעיל" />} />}
  </Stack></DialogContent><DialogActions><Button onClick={onClose} disabled={saving}>ביטול</Button><Button type="submit" variant="contained" disabled={saving}>{saving ? 'שומר...' : 'שמירה'}</Button></DialogActions></Stack></Dialog>;
}
