import { useState } from 'react';
import { Add, Edit, Person } from '@mui/icons-material';
import { Alert, Box, Button, Chip, IconButton, Paper, Snackbar, Stack, Tooltip, Typography } from '@mui/material';
import { api } from '../../../api/client';
import type { Environment, UserField, UserFieldCreatePayload } from '../../../types';
import { UserFieldDialog } from './UserFieldDialog';

export function UserFieldsTab({ fields, environments, onSaved }: { fields: UserField[]; environments: Environment[]; onSaved: () => Promise<void> | void }) {
  const [open,setOpen]=useState(false); const[editing,setEditing]=useState<UserField>(); const[saving,setSaving]=useState(false); const[error,setError]=useState(''); const[success,setSuccess]=useState('');
  async function save(payload:UserFieldCreatePayload){setSaving(true);setError('');try{await api(editing?`/user-fields/${editing.id}`:'/user-fields',{method:editing?'PATCH':'POST',body:JSON.stringify(payload)});await onSaved();setOpen(false);setEditing(undefined);setSuccess(editing?'השדה עודכן בהצלחה':'השדה נוצר בהצלחה')}catch(caught){setError((caught as Error).message);throw caught}finally{setSaving(false)}}
  return <Stack spacing={2}>{error&&<Alert severity="error">{error}</Alert>}<Button sx={{alignSelf:'flex-start'}} variant="contained" startIcon={<Add/>} onClick={()=>{setEditing(undefined);setError('');setOpen(true)}}>שדה משתמש חדש</Button>{fields.length===0?<Paper sx={{p:5,textAlign:'center'}}>קטלוג שדות המשתמש ריק</Paper>:fields.map(field=><Paper key={field.id} variant="outlined" sx={{p:2}}><Stack direction="row" spacing={2} alignItems="center"><Person color="primary"/><Box flex={1}><Typography fontWeight={700}>{field.label_he}</Typography><Typography variant="body2" color="text.secondary">{field.key} · {field.field_type}</Typography><Stack direction="row" gap={.5} flexWrap="wrap" sx={{mt:.5}}>{(field.options_json||[]).map(option=><Chip key={option.value} size="small" label={option.label_he}/>)}{(field.environment_ids||[]).map(id=><Chip key={id} size="small" variant="outlined" label={environments.find(environment=>environment.id===id)?.name_he||id}/>)}</Stack></Box><Chip label={field.is_active?(field.is_required?'פעיל · חובה':'פעיל'):'מושבת'}/><Tooltip title="עריכת שדה"><IconButton aria-label={`עריכת ${field.label_he}`} onClick={()=>{setEditing(field);setError('');setOpen(true)}}><Edit/></IconButton></Tooltip></Stack></Paper>)}<UserFieldDialog open={open} saving={saving} environments={environments} field={editing} onClose={()=>{setOpen(false);setEditing(undefined)}} onSubmit={save}/><Snackbar open={Boolean(success)} autoHideDuration={3500} onClose={()=>setSuccess('')} message={success}/></Stack>
}
