import { Search } from '@mui/icons-material';
import { useState } from 'react';
import { Avatar, Box, Checkbox, FormControlLabel, InputAdornment, MenuItem, Paper, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import type { Environment, Group, User } from '../../../types';

export function AccessSubjectsPanel({ tab, setTab, users, groups, environments, environment, setEnvironment, selected, setSelected }: { tab:number;setTab:(value:number)=>void;users:User[];groups:Group[];environments:Environment[];environment:string;setEnvironment:(value:string)=>void;selected:string[];setSelected:(value:string[])=>void }) {
  const [search,setSearch]=useState(''); const [status,setStatus]=useState('all'); const [group,setGroup]=useState('all');
  const entities=(tab===0?users:groups).filter(item=>{const active=item.is_active!==false;const text=tab===0?`${(item as User).display_name} ${(item as User).email}`:(item as Group).name;const groupMatch=tab!==0||group==='all'||(item as User).groups?.some(row=>row.id===group);return(status==='all'||(status==='active')===active)&&groupMatch&&text.toLowerCase().includes(search.toLowerCase())});
  const toggle=(id:string)=>setSelected(selected.includes(id)?selected.filter(value=>value!==id):[...selected,id]);
  return <Paper className="access-subjects" variant="outlined"><Tabs value={tab} onChange={(_,value)=>{setTab(value);setSelected([])}} variant="fullWidth"><Tab label="משתמשים"/><Tab label="קבוצות משתמשים"/></Tabs><Stack spacing={1.5} mt={2}><TextField label="חיפוש" value={search} onChange={e=>setSearch(e.target.value)} slotProps={{input:{startAdornment:<InputAdornment position="start"><Search/></InputAdornment>}}}/><Box sx={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:1}}><TextField select label="סטטוס" value={status} onChange={e=>setStatus(e.target.value)}><MenuItem value="all">הכול</MenuItem><MenuItem value="active">פעיל</MenuItem><MenuItem value="inactive">לא פעיל</MenuItem></TextField>{tab===0&&<TextField select label="קבוצה" value={group} onChange={e=>setGroup(e.target.value)}><MenuItem value="all">כל הקבוצות</MenuItem>{groups.filter(x=>x.is_active).map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField>}</Box><TextField select label="תחולת הרשאה" value={environment} onChange={e=>setEnvironment(e.target.value)}><MenuItem value="">הרשאה כללית</MenuItem>{environments.map(item=><MenuItem key={item.id} value={item.id}>{item.name_he}</MenuItem>)}</TextField><FormControlLabel control={<Checkbox checked={entities.length>0&&selected.length===entities.length} indeterminate={selected.length>0&&selected.length<entities.length} onChange={()=>setSelected(selected.length===entities.length?[]:entities.map(x=>x.id))}/>} label={`בחירת הכול (${entities.length})`}/><Stack spacing={.75} sx={{maxHeight:560,overflowY:'auto'}}>{entities.map(item=>{const name=tab===0?(item as User).display_name:(item as Group).name;const detail=tab===0?(item as User).email:`${(item as Group).member_count} חברים`;return <Stack key={item.id} direction="row" alignItems="center" gap={1} sx={{p:1,borderRadius: '8px',bgcolor:selected.includes(item.id)?'action.selected':'background.default',border:'1px solid',borderColor:selected.includes(item.id)?'primary.light':'transparent'}}><Checkbox checked={selected.includes(item.id)} onChange={()=>toggle(item.id)}/><Avatar sx={{width:34,height:34,bgcolor:'primary.light',color:'primary.dark'}}>{name[0]}</Avatar><Box minWidth={0}><Typography fontWeight={650} noWrap>{name}</Typography><Typography variant="caption" color="text.secondary" noWrap>{detail}</Typography></Box></Stack>})}</Stack></Stack></Paper>;
}
