import { useEffect, useState } from 'react';
import { SaveOutlined } from '@mui/icons-material';
import { Alert, Box, Button, Container, Dialog, DialogActions, DialogContent, DialogTitle, Paper, Stack, Typography } from '@mui/material';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../../api/client';
import { ScreenHeader } from '../../../components/ScreenHeader';
import type { Environment, Group, User } from '../../../types';
import type { AccessLevel } from './AccessLevelSelector';
import { AccessSubjectsPanel } from './AccessSubjectsPanel';
import { PermissionCards } from './PermissionCards';
import type { AccessDomain, MatrixRow } from './types';

type AssignmentPayload={levels:Record<string,AccessLevel|'mixed'>};
export function AccessPage(){
  const client=useQueryClient(); const[tab,setTab]=useState(0); const[selected,setSelected]=useState<string[]>([]); const[environment,setEnvironment]=useState(''); const[levels,setLevels]=useState<Record<string,AccessLevel>>({}); const[confirmOpen,setConfirmOpen]=useState(false); const[message,setMessage]=useState(''); const[error,setError]=useState('');
  const{data:domains=[]}=useQuery({queryKey:['access-domains'],queryFn:()=>api<AccessDomain[]>('/access/domains')}); const{data:users=[]}=useQuery({queryKey:['users'],queryFn:()=>api<User[]>('/users?active_only=false')}); const{data:groups=[]}=useQuery({queryKey:['groups'],queryFn:()=>api<Group[]>('/groups')}); const{data:environments=[]}=useQuery({queryKey:['environments'],queryFn:()=>api<Environment[]>('/environments')});
  const scope=environment?`&environment_id=${environment}`:'';
  const assignments=useQuery({queryKey:['access-assignments',tab,selected,environment],queryFn:()=>api<AssignmentPayload>(`/access/assignments?subject_type=${tab===0?'users':'groups'}&subject_ids=${selected.join(',')}${scope}`),enabled:selected.length>0});
  const matrix=useQuery({queryKey:['access-matrix',tab,selected[0],environment],queryFn:()=>api<MatrixRow[]>(`/access/subjects/${tab===0?'user':'group'}/${selected[0]}/matrix?${scope.slice(1)}`),enabled:selected.length===1});
  useEffect(()=>{if(!selected.length)setLevels({});else if(selected.length===1&&matrix.data)setLevels(Object.fromEntries(matrix.data.map(row=>[row.domain_code,row.direct_level])));else if(assignments.data)setLevels(Object.fromEntries(Object.entries(assignments.data.levels).filter(([,value])=>value!=='mixed')) as Record<string,AccessLevel>)},[assignments.data,matrix.data,selected.length]);
  const selectedName=selected.length===1?(tab===0?users.find(x=>x.id===selected[0])?.display_name:groups.find(x=>x.id===selected[0])?.name):selected.length?`${selected.length} פריטים נבחרו`:'לא נבחר משתמש או קבוצה';
  const isAdmin=tab===0?users.find(x=>x.id===selected[0])?.is_system_admin:groups.find(x=>x.id===selected[0])?.is_system_admin_group;
  async function save(){setError('');try{await api('/access/bulk',{method:'POST',body:JSON.stringify({subject_type:tab===0?'users':'groups',subject_ids:selected,environment_id:environment||null,levels})});setConfirmOpen(false);await Promise.all([client.invalidateQueries({queryKey:['access-assignments']}),client.invalidateQueries({queryKey:['access-matrix']}),client.invalidateQueries({queryKey:['effective-access']})]);const fresh=selected.length===1?await matrix.refetch():undefined;if(fresh?.data&&!fresh.data.every(row=>row.direct_level===(levels[row.domain_code]||'inherit')))throw new Error('השמירה לא אומתה מול השרת');setMessage('ההרשאות נשמרו ואומתו')}catch(caught){setError((caught as Error).message)}}
  return <Box className="admin-page"><Container maxWidth="xl"><Stack spacing={2.5}><ScreenHeader title="משתמשים והרשאות" subtitle="ניהול הרשאות ישירות, ירושה קבוצתית ותחולה סביבתית ממקום אחד"/>{message&&<Alert severity="success" onClose={()=>setMessage('')}>{message}</Alert>}{error&&<Alert severity="error">{error}</Alert>}{(assignments.isError||matrix.isError)&&<Alert severity="error">לא ניתן לטעון את מטריצת ההרשאות</Alert>}{isAdmin&&<Alert severity="info">מנהל מערכת או קבוצת Admin מקבלים אוטומטית הרשאת מקסימום לכל תחום קיים ועתידי.</Alert>}
    <Box className="access-layout"><Box className="access-subject-column"><AccessSubjectsPanel tab={tab} setTab={setTab} users={users} groups={groups} environments={environments} environment={environment} setEnvironment={value=>{setEnvironment(value);setLevels({})}} selected={selected} setSelected={setSelected}/></Box><Box className="access-permission-column"><Paper className="access-heading" variant="outlined"><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" alignItems={{sm:'center'}} gap={1}><Box><Typography variant="h5">ניהול הרשאות</Typography><Typography color="text.secondary">{selectedName}{environment?` · ${environments.find(x=>x.id===environment)?.name_he}`:' · הרשאה כללית'}</Typography></Box><Button variant="contained" startIcon={<SaveOutlined/>} disabled={!selected.length||!Object.keys(levels).length||Boolean(isAdmin)} onClick={()=>setConfirmOpen(true)}>שמירת שינויים</Button></Stack></Paper><PermissionCards domains={selected.length?domains:[]} matrix={matrix.data||[]} levels={levels} onChange={(code,value)=>setLevels({...levels,[code]:value})}/></Box></Box>
  </Stack></Container><Dialog open={confirmOpen} onClose={()=>setConfirmOpen(false)} fullWidth maxWidth="sm"><DialogTitle>אישור שינוי הרשאות</DialogTitle><DialogContent><Typography>השינויים יחולו על {selected.length} משתמשים או קבוצות בתחולה {environment?'הסביבתית שנבחרה':'הכללית'}.</Typography></DialogContent><DialogActions><Button onClick={()=>setConfirmOpen(false)}>ביטול</Button><Button variant="contained" onClick={save}>אישור ושמירה</Button></DialogActions></Dialog></Box>;
}
