import { useEffect, useMemo, useState } from 'react';
import { SaveOutlined } from '@mui/icons-material';
import { Alert, Box, Button, Container, Paper, Snackbar, Stack, Typography } from '@mui/material';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../../api/client';
import { ScreenHeader } from '../../../components/ScreenHeader';
import type { Environment, Group, User } from '../../../types';
import type { AccessLevel } from './AccessLevelSelector';
import { AccessSubjectsPanel } from './AccessSubjectsPanel';
import { PermissionCards } from './PermissionCards';
import type { AccessDomain, MatrixRow } from './types';

type AssignmentPayload={levels:Record<string,AccessLevel|'mixed'>};
const EMPTY_DOMAINS:AccessDomain[]=[];
export function AccessPage(){
  const client=useQueryClient(); const[tab,setTab]=useState(0); const[selected,setSelected]=useState<string[]>([]); const[environment,setEnvironment]=useState(''); const[levels,setLevels]=useState<Record<string,AccessLevel>>({}); const[dirty,setDirty]=useState(false); const[saving,setSaving]=useState(false); const[toast,setToast]=useState<{severity:'success'|'error';text:string}|null>(null);
  const{data:domainData}=useQuery({queryKey:['access-domains'],queryFn:()=>api<AccessDomain[]>('/access/domains')});const domains=domainData||EMPTY_DOMAINS; const{data:users=[]}=useQuery({queryKey:['users'],queryFn:()=>api<User[]>('/users?active_only=false')}); const{data:groups=[]}=useQuery({queryKey:['groups'],queryFn:()=>api<Group[]>('/groups')}); const{data:environments=[]}=useQuery({queryKey:['environments'],queryFn:()=>api<Environment[]>('/environments')});
  const scope=environment?`&environment_id=${environment}`:'';
  const assignments=useQuery({queryKey:['access-assignments',tab,selected,environment],queryFn:()=>api<AssignmentPayload>(`/access/assignments?subject_type=${tab===0?'users':'groups'}&subject_ids=${selected.join(',')}${scope}`),enabled:selected.length>0});
  const matrix=useQuery({queryKey:['access-matrix',tab,selected[0],environment],queryFn:()=>api<MatrixRow[]>(`/access/subjects/${tab===0?'user':'group'}/${selected[0]}/matrix?${scope.slice(1)}`),enabled:selected.length===1});
  const visibleDomains=useMemo(()=>domains.filter(domain=>environment?domain.scope==='environment'||domain.scope==='both':domain.scope==='global'||domain.scope==='both'),[domains,environment]);
  useEffect(()=>{if(dirty)return;if(!selected.length){setLevels({});return}else if(selected.length===1&&matrix.data)setLevels(Object.fromEntries(matrix.data.filter(row=>visibleDomains.some(domain=>domain.code===row.domain_code)).map(row=>[row.domain_code,row.direct_level])));else if(assignments.data)setLevels(Object.fromEntries(Object.entries(assignments.data.levels).filter(([code,value])=>value!=='mixed'&&visibleDomains.some(domain=>domain.code===code))) as Record<string,AccessLevel>)},[assignments.data,matrix.data,selected.length,dirty,visibleDomains]);
  const selectedName=selected.length===1?(tab===0?users.find(x=>x.id===selected[0])?.display_name:groups.find(x=>x.id===selected[0])?.name):selected.length?`${selected.length} פריטים נבחרו`:'לא נבחר משתמש או קבוצה';
  const isAdmin=selected.some(id=>tab===0?users.find(x=>x.id===id)?.is_system_admin:groups.find(x=>x.id===id)?.is_system_admin_group);
  async function save(){setSaving(true);try{const payload=Object.fromEntries(visibleDomains.map(domain=>[domain.code,levels[domain.code]||'inherit']));await api('/access/bulk',{method:'POST',body:JSON.stringify({subject_type:tab===0?'users':'groups',subject_ids:selected,environment_id:environment||null,levels:payload})});await Promise.all([client.invalidateQueries({queryKey:['access-assignments']}),client.invalidateQueries({queryKey:['access-matrix']}),client.invalidateQueries({queryKey:['effective-access']})]);const verified=await api<AssignmentPayload>(`/access/assignments?subject_type=${tab===0?'users':'groups'}&subject_ids=${selected.join(',')}${scope}`);if(!Object.entries(payload).every(([code,value])=>(verified.levels[code]||'inherit')===value))throw new Error('verification failed');setDirty(false);setToast({severity:'success',text:'השינויים נשמרו בהצלחה'})}catch{setToast({severity:'error',text:'שמירת ההרשאות נכשלה'})}finally{setSaving(false)}}
  return <Box className="admin-page"><Container maxWidth="xl"><Stack spacing={2.5}><ScreenHeader title="משתמשים והרשאות" subtitle="ניהול הרשאות ישירות, ירושה קבוצתית ותחולה סביבתית ממקום אחד"/>{(assignments.isError||matrix.isError)&&<Alert severity="error">לא ניתן לטעון את מטריצת ההרשאות</Alert>}{isAdmin&&<Alert severity="info">קבוצת Admin מקבלת אוטומטית הרשאת מקסימום לכל תחום קיים ועתידי.</Alert>}
    <Box className="access-layout"><Box className="access-subject-column"><AccessSubjectsPanel tab={tab} setTab={value=>{setTab(value);setDirty(false)}} users={users} groups={groups} environments={environments} environment={environment} setEnvironment={value=>{setEnvironment(value);setLevels({});setDirty(false)}} selected={selected} setSelected={value=>{setSelected(value);setDirty(false)}}/></Box><Box className="access-permission-column"><Paper className="access-heading" variant="outlined"><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" alignItems={{sm:'center'}} gap={1}><Box><Typography variant="h5">ניהול הרשאות</Typography><Typography color="text.secondary">{selectedName}{environment?` · ${environments.find(x=>x.id===environment)?.name_he}`:' · הרשאה כללית'}</Typography></Box><Button variant="contained" startIcon={<SaveOutlined/>} disabled={!selected.length||!dirty||Boolean(isAdmin)||saving} onClick={save}>{saving?'שומר…':'שמירת שינויים'}</Button></Stack></Paper><PermissionCards domains={selected.length?visibleDomains:[]} matrix={matrix.data||[]} levels={levels} onChange={(code,value)=>{setLevels(current=>({...current,[code]:value}));setDirty(true)}}/></Box></Box>
  </Stack></Container><Snackbar open={!!toast} autoHideDuration={4500} onClose={()=>setToast(null)} anchorOrigin={{vertical:'bottom',horizontal:'center'}}>{toast?<Alert severity={toast.severity} variant="filled" onClose={()=>setToast(null)}>{toast.text}</Alert>:undefined}</Snackbar></Box>;
}
