import { useEffect, useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ContentCopy } from '@mui/icons-material';
import { Alert, Box, Button, Checkbox, Container, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, MenuItem, Paper, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import { api } from '../../../api/client';
import type { Environment, Group, User } from '../../../types';
import { AccessLevelSelector, type AccessLevel } from './AccessLevelSelector';
import { useTranslation } from 'react-i18next';

type Domain = { code: string; name_he: string; description_he: string; localized_name?: string; localized_description?: string; scope: string };
type CopyMode = 'replace' | 'merge' | 'missing';
type AssignmentPayload = { levels:Record<string,AccessLevel|'mixed'> };
type MatrixRow = {domain_code:string;domain_name:string;default_level:AccessLevel;direct_level:AccessLevel;effective_level:AccessLevel;source:string;scope:string;can_override:boolean};

export function AccessPage() {
  const {t}=useTranslation();
  const client = useQueryClient();
  const [tab, setTab] = useState(0); const [selected, setSelected] = useState<string[]>([]);
  const [search, setSearch] = useState(''); const [active, setActive] = useState('all');
  const [environment, setEnvironment] = useState(''); const [levels, setLevels] = useState<Record<string, AccessLevel>>({});
  const [confirmOpen, setConfirmOpen] = useState(false); const [copyOpen, setCopyOpen] = useState(false);
  const [copySourceType, setCopySourceType] = useState<'user' | 'group'>('user'); const [copySourceId, setCopySourceId] = useState('');
  const [copyMode, setCopyMode] = useState<CopyMode>('replace'); const [copyPreview, setCopyPreview] = useState<Record<string, string>>();
  const [message, setMessage] = useState('');
  const { data: domains = [] } = useQuery({ queryKey: ['access-domains'], queryFn: () => api<Domain[]>('/access/domains') });
  const { data: users = [] } = useQuery({ queryKey: ['users'], queryFn: () => api<User[]>('/users?active_only=false') });
  const { data: groups = [] } = useQuery({ queryKey: ['groups'], queryFn: () => api<Group[]>('/groups') });
  const { data: environments = [] } = useQuery({ queryKey: ['environments'], queryFn: () => api<Environment[]>('/environments') });
  const scopeParam=environment?`&environment_id=${environment}`:'';
  const assignmentQuery=useQuery({queryKey:['access-assignments',tab,selected,environment],queryFn:()=>api<AssignmentPayload>(`/access/assignments?subject_type=${tab===0?'users':'groups'}&subject_ids=${selected.join(',')}${scopeParam}`),enabled:selected.length>0});
  const matrixQuery=useQuery({queryKey:['access-matrix',tab,selected[0],environment],queryFn:()=>api<MatrixRow[]>(`/access/subjects/${tab===0?'user':'group'}/${selected[0]}/matrix?${scopeParam.slice(1)}`),enabled:selected.length===1});
  useEffect(()=>{if(!selected.length)setLevels({});else if(selected.length===1&&matrixQuery.data)setLevels(Object.fromEntries(matrixQuery.data.map(row=>[row.domain_code,row.direct_level])));else if(assignmentQuery.data)setLevels(Object.fromEntries(Object.entries(assignmentQuery.data.levels).filter(([,value])=>value!=='mixed')) as Record<string,AccessLevel>)},[assignmentQuery.data,matrixQuery.data,selected.length]);
  const entities = useMemo(() => (tab === 0 ? users : groups).filter((item) => {
    const enabled = item.is_active !== false;
    const text = tab === 0 ? `${(item as User).display_name} ${(item as User).email}` : (item as Group).name;
    return (active === 'all' || (active === 'active') === enabled) && text.toLowerCase().includes(search.toLowerCase());
  }), [tab, users, groups, active, search]);
  const sourceItems = copySourceType === 'user' ? users : groups;
  const toggle = (id: string) => setSelected(selected.includes(id) ? selected.filter((value) => value !== id) : [...selected, id]);
  const payload = { source_type: copySourceType, source_id: copySourceId, target_type: tab === 0 ? 'users' : 'groups', target_ids: selected, environment_id: environment || null, mode: copyMode };
  async function save() { await api('/access/bulk', { method: 'POST', body: JSON.stringify({ subject_type: tab === 0 ? 'users' : 'groups', subject_ids: selected, environment_id: environment || null, levels }) }); setConfirmOpen(false); await Promise.all([client.invalidateQueries({ queryKey: ['access-assignments'] }),client.invalidateQueries({queryKey:['effective-access']})]); const fresh=selected.length===1?await matrixQuery.refetch():undefined;if(selected.length===1&&fresh?.data&&!fresh.data.every(row=>row.direct_level===(levels[row.domain_code]||'inherit')))throw new Error(t('permissions.loadFailed'));setMessage(t('permissions.saved')); }
  async function previewCopy() { const result = await api<{ source_levels: Record<string, string> }>('/access/copy/preview', { method: 'POST', body: JSON.stringify(payload) }); setCopyPreview(result.source_levels); }
  async function copyAccess() { await api('/access/copy', { method: 'POST', body: JSON.stringify(payload) }); setCopyOpen(false); setCopyPreview(undefined); setMessage(t('permissions.copied',{count:selected.length})); await Promise.all([client.invalidateQueries({ queryKey: ['access-assignments'] }),client.invalidateQueries({queryKey:['access-matrix']}),client.invalidateQueries({queryKey:['effective-access']})]); }

  return <Container maxWidth="xl"><Stack spacing={2}>
    <Box><Typography variant="h4" fontWeight={800}>{t('permissions.title')}</Typography><Typography color="text.secondary">{t('permissions.subtitle')}</Typography></Box>
    {message && <Alert severity="success" onClose={() => setMessage('')}>{message}</Alert>}
    {(assignmentQuery.isError||matrixQuery.isError)&&<Alert severity="error">{t('permissions.loadFailed')}</Alert>}
    {assignmentQuery.isLoading&&<Alert severity="info">{t('common.loading')}</Alert>}
    {tab===0&&selected.length===1&&users.find(item=>item.id===selected[0])?.is_system_admin&&<Alert severity="info">{t('permissions.systemAdmin')}</Alert>}
    <Box className="permission-grid">
      <Paper variant="outlined" sx={{ p: 2 }}><Typography variant="h6" fontWeight={800}>{t('permissions.title')}</Typography><Stack spacing={1.5} mt={2}>{domains.map((domain) => {const matrix=matrixQuery.data?.find(row=>row.domain_code===domain.code);const level=(value:AccessLevel)=>t(`common.${value}`);const source=matrix?t(`permissions.${matrix.source}`,{defaultValue:matrix.source}):'';return <Paper key={domain.code} variant="outlined" sx={{ p: 1.5, borderColor: matrix?.effective_level==='edit'?'primary.main':'divider', bgcolor: matrix?.effective_level==='edit'?'primary.50':'background.paper' }}><Typography fontWeight={800}>{domain.localized_name || domain.name_he}</Typography><Typography variant="body2" color="text.secondary">{domain.localized_description || domain.description_he} · {t(domain.scope === 'system'?'common.system':'common.environment')}</Typography>{matrix&&<Stack direction={{xs:'column',sm:'row'}} gap={2} my={1}><Typography variant="body2"><strong>{t('common.effective')}:</strong> {level(matrix.effective_level)}</Typography><Typography variant="body2"><strong>{t('common.source')}:</strong> {source}</Typography><Typography variant="body2"><strong>{t('common.default')}:</strong> {level(matrix.default_level)}</Typography><Typography variant="body2"><strong>{t('common.directOverride')}:</strong> {level(matrix.direct_level)}</Typography></Stack>}<AccessLevelSelector allowInherit={!!matrix || tab===0} inheritedLevel={matrix?.default_level} disabled={matrix?.can_override===false} value={levels[domain.code] || 'inherit'} onChange={(value) => setLevels({ ...levels, [domain.code]: value })} /></Paper>})}</Stack></Paper>
      <Paper variant="outlined" sx={{ p: 2 }}><Tabs value={tab} onChange={(_, value) => { setTab(value); setSelected([]); }}><Tab label={t('permissions.users')}/><Tab label={t('permissions.groups')}/></Tabs><Stack direction={{ xs: 'column', sm: 'row' }} gap={1} my={2}><TextField fullWidth label={t('permissions.search')} value={search} onChange={(event) => setSearch(event.target.value)} /><TextField select label={t('permissions.status')} value={active} onChange={(event) => setActive(event.target.value)}><MenuItem value="all">{t('dashboard.all')}</MenuItem><MenuItem value="active">{t('permissions.active')}</MenuItem><MenuItem value="inactive">{t('permissions.inactive')}</MenuItem></TextField></Stack><TextField fullWidth select label={t('permissions.scope')} value={environment} onChange={(event) => setEnvironment(event.target.value)}><MenuItem value="">{t('permissions.systemScope')}</MenuItem>{environments.map((item) => <MenuItem key={item.id} value={item.id}>{item.name_he}</MenuItem>)}</TextField><FormControlLabel sx={{ mt: 1 }} control={<Checkbox checked={entities.length > 0 && selected.length === entities.length} indeterminate={selected.length > 0 && selected.length < entities.length} onChange={() => setSelected(selected.length === entities.length ? [] : entities.map((item) => item.id))} />} label={t('permissions.selectAll')}/><Stack>{entities.map((item) => <FormControlLabel key={item.id} control={<Checkbox checked={selected.includes(item.id)} onChange={() => toggle(item.id)} />} label={tab === 0 ? `${(item as User).display_name} · ${(item as User).email}` : (item as Group).name} />)}</Stack></Paper>
    </Box>
    <Paper className="bulk-toolbar" elevation={4}><Typography>{t('permissions.selectionSummary',{targets:selected.length,domains:Object.keys(levels).length})}</Typography><Stack direction="row" gap={1}><Button startIcon={<ContentCopy />} disabled={!selected.length} onClick={() => setCopyOpen(true)}>{t('permissions.copy')}</Button><Button variant="contained" disabled={!selected.length || !Object.keys(levels).length} onClick={() => setConfirmOpen(true)}>{t('permissions.saveLevels')}</Button></Stack></Paper>
  </Stack>
  <Dialog open={confirmOpen} onClose={() => setConfirmOpen(false)} fullWidth><DialogTitle>{t('permissions.confirmTitle')}</DialogTitle><DialogContent><Typography>{t('permissions.confirmBody',{count:selected.length,subjects:t(tab===0?'permissions.users':'permissions.groups'),scope:environment?environments.find((item) => item.id === environment)?.name_he:t('permissions.systemScope')})}</Typography>{Object.entries(levels).map(([code, level]) => <Typography key={code}>{domains.find((item) => item.code === code)?.name_he}: {t(`common.${level}`)}</Typography>)}</DialogContent><DialogActions><Button onClick={() => setConfirmOpen(false)}>{t('common.cancel')}</Button><Button variant="contained" onClick={save}>{t('permissions.confirmSave')}</Button></DialogActions></Dialog>
  <Dialog open={copyOpen} onClose={() => setCopyOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{t('permissions.copy')}</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><Alert severity="info">{t('permissions.copyHelp',{count:selected.length})}</Alert><TextField select label={t('permissions.sourceType')} value={copySourceType} onChange={(event) => { setCopySourceType(event.target.value as 'user' | 'group'); setCopySourceId(''); setCopyPreview(undefined); }}><MenuItem value="user">{t('permissions.user')}</MenuItem><MenuItem value="group">{t('permissions.group')}</MenuItem></TextField><TextField select label={t('common.source')} value={copySourceId} onChange={(event) => { setCopySourceId(event.target.value); setCopyPreview(undefined); }}>{sourceItems.map((item) => <MenuItem key={item.id} value={item.id}>{copySourceType === 'user' ? `${(item as User).display_name} · ${(item as User).email}` : (item as Group).name}</MenuItem>)}</TextField><TextField select label={t('permissions.copyMode')} value={copyMode} onChange={(event) => { setCopyMode(event.target.value as CopyMode); setCopyPreview(undefined); }}><MenuItem value="replace">{t('permissions.replace')}</MenuItem><MenuItem value="merge">{t('permissions.merge')}</MenuItem><MenuItem value="missing">{t('permissions.missing')}</MenuItem></TextField>{copyPreview && <Paper variant="outlined" sx={{ p: 2 }}><Typography fontWeight={800}>{t('permissions.preview')}</Typography>{Object.keys(copyPreview).length ? Object.entries(copyPreview).map(([code, level]) => <Typography key={code}>{domains.find((item) => item.code === code)?.name_he || code}: {t(`common.${level}`)}</Typography>) : <Typography color="text.secondary">{t('permissions.noSourcePermissions')}</Typography>}</Paper>}</Stack></DialogContent><DialogActions><Button onClick={() => setCopyOpen(false)}>{t('common.cancel')}</Button><Button disabled={!copySourceId} onClick={previewCopy}>{t('permissions.preview')}</Button><Button variant="contained" disabled={!copySourceId || !copyPreview} onClick={copyAccess}>{t('permissions.confirmCopy')}</Button></DialogActions></Dialog>
  </Container>;
}
