import { SecurityOutlined } from '@mui/icons-material';
import { Box, Chip, Paper, Stack, Typography } from '@mui/material';
import { AccessLevelSelector, type AccessLevel } from './AccessLevelSelector';
import type { AccessDomain, MatrixRow } from './types';

const modules:Record<string,string>={user:'ניהול משתמשים',users:'ניהול משתמשים',group:'ניהול קבוצות משתמשים',groups:'ניהול קבוצות משתמשים',access:'ניהול הרשאות',permission:'ניהול הרשאות',environment:'ניהול סביבות',case:'ניהול קריאות',cases:'ניהול קריאות',report:'ניהול דוחות',approval:'ניהול אישורים',automation:'ניהול אוטומציות',global:'ניהול שדות גלובליים',system:'הגדרות מערכת'};
const levelLabel:Record<string,string>={inherit:'בירושה',none:'ללא',view:'צפייה',edit:'ניהול מלא'};
export function PermissionCards({ domains, matrix, levels, onChange }: { domains:AccessDomain[];matrix:MatrixRow[];levels:Record<string,AccessLevel>;onChange:(code:string,value:AccessLevel)=>void }) {
  const grouped=Object.entries(domains.reduce<Record<string,AccessDomain[]>>((result,domain)=>{const key=modules[domain.code.split(/[._]/)[0]]||'הרשאות נוספות';(result[key]??=[]).push(domain);return result},{}));
  if(!domains.length)return <Paper className="empty-state" variant="outlined"><Typography>יש לבחור משתמש או קבוצה להצגת ההרשאות</Typography></Paper>;
  return <Stack spacing={2}>{grouped.map(([module,rows])=><Paper key={module} className="permission-module" variant="outlined"><Stack direction="row" gap={1} alignItems="center" mb={2}><Box className="permission-module-icon"><SecurityOutlined/></Box><Typography variant="h6">{module}</Typography></Stack><Stack spacing={1.25}>{(rows||[]).map(domain=>{const item=matrix.find(row=>row.domain_code===domain.code);return <Box key={domain.code} sx={{p:1.75,border:'1px solid',borderColor:item?.effective_level==='edit'?'primary.light':'divider',borderRadius:2.5,bgcolor:item?.effective_level==='edit'?'#f7faff':'#fff'}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={1} mb={1}><Box><Typography fontWeight={800}>{domain.localized_name||domain.name_he}</Typography><Typography variant="body2" color="text.secondary">{domain.localized_description||domain.description_he}</Typography></Box>{item&&<Stack direction="row" gap={.75} flexWrap="wrap"><Chip size="small" color="primary" variant="outlined" label={`אפקטיבי: ${levelLabel[item.effective_level]}`}/><Chip size="small" variant="outlined" label={`מקור: ${item.source}`}/></Stack>}</Stack><AccessLevelSelector allowInherit={!!item} inheritedLevel={item?.default_level} disabled={item?.can_override===false} value={levels[domain.code]||'inherit'} onChange={value=>onChange(domain.code,value)}/></Box>})}</Stack></Paper>)}</Stack>;
}
