import { useEffect, useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Accordion, AccordionDetails, AccordionSummary, Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, MenuItem, Stack, Switch, Tab, Tabs, TextField, Typography } from '@mui/material';
import { ExpandMore } from '@mui/icons-material';
import { api } from '../../../api/client';
import type { Environment, Group, User } from '../../../types';
import { AccessLevelSelector, type AccessLevel } from '../access/AccessLevelSelector';
import type { PermissionDomain } from '../users/UserEditor/types';

type GroupDetails = Group & { members: { id: string; display_name: string; email: string }[] };
function GroupPermissions({ group, environmentId }: { group: Group; environmentId: string }) {
  const client = useQueryClient(); const [levels, setLevels] = useState<Record<string, AccessLevel>>({}); const [message, setMessage] = useState('');
  const { data: domains = [] } = useQuery({ queryKey: ['access-domains'], queryFn: () => api<PermissionDomain[]>('/access/domains') });
  const { data } = useQuery({ queryKey: ['group-access', group.id, environmentId], queryFn: () => api<{ levels: Record<string, AccessLevel> }>(`/access/assignments?subject_type=groups&subject_ids=${group.id}${environmentId ? `&environment_id=${environmentId}` : ''}`) });
  useEffect(() => { setLevels(data?.levels || {}); }, [data]);
  const visible = domains.filter((domain) => environmentId ? domain.scope !== 'global' : domain.scope !== 'environment'); const categories = useMemo(() => [...new Set(visible.map((domain) => domain.category))], [visible]);
  async function save() { await api('/access/bulk', { method: 'POST', body: JSON.stringify({ subject_type: 'groups', subject_ids: [group.id], environment_id: environmentId || null, levels }) }); setMessage('הרשאות הקבוצה נשמרו'); await client.invalidateQueries({ queryKey: ['group-access', group.id] }); }
  return <Stack spacing={1.5}>{message && <Alert severity="success">{message}</Alert>}{categories.map((category) => <Accordion key={category} defaultExpanded><AccordionSummary expandIcon={<ExpandMore/>}><Typography fontWeight={800}>{category}</Typography></AccordionSummary><AccordionDetails><Stack spacing={1.5}>{visible.filter((domain) => domain.category === category).map((domain) => <Stack key={domain.code} spacing={1}><Typography fontWeight={700}>{domain.name_he}</Typography><Typography variant="caption">{domain.description_he}</Typography><AccessLevelSelector value={levels[domain.code] || 'none'} onChange={(level) => setLevels({ ...levels, [domain.code]: level })}/></Stack>)}</Stack></AccordionDetails></Accordion>)}<Button variant="contained" onClick={save}>שמירת הרשאות</Button></Stack>;
}

export function GroupEditor({ group, users, environments, onClose, onSaved }: { group?: Group; users: User[]; environments: Environment[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const [tab, setTab] = useState(0); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [active, setActive] = useState(true); const [members, setMembers] = useState<string[]>([]); const [environmentId, setEnvironmentId] = useState('');
  const { data: details } = useQuery({ queryKey: ['group-details', group?.id], queryFn: () => api<GroupDetails>(`/groups/${group!.id}`), enabled: !!group });
  useEffect(() => { if (group) { setTab(0); setName(group.name); setDescription(group.description || ''); setActive(group.is_active); } }, [group]); useEffect(() => setMembers(details?.members.map((member) => member.id) || []), [details]);
  async function saveDetails() { if (!group) return; await api(`/groups/${group.id}`, { method: 'PATCH', body: JSON.stringify({ name, description: description || null, is_active: active }) }); await onSaved(); }
  async function saveMembers() { if (!group) return; const before = new Set(details?.members.map((member) => member.id) || []); for (const id of members) if (!before.has(id)) await api(`/groups/${group.id}/members`, { method: 'POST', body: JSON.stringify({ user_id: id }) }); for (const id of before) if (!members.includes(id)) await api(`/groups/${group.id}/members/${id}`, { method: 'DELETE' }); await onSaved(); }
  return <Dialog open={!!group} onClose={onClose} fullWidth maxWidth="lg" fullScreen={window.innerWidth < 600}><DialogTitle>{group?.name}</DialogTitle>{group && <><Tabs value={tab} onChange={(_, value) => setTab(value)} variant="scrollable"><Tab label="פרטים"/><Tab label="משתמשים"/><Tab label="הרשאות"/><Tab label="הרשאות לפי סביבה"/></Tabs><DialogContent dividers>{tab === 0 && <Stack spacing={2}><TextField label="שם הקבוצה" value={name} onChange={(event) => setName(event.target.value)}/><TextField label="תיאור" multiline value={description} onChange={(event) => setDescription(event.target.value)}/><FormControlLabel control={<Switch checked={active} onChange={(event) => setActive(event.target.checked)}/>} label="קבוצה פעילה"/><Button variant="contained" onClick={saveDetails}>שמירת פרטים</Button></Stack>}{tab === 1 && <Stack spacing={2}><Typography>{members.length} משתמשים בקבוצה</Typography><TextField select SelectProps={{ multiple: true }} label="משתמשים" value={members} onChange={(event) => setMembers(typeof event.target.value === 'string' ? event.target.value.split(',') : event.target.value)}>{users.map((user) => <MenuItem key={user.id} value={user.id}>{user.display_name} · {user.email}</MenuItem>)}</TextField><Button variant="contained" onClick={saveMembers}>שמירת משתמשים</Button></Stack>}{tab === 2 && <GroupPermissions group={group} environmentId=""/>}{tab === 3 && <Stack spacing={2}><TextField select label="סביבה" value={environmentId} onChange={(event) => setEnvironmentId(event.target.value)}>{environments.map((environment) => <MenuItem key={environment.id} value={environment.id}>{environment.name_he}</MenuItem>)}</TextField>{environmentId && <GroupPermissions group={group} environmentId={environmentId}/>}</Stack>}</DialogContent></>}<DialogActions><Button onClick={onClose}>סגירה</Button></DialogActions></Dialog>;
}
