import { useState } from 'react';
import { Add } from '@mui/icons-material';
import { Alert, Button, MenuItem, Paper, Snackbar, Stack, TextField, Typography } from '@mui/material';
import { api } from '../../../api/client';
import type { Environment, Group, Role, User } from '../../../types';
import { GroupDialog, type GroupFormValues } from './GroupDialog';

export function GroupsTab({ groups, users, roles, environments, onCreated }: { groups: Group[]; users: User[]; roles: Role[]; environments: Environment[]; onCreated: () => Promise<void> | void }) {
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(false);
  const [selectedGroupId,setSelectedGroupId]=useState(''); const[memberUserId,setMemberUserId]=useState(''); const[environmentId,setEnvironmentId]=useState(''); const[roleId,setRoleId]=useState('');
  async function create(values: GroupFormValues) { setSaving(true); setError(''); try { await api('/groups', { method: 'POST', body: JSON.stringify({ ...values, description: values.description?.trim() || null, is_active: true }) }); await onCreated(); setOpen(false); setSuccess(true); } catch (caught) { setError((caught as Error).message); throw caught; } finally { setSaving(false); } }
  async function addMember(){try{await api(`/groups/${selectedGroupId}/members`,{method:'POST',body:JSON.stringify({user_id:memberUserId})});setMemberUserId('');setSuccess(true);await onCreated()}catch(caught){setError((caught as Error).message)}}
  async function assignRole(){try{await api(`/groups/${selectedGroupId}/roles`,{method:'POST',body:JSON.stringify({environment_id:environmentId,role_id:roleId})});setSuccess(true)}catch(caught){setError((caught as Error).message)}}
  return <Stack spacing={2}>{error && <Alert severity="error">{error}</Alert>}<Button sx={{ alignSelf: 'flex-start' }} variant="contained" startIcon={<Add />} onClick={() => { setError(''); setOpen(true); }}>קבוצה חדשה</Button>{groups.length === 0 ? <Paper sx={{ p: 5, textAlign: 'center' }}>אין קבוצות. צרו קבוצה ראשונה לצוות עבודה.</Paper> : groups.map((group) => <Paper key={group.id} variant="outlined" onClick={()=>setSelectedGroupId(group.id)} sx={{ p: 2,cursor:'pointer',borderColor:selectedGroupId===group.id?'primary.main':undefined }}><Typography fontWeight={700}>{group.name}</Typography><Typography color="text.secondary">{group.description || 'ללא תיאור'}</Typography><Typography variant="caption">{group.member_count} חברים</Typography></Paper>)}{selectedGroupId&&<Paper variant="outlined" sx={{p:2}}><Typography fontWeight={800}>ניהול הקבוצה שנבחרה</Typography><Stack spacing={1.5} sx={{mt:1.5}}><Stack direction={{xs:'column',md:'row'}} spacing={1}><TextField select fullWidth label="משתמש להוספה" value={memberUserId} onChange={event=>setMemberUserId(event.target.value)}>{users.map(user=><MenuItem key={user.id} value={user.id}>{user.display_name} · {user.email}</MenuItem>)}</TextField><Button variant="outlined" disabled={!memberUserId} onClick={addMember}>הוספה לקבוצה</Button></Stack><Stack direction={{xs:'column',md:'row'}} spacing={1}><TextField select fullWidth label="סביבה" value={environmentId} onChange={event=>setEnvironmentId(event.target.value)}>{environments.map(environment=><MenuItem key={environment.id} value={environment.id}>{environment.name_he}</MenuItem>)}</TextField><TextField select fullWidth label="Role" value={roleId} onChange={event=>setRoleId(event.target.value)}>{roles.filter(role=>role.scope==='environment').map(role=><MenuItem key={role.id} value={role.id}>{role.name}</MenuItem>)}</TextField><Button variant="contained" disabled={!environmentId||!roleId} onClick={assignRole}>שיוך Role</Button></Stack></Stack></Paper>}<GroupDialog open={open} saving={saving} onClose={() => setOpen(false)} onSubmit={create} /><Snackbar open={success} autoHideDuration={3500} onClose={() => setSuccess(false)} message="הפעולה הושלמה בהצלחה" /></Stack>;
}
