import { useEffect, useState } from 'react';
import { Button, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, FormHelperText, MenuItem, Stack, Switch, TextField } from '@mui/material';
import type { GlobalField } from './types';
import { fieldTypes } from './types';

const empty = { label_he:'', label_en:'', field_type:'text', is_required:false, is_active:true, track_history:false, semantic_binding:null as string|null };
export function GlobalFieldDialog({ open, field, onClose, onSave }: { open: boolean; field?: GlobalField; onClose: () => void; onSave: (value: typeof empty) => Promise<void> }) {
  const [value,setValue]=useState(empty); const [saving,setSaving]=useState(false);
  useEffect(()=>setValue(field?{label_he:field.label_he,label_en:field.label_en,field_type:field.field_type,is_required:field.is_required,is_active:field.is_active,track_history:field.track_history,semantic_binding:field.semantic_binding||null}:empty),[field,open]);
  const semanticOptions=value.field_type==='user'?[['case.assignee','מטפל']]:value.field_type==='single_select'?[['case.status','סטטוס'],['case.priority','עדיפות'],['case.sub_priority','תת עדיפות']]:[];
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{field?'עריכת שדה גלובלי':'הוספת שדה גלובלי'}</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField label="שם שדה בעברית" value={value.label_he} onChange={e=>setValue({...value,label_he:e.target.value})}/><TextField label="שם שדה באנגלית" value={value.label_en} onChange={e=>setValue({...value,label_en:e.target.value})}/><TextField select label="סוג שדה" value={value.field_type} onChange={e=>setValue({...value,field_type:e.target.value,semantic_binding:null})}>{fieldTypes.map(([key,label])=><MenuItem key={key} value={key}>{label}</MenuItem>)}</TextField><TextField select label="משמעות עסקית" value={value.semantic_binding||''} disabled={!semanticOptions.length} onChange={e=>setValue({...value,semantic_binding:e.target.value||null})}><MenuItem value="">ללא</MenuItem>{semanticOptions.map(([key,label])=><MenuItem key={key} value={key}>{label}</MenuItem>)}</TextField><Stack direction="row" gap={3} flexWrap="wrap"><FormControlLabel control={<Switch checked={value.is_required} onChange={e=>setValue({...value,is_required:e.target.checked})}/>} label="חובה"/><FormControlLabel control={<Switch checked={value.is_active} onChange={e=>setValue({...value,is_active:e.target.checked})}/>} label="פעיל"/><Stack><FormControlLabel control={<Switch checked={value.track_history} onChange={e=>setValue({...value,track_history:e.target.checked})}/>} label="שמירת היסטוריית שינויים"/><FormHelperText>בעת שינוי ערך יישמרו המשתמש, המועד, הערך הקודם והערך החדש.</FormHelperText></Stack></Stack></Stack></DialogContent><DialogActions><Button onClick={onClose}>ביטול</Button><Button variant="contained" disabled={!value.label_he.trim()||saving} onClick={async()=>{setSaving(true);try{await onSave(value)}finally{setSaving(false)}}}>שמירה</Button></DialogActions></Dialog>;
}
