import { useState } from 'react';
import { DndContext, closestCenter, type DragEndEvent } from '@dnd-kit/core';
import { SortableContext, arrayMove, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { DeleteOutline, DragIndicator } from '@mui/icons-material';
import { Button, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, Stack, Switch, TextField, Typography } from '@mui/material';
import type { GlobalField, GlobalOption } from './types';

function OptionRow({ option, onUpdate, onRemove }: { option: GlobalOption; onUpdate: (option: GlobalOption, labelHe: string, labelEn: string, active: boolean) => void; onRemove: (option: GlobalOption) => void }) {
  const sortable=useSortable({id:option.id}); const [labelHe,setLabelHe]=useState(option.label_he); const [labelEn,setLabelEn]=useState(option.label_en);
  const persist=()=>labelHe.trim()&&(labelHe!==option.label_he||labelEn!==option.label_en)&&onUpdate(option,labelHe,labelEn,option.is_active);
  return <Stack ref={sortable.setNodeRef} direction={{xs:'column',sm:'row'}} gap={1} alignItems={{sm:'center'}} sx={{p:1.25,border:'1px solid',borderColor:'divider',borderRadius: '8px',transform:CSS.Transform.toString(sortable.transform),transition:sortable.transition,bgcolor:'background.paper'}}><IconButton {...sortable.attributes} {...sortable.listeners} aria-label={`גרירת ${option.label_he}`}><DragIndicator/></IconButton><TextField size="small" fullWidth label="שם בעברית" value={labelHe} onChange={e=>setLabelHe(e.target.value)} onBlur={persist}/><TextField size="small" fullWidth label="תרגום באנגלית" value={labelEn} onChange={e=>setLabelEn(e.target.value)} onBlur={persist}/><Switch checked={option.is_active} inputProps={{'aria-label':'פעיל'}} onChange={e=>onUpdate(option,labelHe,labelEn,e.target.checked)}/><IconButton color="error" aria-label="מחיקה" onClick={()=>onRemove(option)}><DeleteOutline/></IconButton></Stack>;
}
export function GlobalOptionsDialog({ field, onClose, onAdd, onUpdate, onRemove, onReorder }: { field?: GlobalField; onClose: () => void; onAdd: (labelHe: string, labelEn: string) => Promise<void>; onUpdate: (option: GlobalOption, labelHe: string, labelEn: string, active: boolean) => void; onRemove: (option: GlobalOption) => void; onReorder: (ids: string[]) => void }) {
  const [labelHe,setLabelHe]=useState(''); const [labelEn,setLabelEn]=useState(''); if(!field)return null;
  const drag=(event:DragEndEvent)=>{if(!event.over||event.active.id===event.over.id)return;const next=arrayMove(field.options,field.options.findIndex(x=>x.id===event.active.id),field.options.findIndex(x=>x.id===event.over?.id));onReorder(next.map(x=>x.id));};
  return <Dialog open onClose={onClose} fullWidth maxWidth="md"><DialogTitle>ניהול ערכים · {field.label_he}</DialogTitle><DialogContent><Typography color="text.secondary" mb={2}>הסדר נשמר באמצעות גרירה. ערך שנמצא בשימוש יושבת במקום להימחק.</Typography><DndContext collisionDetection={closestCenter} onDragEnd={drag}><SortableContext items={field.options.map(x=>x.id)} strategy={verticalListSortingStrategy}><Stack spacing={1}>{field.options.map(option=><OptionRow key={option.id} option={option} onUpdate={onUpdate} onRemove={onRemove}/>)}</Stack></SortableContext></DndContext><Stack direction={{xs:'column',sm:'row'}} gap={1} mt={2}><TextField fullWidth label="ערך חדש בעברית" value={labelHe} onChange={e=>setLabelHe(e.target.value)}/><TextField fullWidth label="תרגום באנגלית" value={labelEn} onChange={e=>setLabelEn(e.target.value)}/><Button variant="contained" disabled={!labelHe.trim()} onClick={async()=>{await onAdd(labelHe,labelEn);setLabelHe('');setLabelEn('')}}>הוספה</Button></Stack></DialogContent><DialogActions><Button onClick={onClose}>סגירה</Button></DialogActions></Dialog>;
}
