DOMAIN_DEFINITIONS = [
    ("users_manage", "ניהול משתמשים", "ניהול זהויות, מצב משתמש וסיסמאות", "משתמשים והרשאות", "global", "system.users.read", "system.users.create,system.users.update,system.users.disable,system.users.reset_password"),
    ("groups_manage", "ניהול קבוצות משתמשים", "ניהול קבוצות וחברויות", "משתמשים והרשאות", "global", "system.groups.read", "system.groups.manage"),
    ("access_manage", "ניהול הרשאות", "ניהול רמות גישה והעתקת הרשאות", "משתמשים והרשאות", "global", "system.roles.read", "system.roles.manage"),
    ("roles_manage", "ניהול תפקידים", "ניהול תפקידים כהקשר עסקי", "משתמשים והרשאות", "global", "system.roles.read", "system.roles.manage"),
    ("environments_manage", "ניהול סביבות", "צפייה וניהול סביבות עבודה", "סביבות", "both", "environment.read", "environment.manage"),
    ("environment_delete", "מחיקת סביבה", "מחיקה פיזית של סביבה ללא תלויות", "סביבות", "global", "environment.read", "environment.delete"),
    ("environment_users", "ניהול משתמשי סביבה", "ניהול שיוכי משתמשים בסביבה", "סביבות", "environment", "environment.read", "environment.users.manage"),
    ("environment_settings", "ניהול הגדרות סביבה", "ניהול סוגי קריאות, ערכים ותהליכים", "סביבות", "environment", "environment.read", "environment.manage,environment.request_types.manage,environment.forms.manage,workflow.manage"),
    ("user_fields", "ניהול שדות משתמש גלובליים", "ניהול שדות משתמש וערכיהם", "שדות", "global", "system.fields.read", "system.fields.manage"),
    ("case_fields", "ניהול שדות קריאה", "ניהול שדות וטפסי קריאה", "שדות", "environment", "environment.read", "environment.fields.manage,environment.forms.manage"),
    ("environment_fields_delete", "מחיקת שדות סביבה", "מחיקה או השבתה מבוקרת של שדות סביבה", "שדות", "environment", "environment.read", "environment.fields.delete"),
    ("system_fields_delete", "מחיקת שדות מערכת", "מחיקה או השבתה מבוקרת של שדות גלובליים", "שדות", "global", "system.fields.read", "system.fields.delete"),
    ("system_settings", "ניהול הגדרות מערכת", "ניהול תצורת מערכת רוחבית", "מערכת", "global", "system.roles.read", "system.roles.manage"),
    ("impersonation", "התחזות למשתמש", "צפייה מאובטחת במערכת בזהות משתמש אחר", "מערכת", "global", "system.impersonate_users", "system.impersonate_users"),
    ("audit_system", "צפייה ב-Audit מערכת", "צפייה ביומן הביקורת המערכתי", "מערכת", "global", "audit.read_system", "audit.read_system"),
    ("cases_create", "פתיחת קריאות", "פתיחת קריאות שירות", "קריאות שירות", "environment", "environment.read,request_type.read,case.create", "environment.read,request_type.read,case.create"),
    ("cases_view", "צפייה בקריאות", "צפייה בקריאות מורשות", "קריאות שירות", "environment", "case.read,case.read_environment,case.read_participating,case.comment,comment.public.read,comment.public.create,attachment.read,attachment.upload", "case.read,case.read_environment,case.read_participating,case.comment,comment.public.read,comment.public.create,attachment.read,attachment.upload"),
    ("cases_edit", "עריכת קריאות", "עריכת פרטי קריאה", "קריאות שירות", "environment", "case.read", "case.update"),
    ("cases_assign", "שיוך מטפל", "שיוך משתמש או קבוצה מטפלת", "קריאות שירות", "environment", "case.read", "case.assign"),
    ("cases_status", "שינוי סטטוס", "ביצוע מעברי Workflow", "קריאות שירות", "environment", "case.read", "case.change_status"),
    ("cases_participants", "ניהול משתתפים", "צפייה וניהול משתתפי קריאה", "קריאות שירות", "environment", "case.read_participating", "case.manage_participants"),
    ("cases_lock", "נעילת קריאה", "נעילה ושחרור של קריאות", "קריאות שירות", "environment", "case.read", "case.lock"),
    ("cases_transfer", "העברת קריאה בין סביבות", "העברה מבוקרת של קריאה לסביבת עבודה אחרת", "קריאות שירות", "environment", "case.read", "case.transfer_environment"),
    ("knowledge_read", "צפייה במאגר ידע", "צפייה במסמכי הידע של הסביבה", "ניהול ידע", "environment", "knowledge.read", "knowledge.read"),
    ("knowledge_query", "שאילת מאגר ידע", "חיפוש וקבלת תשובות ממסמכי הסביבה", "ניהול ידע", "environment", "knowledge.read", "knowledge.query"),
    ("knowledge_manage", "ניהול מאגר ידע", "העלאה, אינדוקס והשבתת מסמכי ידע", "ניהול ידע", "environment", "knowledge.read", "knowledge.manage"),
    ("manager_notes", "הערות מנהלים", "צפייה וכתיבה בשיחה פנימית", "קריאות שירות", "environment", "comment.manager.read", "comment.manager.create,case.internal_comment"),
    ("automation_manage", "ניהול אוטומציות", "ניהול טריגרים, תנאים ופעולות", "אוטומציות", "environment", "environment.read", "environment.rules.manage"),
    ("approvals_manage", "ניהול סבבי אישורים", "הגדרת סבבי אישורים", "אישורים", "environment", "environment.read", "environment.manage"),
    ("approvals_view", "צפייה באישורים", "צפייה בתהליכי אישור", "אישורים", "environment", "environment.read", "environment.read"),
    ("report_cases", "דוח קריאות שירות", "צפייה וייצוא של דוח הקריאות", "דוחות", "environment", "report.cases", "report.cases"),
    ("report_approvals", "דוח אישורים", "צפייה בדוח תהליכי אישור", "דוחות", "both", "report.approvals", "report.approvals"),
    ("report_users", "דוח משתמשים והרשאות", "צפייה בדוח זהויות והרשאות אפקטיביות", "דוחות", "global", "report.users", "report.users"),
    ("report_audit", "דוח Audit", "צפייה בדוח אירועי ביקורת", "דוחות", "both", "report.audit", "report.audit"),
    ("report_sla", "דוח SLA", "צפייה בדוח יעדי השירות", "דוחות", "environment", "report.sla", "report.sla"),
]


def codes(value: str) -> set[str]:
    return {code for code in value.split(",") if code}
